-- Postal Locale File
-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/postal/localization/

local AL3 = LibStub("AceLocale-3.0")
local debug = false
--[===[@debug@
debug = true
--@end-debug@]===]

local L = AL3:NewLocale("Postal", "enUS", true, debug)
if L then
L["|cffeda55fAlt-Click|r to send this item to %s."] = true
L["|cffeda55fControl-Click|r to attach similar items."] = true
L["|cffeda55fCtrl-Click|r to return it to sender."] = true
L["|cffeda55fShift-Click|r to take the contents."] = true
L[ [=[|cFFFFCC00*|r Selected mail will be batch opened or returned to sender by clicking Open or Return.
|cFFFFCC00*|r You can Shift-Click 2 checkboxes to mass select every mail between the 2 checkboxes.
|cFFFFCC00*|r You can Ctrl-Click a checkbox to mass select or unselect every mail from that sender.
|cFFFFCC00*|r Select will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r Select will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = true
L[ [=[|cFFFFCC00*|r Shift-Click to take item/money from mail.
|cFFFFCC00*|r Ctrl-Click to return mail.
|cFFFFCC00*|r Alt-Click to move an item from your inventory to the current outgoing mail (same as right click in default UI).]=] ] = true
L[ [=[|cFFFFCC00*|r Simple filters are available for various mail types.
|cFFFFCC00*|r Shift-Click the Open All button to override the filters and take ALL mail.
|cFFFFCC00*|r OpenAll will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r OpenAll will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = true
L[ [=[|cFFFFCC00*|r This module will list your contacts, friends, guild mates, alts and track the last 10 people you mailed.
|cFFFFCC00*|r It will also autocomplete all names in your BlackBook.]=] ] = true
L["A button that collects all attachments and coins from mail."] = true
L["Add check boxes to the inbox for multiple mail operations."] = true
L["Add Contact"] = true
L["Add multiple item mail tooltips"] = true
L["Adds a contact list next to the To: field."] = true
L["AH-related mail"] = true
L["All Alts"] = true
L["Allows you to copy the contents of a mail."] = true
L["Alts"] = true
L["Auto-Attach similar items on Control-Click"] = true
L["Autofill last person mailed"] = true
L["Auto-Send on Alt-Click"] = true
L["BlackBook"] = true
L["Block incoming trade requests while in a mail session."] = true
L["CarbonCopy"] = true
L["Chat Output"] = true
L["Choose"] = true
L["Clear list"] = true
L["Collected"] = true
L["Contacts"] = true
L["Copy From"] = true
L["Copy this mail"] = true
L["Delete"] = true
L["Disable Blizzard's auto-completion popup menu"] = true
L["DoNotWant"] = true
L["Enable Alt-Click to send mail"] = true
L["Exclude randoms you interacted with"] = true
L["Express"] = true
L["Friends"] = true
L["Guild"] = true
L["Help"] = true
L["In Progress"] = true
L["Keep free space"] = true
L["Mouse click short cuts for mail."] = true
L["Name auto-completion options"] = true
L["New Profile"] = true
L["New Profile Name:"] = true
L["Non-AH related mail"] = true
L["Not all messages are shown, refreshing mailbox soon to continue Open All..."] = true
L["Not taking more items as there are now only %d regular bagslots free."] = true
L["Open"] = true
L["Open All"] = true
L["Open all Auction cancelled mail"] = true
L["Open all Auction expired mail"] = true
L["Open all Auction successful mail"] = true
L["Open all Auction won mail"] = true
L["Open all mail with attachments"] = true
L["Open all Outbid on mail"] = true
L["Open mail from the Postmaster"] = true
L["OpenAll"] = true
L["Opening Speed"] = true
L["Other options"] = true
L["Part %d"] = true
L["Please post bugs or suggestions at the wowace forums thread at |cFF00FFFFhttp://forums.wowace.com/showthread.php?t=3909|r. When posting bugs, indicate your locale and Postal's version number v%s."] = true
L["Prints the amount of money collected during a mail session."] = true
L["Processing Message"] = true
L["Profile"] = true
L["Rake"] = true
L["Recently Mailed"] = true
L["Refreshing mailbox..."] = true
L["Remove Contact"] = true
L["Reset Profile"] = true
L["Return"] = true
L["Select"] = true
L["Set subject field to value of coins sent if subject is blank."] = true
L["Shows a clickable visual icon as to whether a mail will be returned or deleted on expiry."] = true
L["Skipping"] = true
L["Some Messages May Have Been Skipped."] = true
L["Thaumaturge Vashreen"] = true
L["The Postmaster"] = true
L["There are %i more messages not currently shown."] = true
L["There are %i more messages not currently shown. More should become available in %i seconds."] = true
L["TradeBlock"] = true
L["Use Mr.Plow after opening"] = true
L["Use Postal's auto-complete"] = true
L["Verbose mode"] = true
L["Wire"] = true

    if GetLocale() == "enUS" or GetLocale() == "enGB" then
        return
    end
end

L = AL3:NewLocale("Postal", "deDE")
if L then
L["|cffeda55fAlt-Click|r to send this item to %s."] = "|cffeda55fAlt-Klick|r, um diesen Gegenstand an %s zu senden."
L["|cffeda55fControl-Click|r to attach similar items."] = "|cffeda55fStrg-Klick|r, um ähnliche Gegenstände anzuhängen."
L["|cffeda55fCtrl-Click|r to return it to sender."] = "|cffeda55fStrg-Klick|r, um diesen Gegenstand zurückzusenden."
L["|cffeda55fShift-Click|r to take the contents."] = "|cffeda55fShift-Klick|r, um die Gegenstände zu entnehmen."
L[ [=[|cFFFFCC00*|r Selected mail will be batch opened or returned to sender by clicking Open or Return.
|cFFFFCC00*|r You can Shift-Click 2 checkboxes to mass select every mail between the 2 checkboxes.
|cFFFFCC00*|r You can Ctrl-Click a checkbox to mass select or unselect every mail from that sender.
|cFFFFCC00*|r Select will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r Select will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r Ausgewählte Nachrichten werden alle geöffnet oder zurückgeschickt bei Klick auf Öffnen oder Zurückschicken.
|cFFFFCC00*|r Du kannst auf zwei Kontrollkästchen Shift-Klicken, um alle Nachrichten dazwischen auszuwählen.
|cFFFFCC00*|r Du kannst mit Strg-Klick auf ein Kontrollkästchen alle Nachrichten dieses Absenders aus- oder abwählen.
|cFFFFCC00*|r "Auswählen" löscht nie Nachrichten (Nachrichten ohne Text werden automatisch vom Spiel gelöscht, sobald alle angehängten Gegenstände oder Gold entnommen wurden).
|cFFFFCC00*|r "Auswählen" überspringt Nachnahmesendungen und Nachrichten von Blizzard.
|cFFFFCC00*|r Deaktiviere den ausführlichen Modus, um den Chatspam beim Öffnen von Post abzustellen.]=]
L[ [=[|cFFFFCC00*|r Shift-Click to take item/money from mail.
|cFFFFCC00*|r Ctrl-Click to return mail.
|cFFFFCC00*|r Alt-Click to move an item from your inventory to the current outgoing mail (same as right click in default UI).]=] ] = [=[|cFFFFCC00*|r Shift-Klick, um Gegenstände/Gold aus Nachrichten zu entnehmen.
|cFFFFCC00*|r Strg-Klick, um die Nachricht zurückzuschicken.
|cFFFFCC00*|r Alt-Klick, um einen Gegenstand aus dem Inventar an die ausgehende Nachricht anzuhängen (gleich dem Rechtsklick der Standard-UI).
|cFFFFCC00*|r Ermöglicht das Durchblättern des Postfachs mit dem Mausrad.]=]
L[ [=[|cFFFFCC00*|r Simple filters are available for various mail types.
|cFFFFCC00*|r Shift-Click the Open All button to override the filters and take ALL mail.
|cFFFFCC00*|r OpenAll will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r OpenAll will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r Einfache Filter sind für verschiedene Nachrichtstypen verfügbar.
|cFFFFCC00*|r Shift-Klick auf den Knopf ''Alle öffnen" ignoriert Filter und öffnet alle Nachrichten.
|cFFFFCC00*|r "Alle öffnen" löscht niemals Nachrichten (Nachrichten ohne Text werden automatisch vom Spiel gelöscht sobald alle angehängten Gegenstände oder Gold entnommen wurden).
|cFFFFCC00*|r "Alle öffnen" überspringt Nachnahmesendungen und Nachrichten von Blizzard.
|cFFFFCC00*|r Deaktiviere den ausführlichen Modus, um den Chatspam beim Öffnen von Post abzustellen.]=]
L[ [=[|cFFFFCC00*|r This module will list your contacts, friends, guild mates, alts and track the last 10 people you mailed.
|cFFFFCC00*|r It will also autocomplete all names in your BlackBook.]=] ] = [=[|cFFFFCC00*|r Dieses Modul zeigt eine Liste deiner Kontakte, Freunde, Gildenmitglieder und Alts und merkt sich die letzten 10 Empfänger gesendeter Nachrichten.
|cFFFFCC00*|r Außerdem vervollständigt es automatisch alle Namen in deinem schwarzen Buch.]=]
L["A button that collects all attachments and coins from mail."] = "Eine Taste, die alle Anhänge und Geld von Nachrichten entnimmt."
L["Add check boxes to the inbox for multiple mail operations."] = "Fügt dem Posteingang Kontrollkästchen für zusätzliche Bearbeitungsmöglichkeiten von Nachrichten hinzu."
L["Add Contact"] = "Kontakt hinzufügen"
L["Add multiple item mail tooltips"] = "Enthaltene Gegenstände den Nachrichtentooltips hinzufügen"
L["Adds a contact list next to the To: field."] = "Setzt eine Kontaktliste neben das Empfängerfeld."
L["AH-related mail"] = "Auktionshausnachrichten"
L["All Alts"] = "Alle Charaktere"
L["Allows you to copy the contents of a mail."] = "Erlaubt Dir, die Inhalte einer Nachricht zu kopieren."
L["Alts"] = "Twinks"
L["Auto-Attach similar items on Control-Click"] = "Automatisches Anhängen ähnlicher Gegenstände bei STRG-Klick"
L["Autofill last person mailed"] = "Namen der zuletzt angeschriebenen Person automatisch einfügen"
L["Auto-Send on Alt-Click"] = "Automatisches Senden per Alt-Klick"
L["BlackBook"] = "Schwarzes Buch"
L["Block incoming trade requests while in a mail session."] = "Blockt eingehende Handelsversuche von Spielern, solange der Briefkasten geöffnet ist."
L["CarbonCopy"] = "Kopie"
L["Chat Output"] = "Chatausgabe"
L["Choose"] = "Auswählen"
L["Clear list"] = "Liste leeren"
L["Collected"] = "Gesammelt"
L["Contacts"] = "Kontakte"
L["Copy From"] = "Kopieren von"
L["Copy this mail"] = "Diese Nachricht kopieren"
L["Delete"] = "Löschen"
L["Disable Blizzard's auto-completion popup menu"] = "Blizzards Auto-Vervollständigungs-Popup-Menü deaktivieren"
L["DoNotWant"] = "Unerwünscht-Taste"
L["Enable Alt-Click to send mail"] = "Alt-Klick aktivieren, um Nachrichten zu senden."
L["Exclude randoms you interacted with"] = "Zufallsspieler, mit denen Du Kontakt hattest, ausschließen"
L["Express"] = "Express"
L["Friends"] = "Freunde"
L["Guild"] = "Gilde"
L["Help"] = "Hilfe"
L["In Progress"] = "In Bearbeitung"
L["Keep free space"] = "Platz freihalten"
L["Mouse click short cuts for mail."] = "Mauskürzel für Nachrichten."
L["Name auto-completion options"] = "Optionen für automatische Namensvervollständigung"
L["New Profile"] = "Neues Profil"
L["New Profile Name:"] = "Neuer Profilname:"
L["Non-AH related mail"] = "Nicht-AH betreffende Nachricht"
L["Not all messages are shown, refreshing mailbox soon to continue Open All..."] = "Es werden nicht alle Nachrichten angezeigt, aktualisiere den Posteingang umgehend, um mit \"Alle öffnen\" fortzufahren."
L["Not taking more items as there are now only %d regular bagslots free."] = "Es werden keine weiteren Gegenstände angenommen, weil nur mehr %s reguläre Taschenplätze frei sind."
L["Open"] = "Öffnen"
L["Open All"] = "Alle öffnen"
L["Open all Auction cancelled mail"] = "Alle 'Auktion abgebrochen'-Nachrichten öffnen"
L["Open all Auction expired mail"] = "Alle 'Auktion abgelaufen'-Nachrichten öffnen"
L["Open all Auction successful mail"] = "Alle 'Auktion erfolgreich'-Nachrichten öffnen"
L["Open all Auction won mail"] = "Alle 'Auktion gewonnen'-Nachrichten öffnen"
L["Open all mail with attachments"] = "Alle Nachrichten mit Anhängen öffnen"
L["Open all Outbid on mail"] = "Alle 'Überboten'-Nachrichten öffnen"
L["Open mail from the Postmaster"] = "Nachrichten vom Postmeister öffnen"
L["OpenAll"] = "Alles öffnen"
L["Opening Speed"] = "Öffnungsgeschwindigkeit"
L["Other options"] = "Weitere Optionen"
L["Part %d"] = "Teil %d"
L["Please post bugs or suggestions at the wowace forums thread at |cFF00FFFFhttp://forums.wowace.com/showthread.php?t=3909|r. When posting bugs, indicate your locale and Postal's version number v%s."] = "Bitte melde Fehler oder Anregungen im Wowace-Forumsthread unter |cFF00FFFFhttp://forums.wowace.com/showthread.php?t=3909|r. Wenn du Fehler meldest, gebe bitte deine Sprache und Postals Versionsnummer v%s an."
L["Prints the amount of money collected during a mail session."] = "Gibt im Chat aus, wie viel Gold bei einer Nachrichtensitzung am Briefkasten entnommen wurde."
L["Processing Message"] = "Bearbeite Nachricht"
L["Profile"] = "Profil"
L["Rake"] = "Summieren"
L["Recently Mailed"] = "Kürzlich versendet"
L["Refreshing mailbox..."] = "Aktualisiere Posteingang..."
L["Remove Contact"] = "Kontakt entfernen"
L["Reset Profile"] = "Profil zurücksetzen"
L["Return"] = "Zurück"
L["Select"] = "Auswählen"
L["Set subject field to value of coins sent if subject is blank."] = "Setzt den Betreff auf die Menge des verschickten Goldes, falls der Betreff leer ist."
L["Shows a clickable visual icon as to whether a mail will be returned or deleted on expiry."] = "Zeigt ein anklickbares visuelles Symbol, ob eine Mail zurückgeschickt oder nach ihrem Ablauf gelöscht werden wird"
L["Skipping"] = "Überspringe"
L["Some Messages May Have Been Skipped."] = "Einige Nachrichten können ausgelassen worden sein."
L["Thaumaturge Vashreen"] = "Thaumaturg Vashreen"
L["The Postmaster"] = "Der Postmeister"
L["There are %i more messages not currently shown."] = "Es gibt %i weitere Nachrichten, die im Moment nicht angezeigt werden."
L["There are %i more messages not currently shown. More should become available in %i seconds."] = "Es gibt %i weitere Nachrichten, die im Moment nicht angezeigt werden. Weitere sollten in %i Sekunden verfügbar sein."
L["TradeBlock"] = "Handelsblock"
L["Use Mr.Plow after opening"] = "Mr.Plow (Zusatzaddon) nach dem Öffnen verwenden"
L["Use Postal's auto-complete"] = "Postals automatische Vervollständigung verwenden"
L["Verbose mode"] = "Ausführlicher Modus"
L["Wire"] = "Geldbetrag im Betreff"

    return
end

L = AL3:NewLocale("Postal", "esES") or AL3:NewLocale("Postal", "esMX")
if L then
L["|cffeda55fAlt-Click|r to send this item to %s."] = "|cffeda55fAlt-Clic|r para enviar este objeto a %s"
L["|cffeda55fControl-Click|r to attach similar items."] = "|cffeda55fCtrl-Clic|r para adjuntar objetos similares."
L["|cffeda55fCtrl-Click|r to return it to sender."] = "|cffeda55fCtrl-Clic|r para devolver correo al que te lo envió."
L["|cffeda55fShift-Click|r to take the contents."] = "|cffeda55fShift-Clic|r para tomar el contenido."
L[ [=[|cFFFFCC00*|r Selected mail will be batch opened or returned to sender by clicking Open or Return.
|cFFFFCC00*|r You can Shift-Click 2 checkboxes to mass select every mail between the 2 checkboxes.
|cFFFFCC00*|r You can Ctrl-Click a checkbox to mass select or unselect every mail from that sender.
|cFFFFCC00*|r Select will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r Select will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r El correo seleccionado puede ser abierto por lotes o devuelto al remitente haciendo clic en Abrir o Devolver.
|cFFFFCC00*|r Puedes hacer Shift-Clic en 2 casillas de verificación para seleccionar el total de los correos entre las 2 casillas de verificación.
|cFFFFCC00*|r Puedes hacer Ctrl-Clic en una casilla de verificación para seleccionar o desmarcar el total de cada correo de ese remitente.
|cFFFFCC00*|r Selecciona para nunca eliminar ningún correo (correo sin texto es automáticamente borrado por el juego cuando se toman todos los objetos adjuntos y el oro).
|cFFFFCC00*|r Selecciona para omitir correos C.R. y correos de Blizzard.
|cFFFFCC00*|r Desactive la opción Modo detallado para detener el spam del chat al abrir el correo.]=]
L[ [=[|cFFFFCC00*|r Shift-Click to take item/money from mail.
|cFFFFCC00*|r Ctrl-Click to return mail.
|cFFFFCC00*|r Alt-Click to move an item from your inventory to the current outgoing mail (same as right click in default UI).]=] ] = [=[|cFFFFCC00*|r Shift-Clic para tomar objetos/dinero del correo.
|cFFFFCC00*|r Ctrl-Clic para devolver el correo.
|cFFFFCC00*|r Alt-Clic para mover un objeto del inventario al correo de salida actual (igual que clic derecho en la IU predeterminado).
|cFFFFCC00*|r Rueda del ratón para desplazarse en la bandeja de entrada.]=]
L[ [=[|cFFFFCC00*|r Simple filters are available for various mail types.
|cFFFFCC00*|r Shift-Click the Open All button to override the filters and take ALL mail.
|cFFFFCC00*|r OpenAll will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r OpenAll will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r Filtros sencillos están disponibles para los diferentes tipos de correo.
|cFFFFCC00*|r Shift-Clic en el botón Abrir todo para ignorar los filtros y abrir todos los correos.
|cFFFFCC00*|r Abrir todo nunca eliminara ningún correo (correo sin texto es automáticamente borrado por el juego cuando se toman todos los objetos adjuntos y el oro).
|cFFFFCC00*|r Abrir todo omitirá correos C.R. y correos de Blizzard.
|cFFFFCC00*|r Desactive la opción Modo detallado para detener el spam del chat al abrir el correo.]=]
L[ [=[|cFFFFCC00*|r This module will list your contacts, friends, guild mates, alts and track the last 10 people you mailed.
|cFFFFCC00*|r It will also autocomplete all names in your BlackBook.]=] ] = [=[|cFFFFCC00*|r Este módulo te mostrara tus contactos, amigos, compañeros de hermandad, personajes secundarios y listara las ultimas 10 personas a las que mandaste un correo.
|cFFFFCC00*|r Además autocompletará todos los nombres en tu libro negro.]=]
L["A button that collects all attachments and coins from mail."] = "Un botón que recoge todo lo adjunto y el dinero de los correos."
L["Add check boxes to the inbox for multiple mail operations."] = "Añade casillas de verificación a la bandeja de entrada para múltiples operaciones de correo."
L["Add Contact"] = "Añadir contacto"
L["Add multiple item mail tooltips"] = "Añadir ventana emergente en correos con múltiples objetos"
L["Adds a contact list next to the To: field."] = "Añade una lista de contactos al lado del campo Para:"
L["AH-related mail"] = "(Correo relacionado con la casa de subastas)"
L["All Alts"] = "Cualquier personaje"
L["Allows you to copy the contents of a mail."] = "Te permite copiar el contenido de un correo."
L["Alts"] = "Personajes secundarios"
L["Auto-Attach similar items on Control-Click"] = "Autoadjuntar objetos similares con Ctrl-Clic"
L["Autofill last person mailed"] = "Autorellenar con la última persona que mandaste correo"
L["Auto-Send on Alt-Click"] = "Autoenviar con Alt-Clic"
L["BlackBook"] = "Libro negro"
L["Block incoming trade requests while in a mail session."] = "Bloquea las solicitudes entrantes de comercio mientras se está en una sesión de correo."
L["CarbonCopy"] = "Copia al carbón"
L["Chat Output"] = "Chat de salida"
L["Choose"] = "Elegir"
L["Clear list"] = "Limpiar lista"
L["Collected"] = "Recogido"
L["Contacts"] = "Contactos"
L["Copy From"] = "Copiar de"
L["Copy this mail"] = "Copiar este correo"
L["Delete"] = "Borrar"
L["Disable Blizzard's auto-completion popup menu"] = "Desactivar la ventana emergente de autocompletado de Blizzard"
L["DoNotWant"] = "No quiero"
L["Enable Alt-Click to send mail"] = "Habilitar Alt-Clic para enviar correo"
L["Exclude randoms you interacted with"] = "Excluir aleatorios con los que tú interactuaste"
L["Express"] = "Rápido"
L["Friends"] = "Amigos"
L["Guild"] = "Hermandad"
L["Help"] = "Ayuda"
L["In Progress"] = "En progreso"
L["Keep free space"] = "Mantener espacio libre"
L["Mouse click short cuts for mail."] = "Atajos para el correo con clics del ratón."
L["Name auto-completion options"] = "Opciones de autocompletado de nombre"
L["New Profile"] = "Nuevo perfil "
L["New Profile Name:"] = "Nombre del perfil nuevo:"
L["Non-AH related mail"] = "Correo no relacionado con la casa de subastas"
L["Not all messages are shown, refreshing mailbox soon to continue Open All..."] = "No se muestran todos los mensajes, refrescando el buzón antes de seguir abriendo todo..."
L["Not taking more items as there are now only %d regular bagslots free."] = "No se tomarán más objetos ya que solo quedan %d espacios libres en las bolsas."
L["Open"] = "Abrir"
L["Open All"] = "Abrir todo"
L["Open all Auction cancelled mail"] = "Abrir todo el correo de subastas canceladas"
L["Open all Auction expired mail"] = "Abrir todo el correo de subastas expiradas"
L["Open all Auction successful mail"] = "Abrir todo el correo de subastas exitosas"
L["Open all Auction won mail"] = "Abrir todo el correo de subastas ganadas"
L["Open all mail with attachments"] = "Abrir todo el correo con adjuntos"
L["Open all Outbid on mail"] = "Abrir todo el correo de sobrepujas"
L["Open mail from the Postmaster"] = "Abrir todo el correo del Jefe de correos"
L["OpenAll"] = "Abrir todo"
L["Opening Speed"] = "Velocidad de apertura"
L["Other options"] = "Otras opciones"
L["Part %d"] = "Parte %d"
L["Please post bugs or suggestions at the wowace forums thread at |cFF00FFFFhttp://forums.wowace.com/showthread.php?t=3909|r. When posting bugs, indicate your locale and Postal's version number v%s."] = "Por favor, informe de errores o sugerencias en el hilo del foro de Wowace en |cFF00FFFFhttp://forums.wowace.com/showthread.php?t=3909|r. Al publicar errores, indique su localización y el número de versión de Postal v%s."
L["Prints the amount of money collected during a mail session."] = "Muestra la cantidad de dinero reunida durante una sesión de correo."
L["Processing Message"] = "Procesando mensaje"
L["Profile"] = "Perfil"
L["Rake"] = "Rastrillo"
L["Recently Mailed"] = "Enviado recientemente"
L["Refreshing mailbox..."] = "Refrescando buzón..."
L["Remove Contact"] = "Eliminar contacto"
L["Reset Profile"] = "Restablecer perfil"
L["Return"] = "Devolver"
L["Select"] = "Seleccionar"
L["Set subject field to value of coins sent if subject is blank."] = "Establece el campo Asunto con el valor del dinero enviado si el asunto está en blanco."
L["Shows a clickable visual icon as to whether a mail will be returned or deleted on expiry."] = "Muestra un icono visual interactivo si un correo se devolverá o borrará al expirar."
L["Skipping"] = "Omitir"
L["Some Messages May Have Been Skipped."] = "Algunos mensajes pueden haberse omitido."
L["Thaumaturge Vashreen"] = "Taumaturgo Vahsreen"
L["The Postmaster"] = "El Jefe de correos"
L["There are %i more messages not currently shown."] = "Hay %i mensajes más por mostrar."
L["There are %i more messages not currently shown. More should become available in %i seconds."] = "Hay %i mensajes más por mostrar. Estarán disponibles en %i segundos."
L["TradeBlock"] = "Bloquear comercio"
L["Use Mr.Plow after opening"] = "Utilice Mr.Plow después de abrir"
L["Use Postal's auto-complete"] = "Usar el autocompletado de Postal"
L["Verbose mode"] = "Modo detallado"
L["Wire"] = "Telegrama"

    return
end

L = AL3:NewLocale("Postal", "frFR")
if L then
L["|cffeda55fAlt-Click|r to send this item to %s."] = "|cffeda55fAlt+clic gauche|r pour envoyer cet objet à %s."
L["|cffeda55fControl-Click|r to attach similar items."] = "|cffeda55fCtrl+clic|r pour joindre les objets similaires."
L["|cffeda55fCtrl-Click|r to return it to sender."] = "|cffeda55fCtrl+clic gauche|r pour renvoyer à l'expéditeur."
L["|cffeda55fShift-Click|r to take the contents."] = "|cffeda55fMaj+clic gauche|r pour récupérer le contenu."
L[ [=[|cFFFFCC00*|r Selected mail will be batch opened or returned to sender by clicking Open or Return.
|cFFFFCC00*|r You can Shift-Click 2 checkboxes to mass select every mail between the 2 checkboxes.
|cFFFFCC00*|r You can Ctrl-Click a checkbox to mass select or unselect every mail from that sender.
|cFFFFCC00*|r Select will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r Select will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r Les courriers sélectionnés seront ouverts ou renvoyés selon si vous avez cliqué sur Ouvrir ou Renvoi.
|cFFFFCC00*|r Vous pouvez faire Maj+clic gauche sur 2 cases à cocher afin de sélectionner tous les courriers présents entre ces 2 cases.
|cFFFFCC00*|r Vous pouvez faire Ctrl+clic gauche sur une case à cocher pour (dé)sélectionner tous les courriers de cet expéditeur.
|cFFFFCC00*|r Select ne supprimera jamais aucun courrier (les courriers sans texte sont automatiquement supprimés par le jeu quand tous les objets joints et tout l'argent ont été pris).
|cFFFFCC00*|r Select n'ouvrira pas les courriers C.R. ainsi que ceux provenant de Blizzard.
|cFFFFCC00*|r Désactiver l'option Bavard pour enlever le spam dans le chat pendant l'ouverture du courrier.]=]
L[ [=[|cFFFFCC00*|r Shift-Click to take item/money from mail.
|cFFFFCC00*|r Ctrl-Click to return mail.
|cFFFFCC00*|r Alt-Click to move an item from your inventory to the current outgoing mail (same as right click in default UI).]=] ] = [=[|cFFFFCC00*|r Maj+clic gauche pour récupérer le contenu du courrier.
|cFFFFCC00*|r Ctrl+clic gauche pour renvoyer le courrier.
|cFFFFCC00*|r Alt+clic gauche pour déplacer un objet de votre inventaire vers le courrier sortant actuel (même comportement que le clic droit dans l'IU par défaut).]=]
L[ [=[|cFFFFCC00*|r Simple filters are available for various mail types.
|cFFFFCC00*|r Shift-Click the Open All button to override the filters and take ALL mail.
|cFFFFCC00*|r OpenAll will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r OpenAll will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r Des filtres sont disponibles pour les différents types de courrier.
|cFFFFCC00*|r Maj+clic gauche sur le bouton "Tout ouvrir" outrepassera les filtres et ouvrira TOUS les courriers.
|cFFFFCC00*|r Tout Ouvrir ne supprimera jamais un courrier (les courriers sans texte sont automatiquement supprimés par le jeu quand tous les objets joints et tout l'argent ont été récupérés).
|cFFFFCC00*|r Tout Ouvrir n'ouvrira pas les courriers C.R. ainsi que ceux provenant de Blizzard.
|cFFFFCC00*|r Désactiver l'option Bavard pour enlever le spam de la fenêtre de discussion pendant l'ouverture du courrier.]=]
L[ [=[|cFFFFCC00*|r This module will list your contacts, friends, guild mates, alts and track the last 10 people you mailed.
|cFFFFCC00*|r It will also autocomplete all names in your BlackBook.]=] ] = [=[|cFFFFCC00*|r Ce module affichera vos contacts, amis, membres de guilde, rerolls ainsi que les 10 dernières personnes contactées.
|cFFFFCC00*|r De plus il complétera automatiquement tous les noms présents dans votre Répertoire.]=]
L["A button that collects all attachments and coins from mail."] = "Un bouton qui récupère toutes les pièces jointes et l'argent des courriers."
L["Add check boxes to the inbox for multiple mail operations."] = "Ajoute des cases à cocher à la boîte de réception pour gérer plusieurs courriers en même temps."
L["Add Contact"] = "Ajouter un contact"
L["Add multiple item mail tooltips"] = "Afficher plusieurs objets dans l'infobulle du courrier"
L["Adds a contact list next to the To: field."] = "Ajoute une liste des contacts à côté du champ \"À :\"."
L["AH-related mail"] = "Courriers relatifs à l'HV"
L["All Alts"] = "Tous les rerolls"
L["Allows you to copy the contents of a mail."] = "Permet de copier le contenu d'un courrier."
L["Alts"] = "Rerolls"
L["Auto-Attach similar items on Control-Click"] = "Joindre les objets similaires avec Ctrl+clic"
L["Autofill last person mailed"] = "Saisie auto. de la dernière personne contactée"
L["Auto-Send on Alt-Click"] = "Envoi auto. avec Alt+clic gauche"
L["BlackBook"] = "Répertoire"
L["Block incoming trade requests while in a mail session."] = "Bloque les demandes d'échanges lors de la consultation du courrier."
L["CarbonCopy"] = "Copie conforme"
L["Chat Output"] = "Sortie dans le chat"
L["Choose"] = "Choisir"
L["Clear list"] = "Effacer la liste"
L["Collected"] = "Récupéré"
L["Contacts"] = "Contacts"
L["Copy From"] = "Copier à partir de"
L["Copy this mail"] = "Copier ce courrier"
L["Delete"] = "Supprimer"
L["Disable Blizzard's auto-completion popup menu"] = "Désactiver le pop-up de saisie intuitive de Blizzard"
L["DoNotWant"] = "Ne Veux Pas"
L["Enable Alt-Click to send mail"] = "Activer Alt+clic gauche pour envoyer le courrier"
L["Exclude randoms you interacted with"] = "Exclure les inconnus avec qui vous avez interagi"
L["Express"] = "Express"
L["Friends"] = "Amis"
L["Guild"] = "Guilde"
L["Help"] = "Aide"
L["In Progress"] = "En cours"
L["Keep free space"] = "Garder de l'espace libre"
L["Mouse click short cuts for mail."] = "Raccourcis souris pour le courrier."
L["Name auto-completion options"] = "Options de la saisie intuitive des noms"
L["New Profile"] = "Nouveau profil"
L["New Profile Name:"] = "Nom du nouveau profil :"
L["Non-AH related mail"] = "Courriers non relatifs à l'HV"
L["Not all messages are shown, refreshing mailbox soon to continue Open All..."] = "Tous les courriers ne sont pas affichés, réouvrir la boîte aux lettres dans quelques secondes pour pouvoir tous les ouvrir..."
L["Not taking more items as there are now only %d regular bagslots free."] = "N'accepte pas plus d'objets car il n'y a plus que %d espace(s) libre(s) dans vos sacs."
L["Open"] = "Ouvrir"
L["Open All"] = "Tout ouvrir"
L["Open all Auction cancelled mail"] = "Ouvrir tous les courriers des enchères annulées"
L["Open all Auction expired mail"] = "Ouvrir tous les courriers des enchères expirées"
L["Open all Auction successful mail"] = "Ouvrir tous les courriers des enchères réussies"
L["Open all Auction won mail"] = "Ouvrir tous les courriers des enchères gagnées"
L["Open all mail with attachments"] = "Ouvrir tous les courriers avec pièces jointes"
L["Open all Outbid on mail"] = "Ouvrir tous les courriers des enchères surenchéries"
L["Open mail from the Postmaster"] = "Ouvrir tous les courriers du maître de poste"
L["OpenAll"] = "Tout Ouvrir"
L["Opening Speed"] = "Vitesse d'ouverture"
L["Other options"] = "Autres options"
L["Part %d"] = "Partie %d"
L["Please post bugs or suggestions at the wowace forums thread at |cFF00FFFFhttp://forums.wowace.com/showthread.php?t=3909|r. When posting bugs, indicate your locale and Postal's version number v%s."] = "Merci de signaler les bogues ou de faire part de vos suggestions sur le sujet du forum WoWAce dédié à Postal : |cFF00FFFFhttp://forums.wowace.com/showthread.php?t=3909|r. Lors du signalement d'un bogue, indiquez la langue de votre jeu ainsi que le numéro de version de Postal v%s."
L["Prints the amount of money collected during a mail session."] = "Indique la quantité d'argent récoltée pendant la consultation du courrier."
L["Processing Message"] = "En cours"
L["Profile"] = "Profil"
L["Rake"] = "Râteau"
L["Recently Mailed"] = "Récents"
L["Refreshing mailbox..."] = "Rafraichir la boîte aux lettres..."
L["Remove Contact"] = "Supprimer un contact"
L["Reset Profile"] = "Réinitialiser le profil"
L["Return"] = "Renvoi"
L["Select"] = "Sélectionner"
L["Set subject field to value of coins sent if subject is blank."] = "Indique dans le sujet le montant d'argent envoyé si le sujet est vide."
L["Shows a clickable visual icon as to whether a mail will be returned or deleted on expiry."] = "Affiche une icône visuelle cliquable indiquant si le courrier sera renvoyé ou supprimé à son expiration."
L["Skipping"] = "Passe"
L["Some Messages May Have Been Skipped."] = "Certains messages n'ont peut-être pas été ouverts."
L["Thaumaturge Vashreen"] = "Thaumaturge Vashreen"
L["The Postmaster"] = "Le maître de poste"
L["There are %i more messages not currently shown."] = "%i messages supplémentaires ne sont pas affichés."
L["There are %i more messages not currently shown. More should become available in %i seconds."] = "%i messages supplémentaires ne sont pas affichés. D'autres devraient devenir disponible d'ici %i secondes."
L["TradeBlock"] = "Bloqueur d'échanges"
L["Use Mr.Plow after opening"] = "Utilisez Mr.Plow après l'ouverture"
L["Use Postal's auto-complete"] = "Utiliser la saisie intuitive de Postal"
L["Verbose mode"] = "Mode Bavard"
L["Wire"] = "Câbler"

    return
end

L = AL3:NewLocale("Postal", "koKR")
if L then
L["|cffeda55fAlt-Click|r to send this item to %s."] = "|cffeda55fAlt-클릭|r으로 이 아이템을 %s님에게 보냅니다."
L["|cffeda55fControl-Click|r to attach similar items."] = "|cffeda55fCtrl-클릭|r으로 같은 종류의 아이템을 첨부합니다."
L["|cffeda55fCtrl-Click|r to return it to sender."] = "|cffeda55fCtrl-클릭|r으로 반송합니다."
L["|cffeda55fShift-Click|r to take the contents."] = "|cffeda55fShift-클릭|r으로 내용물을 수취합니다."
L[ [=[|cFFFFCC00*|r Selected mail will be batch opened or returned to sender by clicking Open or Return.
|cFFFFCC00*|r You can Shift-Click 2 checkboxes to mass select every mail between the 2 checkboxes.
|cFFFFCC00*|r You can Ctrl-Click a checkbox to mass select or unselect every mail from that sender.
|cFFFFCC00*|r Select will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r Select will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r 열기 또는 반송 버튼을 클릭하면 선택된 우편을 모두 열거나 반송합니다.
|cFFFFCC00*|r 2개의 체크 박스를 Shift-클릭하면 2개 체크 박스 사이의 모든 우편을 선택할 수 있습니다.
|cFFFFCC00*|r 체크 박스를 Ctrl-클릭하면 발송자의 모든 우편물을 선택하거나 해제할 수 있습니다.
|cFFFFCC00*|r 선택된 우편물은 삭제하지 않습니다 (기본적으로 내용이 없는 우편물은 첨부된 모든 아이템과 골드를 취득하면 자동으로 삭제됩니다).
|cFFFFCC00*|r 선택된 대금 청구 우편물과 블리자드 우편물은 무시합니다.
|cFFFFCC00*|r 우편을 여는 동안 대화 스팸을 중지하려면 대화창 메시지 표시 옵션을 비활성하세요.]=]
L[ [=[|cFFFFCC00*|r Shift-Click to take item/money from mail.
|cFFFFCC00*|r Ctrl-Click to return mail.
|cFFFFCC00*|r Alt-Click to move an item from your inventory to the current outgoing mail (same as right click in default UI).]=] ] = [=[|cFFFFCC00*|r Shift-클릭으로 우편에서 아이템/돈을 바로 취득 합니다.
|cFFFFCC00*|r Ctrl-클릭으로 우편물을 반송합니다.
|cFFFFCC00*|r Alt-클릭으로 아이템을 가방에서 우편함으로 바로 등록합니다.(기본 UI의 우-클릭과 같은 기능)]=]
L[ [=[|cFFFFCC00*|r Simple filters are available for various mail types.
|cFFFFCC00*|r Shift-Click the Open All button to override the filters and take ALL mail.
|cFFFFCC00*|r OpenAll will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r OpenAll will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r 간단한 필터는 다양한 우편 유형에 사용할 수 있습니다.
|cFFFFCC00*|r 모두 열기 버튼을 Shift-클릭하면 필터를 무시하고 모든 우편물을 바로 받습니다.
|cFFFFCC00*|r 모두 열기는 우편물을 삭제하지 않습니다. (기본적으로 내용이 없는 우편물은 첨부된 모든 아이템과 골드를 취득하면 자동으로 삭제됩니다).
|cFFFFCC00*|r 모두 열기는 대금 청구 우편과 블리자드 우편을 무시합니다.
|cFFFFCC00*|r 우편을 여는 동안 대화 스팸을 중지하려면 대화창 메시지 표시 옵션을 비활성하세요.]=]
L[ [=[|cFFFFCC00*|r This module will list your contacts, friends, guild mates, alts and track the last 10 people you mailed.
|cFFFFCC00*|r It will also autocomplete all names in your BlackBook.]=] ] = [=[|cFFFFCC00*|r 이 모듈은 당신의 연락처, 친구, 길드, 내 캐릭터 등 마지막으로 우편을 보낸 10명의 인원만 기억합니다.
|cFFFFCC00*|r 또한 주소록에 있는 모든 이름들을 자동완성 합니다.]=]
L["A button that collects all attachments and coins from mail."] = "편지에 첨부된 모든 물품과 골드를 수집하는 버튼입니다."
L["Add check boxes to the inbox for multiple mail operations."] = "여러 개의 우편을 동시에 작업할 수 있도록 받은 우편함에 체크 박스를 추가합니다."
L["Add Contact"] = "연락처 추가"
L["Add multiple item mail tooltips"] = "여러 아이템 우편물 툴팁 추가"
L["Adds a contact list next to the To: field."] = "받는이: 영역 옆에 연락처 목록을 추가합니다."
L["AH-related mail"] = "경매 관련 우편"
L["All Alts"] = "모든 다른 캐릭터"
L["Allows you to copy the contents of a mail."] = "편지의 내용을 복사합니다."
L["Alts"] = "현재 서버 다른 캐릭터"
L["Auto-Attach similar items on Control-Click"] = "Ctrl-클릭으로 같은 종류의 아이템 자동 첨부하기"
L["Autofill last person mailed"] = "마지막 수신자 자동 입력"
L["Auto-Send on Alt-Click"] = "Alt-클릭으로 자동 보내기"
L["BlackBook"] = "주소록"
L["Block incoming trade requests while in a mail session."] = "우편함이 열려 있는 동안 거래 요청을 차단합니다."
L["CarbonCopy"] = "복사본"
L["Chat Output"] = "대화창 출력"
L["Choose"] = "선택"
L["Clear list"] = "목록 삭제"
L["Collected"] = "수집되었습니다: "
L["Contacts"] = "연락처"
L["Copy From"] = "복사해오기"
L["Copy this mail"] = "이 편지 복사"
L["Delete"] = "삭제"
L["Disable Blizzard's auto-completion popup menu"] = "블리자드의 자동 완성 팝업 메뉴 비활성화"
L["DoNotWant"] = "반송된 우편"
L["Enable Alt-Click to send mail"] = "Alt-클릭으로 우편 보내기"
L["Exclude randoms you interacted with"] = "불규칙적인 거래자 제외"
L["Express"] = "빠른 우편"
L["Friends"] = "친구"
L["Guild"] = "길드"
L["Help"] = "도움말"
L["In Progress"] = "처리 중"
L["Keep free space"] = "여유 공간 유지"
L["Mouse click short cuts for mail."] = "마우스 클릭으로 빠르게 우편을 보냅니다."
L["Name auto-completion options"] = "이름 자동 완성 설정"
L["New Profile"] = "새 프로필"
L["New Profile Name:"] = "새 프로필 이름:"
L["Non-AH related mail"] = "경매장 외의 우편"
L["Not all messages are shown, refreshing mailbox soon to continue Open All..."] = "모든 메시지가 표시되지 않았습니다. 모두 열기를 계속 하기 위해 곧 우편함을 갱신합니다..."
L["Not taking more items as there are now only %d regular bagslots free."] = "현재 가방의 여유 공간이 %d칸으로 더이상 아이템을 가질 수 없습니다."
L["Open"] = "열기"
L["Open All"] = "모두 열기"
L["Open all Auction cancelled mail"] = "경매 취소된 우편 모두 열기"
L["Open all Auction expired mail"] = "경매 기한 만료된 우편 모두 열기"
L["Open all Auction successful mail"] = "경매 판매된 우편 모두 열기"
L["Open all Auction won mail"] = "경매 낙찰된 우편 모두 열기"
L["Open all mail with attachments"] = "우편에 첨부된 모든 물품 열기"
L["Open all Outbid on mail"] = "경매 상위 입찰된 우편 모두 열기"
L["Open mail from the Postmaster"] = "우체국장에게 받은 편지 열기"
L["OpenAll"] = "모두 열기"
L["Opening Speed"] = "열기 속도"
L["Other options"] = "기타 설정"
L["Part %d"] = "구성원 %d"
L["Please post bugs or suggestions at the wowace forums thread at |cFF00FFFFhttp://forums.wowace.com/showthread.php?t=3909|r. When posting bugs, indicate your locale and Postal's version number v%s."] = "|cFF00FFFFhttp://forums.wowace.com/showthread.php?t=3909|r의 wowace 포럼에서 버그 제보나 제안을 할 수 있습니다. 버그 제보 시, 귀하의 지역 언어와 버전 번호(v%s)를 알려주세요."
L["Prints the amount of money collected during a mail session."] = "우편함을 열고 있는 동안 수집되는 총 금액을 대화창에 출력합니다."
L["Processing Message"] = "메시지를 처리 중입니다:"
L["Profile"] = "프로필"
L["Rake"] = "우편 금액"
L["Recently Mailed"] = "최근 보낸 우편"
L["Refreshing mailbox..."] = "우편함을 갱신 중입니다..."
L["Remove Contact"] = "연락처 제거"
L["Reset Profile"] = "프로필 초기화"
L["Return"] = "반송"
L["Select"] = "선택"
L["Set subject field to value of coins sent if subject is blank."] = "우편으로 골드를 보낼 때 제목이 비어있는 경우 제목을 금액으로 채웁니다."
L["Shows a clickable visual icon as to whether a mail will be returned or deleted on expiry."] = "만료되어 반송되었거나 삭제된 메일에 클릭 가능한 시각적 아이콘을 표시합니다."
L["Skipping"] = "무시"
L["Some Messages May Have Been Skipped."] = "몇몇 메시지는 무시될 수 있습니다."
L["Thaumaturge Vashreen"] = "마력술사 바시린"
L["The Postmaster"] = "우체국장"
L["There are %i more messages not currently shown."] = "현재 %i개 이상의 메시지를 표시할 수 없습니다."
L["There are %i more messages not currently shown. More should become available in %i seconds."] = "현재 %i개 이상의 메시지를 표시할 수 없습니다. %i초 후에 이용이 가능합니다."
L["TradeBlock"] = "거래 차단"
L["Use Mr.Plow after opening"] = "개봉 뒤 Mr.Plow 사용"
L["Use Postal's auto-complete"] = "Postal의 자동 완성 사용"
L["Verbose mode"] = "대화창 메시지 표시"
L["Wire"] = "금액 표시"

    return
end

L = AL3:NewLocale("Postal", "ruRU")
if L then
L["|cffeda55fAlt-Click|r to send this item to %s."] = "|cffeda55fAlt+щелчок|r чтобы выслать предмет в адрес %s."
L["|cffeda55fControl-Click|r to attach similar items."] = "|cffeda55fControl+щелчок|r чтобы прикрепить аналогичные предеметы."
L["|cffeda55fCtrl-Click|r to return it to sender."] = "|cffeda55fCtrl+щелчок|r чтобы вернуть отправителю."
L["|cffeda55fShift-Click|r to take the contents."] = "|cffeda55fShift+щелчок|r чтобы взять содержимое."
L[ [=[|cFFFFCC00*|r Selected mail will be batch opened or returned to sender by clicking Open or Return.
|cFFFFCC00*|r You can Shift-Click 2 checkboxes to mass select every mail between the 2 checkboxes.
|cFFFFCC00*|r You can Ctrl-Click a checkbox to mass select or unselect every mail from that sender.
|cFFFFCC00*|r Select will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r Select will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r Все выбранные письма будут открыты или возвращены отправителю при нажатии "Открыть" или "Вернуть".
|cFFFFCC00*|r Вы можете нажать Shift+щелчок на 2 флажка для массового выбора писем между этими 2 отмеченными флажками.
|cFFFFCC00*|r Вы можете нажать Ctrl+щелчок по флажку для массового выбора или отмены выбора всех писем от данного отправителя.
|cFFFFCC00*|r Отмеченные письма никогда не будут удаляться (письма без текста автоматически удаляются игрой после получения вложенных предметов или денег).
|cFFFFCC00*|r Письма с выкупом и письма от Blizzard будут пропущены при выборе.
|cFFFFCC00*|r Отключите детальный режим для прекращения спама в чат при открытии писем.]=]
L[ [=[|cFFFFCC00*|r Shift-Click to take item/money from mail.
|cFFFFCC00*|r Ctrl-Click to return mail.
|cFFFFCC00*|r Alt-Click to move an item from your inventory to the current outgoing mail (same as right click in default UI).]=] ] = [=[|cFFFFCC00*|r Shift+щелчок снимает с почты предметы/деньги.
|cFFFFCC00*|r Ctrl+щелчок возвращает почту.
|cFFFFCC00*|r Alt+щелчок помещает предмет из вашего инвентаря в исходящую почту (как щелчок правой кнопкой в стандартном UI).
|cFFFFCC00*|r Колесо мыши прокручивает список входящей почты.]=]
L[ [=[|cFFFFCC00*|r Simple filters are available for various mail types.
|cFFFFCC00*|r Shift-Click the Open All button to override the filters and take ALL mail.
|cFFFFCC00*|r OpenAll will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r OpenAll will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r Простые фильтры доступны для различных типов почты.
|cFFFFCC00*|r Shift+щелчок по кнопке "Открыть все" игнорирует фильтры и снимет ВСЮ почту.
|cFFFFCC00*|r "Открыть все" не будет удалять почту (письма без текста автоматически удаляются игрой после получения вложенных предметов или денег).
|cFFFFCC00*|r "Открыть все" будет пропускать письма с выкупом и письма от Blizzard.
|cFFFFCC00*|r Отключите детальный режим для прекращения спама в чат при открытии писем.]=]
L[ [=[|cFFFFCC00*|r This module will list your contacts, friends, guild mates, alts and track the last 10 people you mailed.
|cFFFFCC00*|r It will also autocomplete all names in your BlackBook.]=] ] = [=[|cFFFFCC00*|r Этот модуль будет выводить список ваших контактов, друзей, согильдийцев, альтов и отслеживать последних 10 людей, которым вы отправили почту.
|cFFFFCC00*|r Будут также автозаполнены все имена в вашем черном списке.]=]
L["A button that collects all attachments and coins from mail."] = "Кнопка, которая собирает все монеты и вложения с почты."
L["Add check boxes to the inbox for multiple mail operations."] = "Добавляет окно для пометки во входящей почте, для многочисленных операций."
L["Add Contact"] = "Добавить контакт"
L["Add multiple item mail tooltips"] = "Добавить подсказку для почты со множеством вещей."
L["Adds a contact list next to the To: field."] = "Добавляет список контактов в поле адресата."
L["AH-related mail"] = "Аукционные письма"
L["All Alts"] = "Все альты"
L["Allows you to copy the contents of a mail."] = "Позволяет скопировать текст письма."
L["Alts"] = "Альты"
L["Auto-Attach similar items on Control-Click"] = "Control+щелчок автоматически прикрепляет аналогичные предметы"
L["Autofill last person mailed"] = "Ввести в строку адреса имя последнего, кому было отправлено письмо"
L["Auto-Send on Alt-Click"] = "Автопосылка по Alt+щелчок"
L["BlackBook"] = "Черный список"
L["Block incoming trade requests while in a mail session."] = "Блокировать все запросы на торговлю во время массовой отправки почты."
L["CarbonCopy"] = "Скрытая копия"
L["Chat Output"] = "Вывод чата"
L["Choose"] = "Выбор"
L["Clear list"] = "Очистить список"
L["Collected"] = "Собрано"
L["Contacts"] = "Контакты"
L["Copy From"] = "Копировать из"
L["Copy this mail"] = "Скопировать письмо"
L["Delete"] = "Удалить"
L["Disable Blizzard's auto-completion popup menu"] = "Выключить всплывающее меню авто-заполнения Blizzard"
L["DoNotWant"] = "НеХоЧу!"
L["Enable Alt-Click to send mail"] = "Включить посылку почты по Alt+щелчок"
L["Exclude randoms you interacted with"] = "Исключать ПУГов, с которыми вы встречались."
L["Express"] = "Доставка"
L["Friends"] = "Друзья"
L["Guild"] = "Гильдия"
L["Help"] = "Справка"
L["In Progress"] = "Обрабатывается"
L["Keep free space"] = "Оставлять свободное место"
L["Mouse click short cuts for mail."] = "Щелчки мыши при открытой почте применяются как ссылки"
L["Name auto-completion options"] = "Настройки авто-заполнения имён"
L["New Profile"] = "Новый профиль"
L["New Profile Name:"] = "Имя нового профиля:"
L["Non-AH related mail"] = "Почта не с аукциона"
L["Not all messages are shown, refreshing mailbox soon to continue Open All..."] = "Не все письма показаны, почтовый ящик вскоре будет обновлен. Для продолжения нажмите \"Открыть всё\"."
L["Not taking more items as there are now only %d regular bagslots free."] = "Не брать больше вещей если в сумках осталось только %d свободных мест."
L["Open"] = "Открыть"
L["Open All"] = "Открыть всё"
L["Open all Auction cancelled mail"] = "Открывать все письма с прерванных аукционов"
L["Open all Auction expired mail"] = "Открывать все письма с несостоявшихся аукционов"
L["Open all Auction successful mail"] = "Открыть все письма с успешных аукционов"
L["Open all Auction won mail"] = "Открывать все письма с выигранных аукционов"
L["Open all mail with attachments"] = "Окрыть все письма с вложениями"
L["Open all Outbid on mail"] = "Открыть все письма с перебитыми ставками"
L["Open mail from the Postmaster"] = "Окрыть все письма Почтальон"
L["OpenAll"] = "Открыть всё"
L["Opening Speed"] = "Скорость открытия"
L["Other options"] = "Прочие опции"
L["Part %d"] = "Часть %d"
L["Please post bugs or suggestions at the wowace forums thread at |cFF00FFFFhttp://forums.wowace.com/showthread.php?t=3909|r. When posting bugs, indicate your locale and Postal's version number v%s."] = "Пожалуйста, сообщите об ошибках или предложениях на форуме wowace |cFF00FFFFhttp://forums.wowace.com/showthread.php?t=3909|r. При отправке ошибки, сообщите язык вашего клиента и номер версии Postal v%s."
L["Prints the amount of money collected during a mail session."] = "Сообщить сумму денег, собранных за сеанс работы с почтой"
L["Processing Message"] = "Обработка сообщения"
L["Profile"] = "Профиль"
L["Rake"] = "Сбор"
L["Recently Mailed"] = "Недавние корреспонденты"
L["Refreshing mailbox..."] = "Обновление списка писем"
L["Remove Contact"] = "Удалить контакт"
L["Reset Profile"] = "Сброс профиля"
L["Return"] = "Вернуть"
L["Select"] = "Выбор"
L["Set subject field to value of coins sent if subject is blank."] = "Писать в теме письма количество монет, если тема не указана."
L["Shows a clickable visual icon as to whether a mail will be returned or deleted on expiry."] = "Показывать кликабельную визуальную иконку, независимо от того, была ли почта возвращена или удалена."
L["Skipping"] = "Пропускаем"
L["Some Messages May Have Been Skipped."] = "Некоторые сообщения могли быть пропущены."
L["Thaumaturge Vashreen"] = "Чудотворец Вашрин"
L["The Postmaster"] = "Почтальон"
L["There are %i more messages not currently shown."] = "В данный момент не показано ещё %i сообщений."
L["There are %i more messages not currently shown. More should become available in %i seconds."] = "В данный момент не показано ещё %i сообщений. Они будут доставлены через %i секунд."
L["TradeBlock"] = "Блокировать торговлю"
L["Use Mr.Plow after opening"] = "Использовать Mr.Plow после открытия"
L["Use Postal's auto-complete"] = "Авто-завершение использования Postal."
L["Verbose mode"] = "Детальный режим"
L["Wire"] = "Оценка"

    return
end

L = AL3:NewLocale("Postal", "zhCN")
if L then
L["|cffeda55fAlt-Click|r to send this item to %s."] = "|cffeda55fAlt+点击|r将该物品发送给%s。"
L["|cffeda55fControl-Click|r to attach similar items."] = "|cffeda55fCtrl+点击|r附加类似物品。"
L["|cffeda55fCtrl-Click|r to return it to sender."] = "|cffeda55fCtrl+点击|r将信退给发件人。"
L["|cffeda55fShift-Click|r to take the contents."] = "|cffeda55fShift+点击|r获得该邮件的内容副本。"
L[ [=[|cFFFFCC00*|r Selected mail will be batch opened or returned to sender by clicking Open or Return.
|cFFFFCC00*|r You can Shift-Click 2 checkboxes to mass select every mail between the 2 checkboxes.
|cFFFFCC00*|r You can Ctrl-Click a checkbox to mass select or unselect every mail from that sender.
|cFFFFCC00*|r Select will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r Select will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r 点击打开或者退信，被选中的邮件会被批量打开或退回。
|cFFFFCC00*|r Shift+点击分别点击2封信的复选框，会将这2封信之前的所有新选中。
|cFFFFCC00*|r Ctrl+点击一封信的复选框，可以将所有来自该发件人的信选中或者取消选中。
|cFFFFCC00*|r 选中则不删除任何邮件（游戏默认当一封没有任何文字的信中的附件被取走之后自动删除该邮件）。
|cFFFFCC00*|r 选中将跳过付款取信的邮件以及来自暴雪的邮件。
|cFFFFCC00*|r 关闭消息模式，取信时聊天窗口将不再显示信息。]=]
L[ [=[|cFFFFCC00*|r Shift-Click to take item/money from mail.
|cFFFFCC00*|r Ctrl-Click to return mail.
|cFFFFCC00*|r Alt-Click to move an item from your inventory to the current outgoing mail (same as right click in default UI).]=] ] = [=[|cFFFFCC00*|r Shift+点击取走信中的金币或者物品。
|cFFFFCC00*|r Ctrl+点击退信。
|cFFFFCC00*|r Alt+点击背包中的物品，将其添加到附件中（同游戏本身的右键点击）。]=]
L[ [=[|cFFFFCC00*|r Simple filters are available for various mail types.
|cFFFFCC00*|r Shift-Click the Open All button to override the filters and take ALL mail.
|cFFFFCC00*|r OpenAll will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r OpenAll will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r各种邮件类型都有简单的过滤条件可用。
|cFFFFCC00*|rShift+点击“打开所有”按钮可以忽略这些过滤并收取所有邮件。
|cFFFFCC00*|r打开所有功能将不会删除任何邮件（无内容邮件将在附件和金钱被收取后自动删除）。
|cFFFFCC00*|r打开所有功能将会阻止付款取信邮件和暴雪发送的邮件。
|cFFFFCC00*|r请关闭详细信息选项来取消打开邮件时的聊天窗口信息。]=]
L[ [=[|cFFFFCC00*|r This module will list your contacts, friends, guild mates, alts and track the last 10 people you mailed.
|cFFFFCC00*|r It will also autocomplete all names in your BlackBook.]=] ] = [=[|cFFFFCC00*|r该模块将列出你所有的联系人、好友、公会成员、小号和你最近发送邮件的10个人。
|cFFFFCC00*|r同时还将自动完成通讯簿中的所有名字。]=]
L["A button that collects all attachments and coins from mail."] = "收取所有邮件的附件和金币。"
L["Add check boxes to the inbox for multiple mail operations."] = "增加可选框以便于对多个邮件进行操作。"
L["Add Contact"] = "添加联系人"
L["Add multiple item mail tooltips"] = "添加多个物品的邮件提示"
L["Adds a contact list next to the To: field."] = "添加联系人列表到收件人栏。"
L["AH-related mail"] = "拍卖相关邮件"
L["All Alts"] = "全部小号"
L["Allows you to copy the contents of a mail."] = "允许你复制信的内容物。"
L["Alts"] = "小号"
L["Auto-Attach similar items on Control-Click"] = "Ctrl+点击自动附加相同物品"
L["Autofill last person mailed"] = "自动填写最后的收件人"
L["Auto-Send on Alt-Click"] = "Alt+点击自动发送"
L["BlackBook"] = "黑名单"
L["Block incoming trade requests while in a mail session."] = "在进行邮件操作中阻止交易请求。"
L["CarbonCopy"] = "复本"
L["Chat Output"] = "聊天输出"
L["Choose"] = "选择"
L["Clear list"] = "清空列表"
L["Collected"] = "已收取"
L["Contacts"] = "联系人"
L["Copy From"] = "从…复制"
L["Copy this mail"] = "复制这封信"
L["Delete"] = "删除"
L["Disable Blizzard's auto-completion popup menu"] = "关闭暴雪的自动完成弹出菜单"
L["DoNotWant"] = "不想要"
L["Enable Alt-Click to send mail"] = "允许 Alt+点击发送邮件"
L["Exclude randoms you interacted with"] = "防止你随意地受到影响"
L["Express"] = "快件"
L["Friends"] = "好友"
L["Guild"] = "公会"
L["Help"] = "帮助"
L["In Progress"] = "处理中"
L["Keep free space"] = "保留背包空间"
L["Mouse click short cuts for mail."] = "鼠标快捷方式。"
L["Name auto-completion options"] = "姓名自动完成选项"
L["New Profile"] = "新配置文件"
L["New Profile Name:"] = "新配置文件名称："
L["Non-AH related mail"] = "非拍卖相关邮件"
L["Not all messages are shown, refreshing mailbox soon to continue Open All..."] = "尚有邮件未能显示，请重整收件匣后继续开启…"
L["Not taking more items as there are now only %d regular bagslots free."] = "无法拿取更多物品，目前仅有%d个背包位置。"
L["Open"] = "打开"
L["Open All"] = "打开所有"
L["Open all Auction cancelled mail"] = "打开所有取消拍卖的邮件"
L["Open all Auction expired mail"] = "打开所有拍卖过期的邮件"
L["Open all Auction successful mail"] = "打开所有拍卖成功的邮件"
L["Open all Auction won mail"] = "打开所有赢得拍卖的邮件"
L["Open all mail with attachments"] = "打开所有带有附件的邮件"
L["Open all Outbid on mail"] = "打开所有超过出价的邮件"
L["Open mail from the Postmaster"] = "打开来自邮政长的邮件"
L["OpenAll"] = "打开所有"
L["Opening Speed"] = "收信速度"
L["Other options"] = "其他选项"
L["Part %d"] = "第%d组"
L["Please post bugs or suggestions at the wowace forums thread at |cFF00FFFFhttp://forums.wowace.com/showthread.php?t=3909|r. When posting bugs, indicate your locale and Postal's version number v%s."] = "请到 WowAce 的论坛|cFF00FFFFhttp://forums.wowace.com/showthread.php?t=3909|r 报告 Bug 或者提交建议。报告 Bug 时请说明 Postal 的版本 v%s。"
L["Prints the amount of money collected during a mail session."] = "显示在一次邮件操作中所收到的金币。"
L["Processing Message"] = "正在处理邮件"
L["Profile"] = "配置文件"
L["Rake"] = "收款显示"
L["Recently Mailed"] = "最近邮寄"
L["Refreshing mailbox..."] = "重新整理收件匣…"
L["Remove Contact"] = "删除联系人"
L["Reset Profile"] = "重置配置文件"
L["Return"] = "退信"
L["Select"] = "选择"
L["Set subject field to value of coins sent if subject is blank."] = "在主题为空时将主题自动填充为金币数量。"
L["Shows a clickable visual icon as to whether a mail will be returned or deleted on expiry."] = "显示一个可点击的图标以确定邮件将被退回或是到期删除。"
L["Skipping"] = "忽略"
L["Some Messages May Have Been Skipped."] = "部分邮件可能被忽略。"
L["Thaumaturge Vashreen"] = "魔术师瓦西里恩"
L["The Postmaster"] = "邮政长"
L["There are %i more messages not currently shown."] = "还有%i或更多的邮件没有显示。"
L["There are %i more messages not currently shown. More should become available in %i seconds."] = "当前还有%i条信息没有显示。将在%i秒内显示。"
L["TradeBlock"] = "阻止交易"
L["Use Mr.Plow after opening"] = "打开邮件后使用 Mr.Plow 插件进行背包整理"
L["Use Postal's auto-complete"] = "使用 Postal 的自动完成"
L["Verbose mode"] = "消息模式"
L["Wire"] = "填充标题"

    return
end

L = AL3:NewLocale("Postal", "zhTW")
if L then
L["|cffeda55fAlt-Click|r to send this item to %s."] = "|cffeda55fAlt-點擊: |r將物品寄給%s。"
L["|cffeda55fControl-Click|r to attach similar items."] = "|cffeda55fCtrl-點擊|r附加類似物品。"
L["|cffeda55fCtrl-Click|r to return it to sender."] = "|cffeda55fCtrl-點擊: |r返回信件。"
L["|cffeda55fShift-Click|r to take the contents."] = "|cffeda55fShift-點擊: |r收取信件。"
L[ [=[|cFFFFCC00*|r Selected mail will be batch opened or returned to sender by clicking Open or Return.
|cFFFFCC00*|r You can Shift-Click 2 checkboxes to mass select every mail between the 2 checkboxes.
|cFFFFCC00*|r You can Ctrl-Click a checkbox to mass select or unselect every mail from that sender.
|cFFFFCC00*|r Select will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r Select will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r |cFFFFCC00*|r 選定的信件將批次開啟或通過點擊打開或返回來退還給發件人。
|cFFFFCC00*|r 您可以Shift-點擊兩個複選框來選擇兩個複選框之間的所有信件。
|cFFFFCC00*|r 您可以按Ctrl-點擊一個複選框來選定或取消選定一切來自該發件人的信件。
|cFFFFCC00*|r 選擇 永遠不會刪除任何信件(當所有附在信件的物品和金錢被提取後，遊戲會自動刪除郵箱裡沒有文字的信件) 。
|cFFFFCC00*|r 選擇 將跳過CoD信件和暴雪的信件。
|cFFFFCC00*|r 關閉 消息模式 選項來停止當開啟信件時在聊天框的洗頻。]=]
L[ [=[|cFFFFCC00*|r Shift-Click to take item/money from mail.
|cFFFFCC00*|r Ctrl-Click to return mail.
|cFFFFCC00*|r Alt-Click to move an item from your inventory to the current outgoing mail (same as right click in default UI).]=] ] = [=[|cFFFFCC00*|r Shift-點擊將從郵件拿取物品/金錢。
|cFFFFCC00*|r 按Ctrl -點擊將退還信件。
|cFFFFCC00*|r 按Alt-點擊一件物品將從您的背包移到目前的外寄信件（等同UI預設的右鍵點擊 ） 。
|cFFFFCC00*|r 用滑鼠滾輪滾動收件匣。]=]
L[ [=[|cFFFFCC00*|r Simple filters are available for various mail types.
|cFFFFCC00*|r Shift-Click the Open All button to override the filters and take ALL mail.
|cFFFFCC00*|r OpenAll will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r OpenAll will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r 簡單的篩選器可用於篩選各種信件類型。
|cFFFFCC00*|r Shift-點擊 收取全部 按鈕將覆蓋所有的篩選器，並提取所有的信件。
|cFFFFCC00*|r 收取全部 永遠不會刪除任何信件(當所有附在信件的物品和金錢被提取後，遊戲會自動刪除郵箱裡沒有文字的信件) 。
|cFFFFCC00*|r 收取全部 將跳過CoD信件和暴雪的信件。
|cFFFFCC00*|r 關閉 消息模式 選項來停止當開啟信件時在聊天框的洗頻。]=]
L[ [=[|cFFFFCC00*|r This module will list your contacts, friends, guild mates, alts and track the last 10 people you mailed.
|cFFFFCC00*|r It will also autocomplete all names in your BlackBook.]=] ] = [=[|cFFFFCC00*|r 此模組將您的聯絡人名單，朋友，公會隊友，分身，並追踪過去您曾郵寄的10人。
|cFFFFCC00*|r 它也將自動填寫已在您的黑名單內所有的名字。]=]
L["A button that collects all attachments and coins from mail."] = "一個收取全部附件及金錢的按鈕。"
L["Add check boxes to the inbox for multiple mail operations."] = "增加勾選框以供多重信件指令使用。"
L["Add Contact"] = "新增聯絡人"
L["Add multiple item mail tooltips"] = "新增多個物品的郵件提示框"
L["Adds a contact list next to the To: field."] = "在收件人輸入框旁邊添加一個聯絡列表。"
L["AH-related mail"] = "拍賣相關信件"
L["All Alts"] = "所有Alts"
L["Allows you to copy the contents of a mail."] = "允許你複製信的內容物。"
L["Alts"] = "分身"
L["Auto-Attach similar items on Control-Click"] = "Ctrl+點擊時自動附加相似物品"
L["Autofill last person mailed"] = "自動填寫最後曾郵寄的人名"
L["Auto-Send on Alt-Click"] = "Alt-點擊 自動發送"
L["BlackBook"] = "聯絡人名冊"
L["Block incoming trade requests while in a mail session."] = "在處理信件期間拒絕交易要求。"
L["CarbonCopy"] = "複本"
L["Chat Output"] = "聊天內容 輸出"
L["Choose"] = "選取"
L["Clear list"] = "清空列表"
L["Collected"] = "已領取"
L["Contacts"] = "聯絡人"
L["Copy From"] = "複製自"
L["Copy this mail"] = "複製這封信"
L["Delete"] = "刪除"
L["Disable Blizzard's auto-completion popup menu"] = "停用內建彈出自動完成的選單"
L["DoNotWant"] = "不想要"
L["Enable Alt-Click to send mail"] = "開啟Alt-點擊 發送信件"
L["Exclude randoms you interacted with"] = "防止你隨意地受到影響"
L["Express"] = "快速收發"
L["Friends"] = "好友"
L["Guild"] = "公會"
L["Help"] = "幫助"
L["In Progress"] = "正在處理"
L["Keep free space"] = "保持背包空位"
L["Mouse click short cuts for mail."] = "點擊快速收發信件。"
L["Name auto-completion options"] = "名字自動完成選項"
L["New Profile"] = "新設定檔"
L["New Profile Name:"] = "新設定檔名稱:"
L["Non-AH related mail"] = "非拍賣相關信件"
L["Not all messages are shown, refreshing mailbox soon to continue Open All..."] = "尚有郵件未能顯示，請重整收件匣後繼續開啟..."
L["Not taking more items as there are now only %d regular bagslots free."] = "無法拾取更多物品，因目前只有%d個背包空位。"
L["Open"] = "開啟"
L["Open All"] = "收取全部"
L["Open all Auction cancelled mail"] = "打開所有取消拍賣的信件"
L["Open all Auction expired mail"] = "打開所有拍賣過期的信件"
L["Open all Auction successful mail"] = "打開所有拍賣成功的信件"
L["Open all Auction won mail"] = "打開所有赢得拍賣的信件"
L["Open all mail with attachments"] = "打開所有帶有附件的信件"
L["Open all Outbid on mail"] = "打開所有超過出價的信件"
L["Open mail from the Postmaster"] = "從Postmaster開啟郵件"
L["OpenAll"] = "收取全部"
L["Opening Speed"] = "收取速度"
L["Other options"] = "其他選項"
L["Part %d"] = "分組%d"
L["Please post bugs or suggestions at the wowace forums thread at |cFF00FFFFhttp://forums.wowace.com/showthread.php?t=3909|r. When posting bugs, indicate your locale and Postal's version number v%s."] = "如要回報錯誤或建議請往wowace論壇|cFF00FFFFhttp://forums.wowace.com/showthread.php?t=3909|r. 發帖時，說明你的語系和Postal的版本編號 v%s."
L["Prints the amount of money collected during a mail session."] = "顯示這次收取的金錢。"
L["Processing Message"] = "正在處理訊息"
L["Profile"] = "設定檔"
L["Rake"] = "報告"
L["Recently Mailed"] = "最近寄出的郵件"
L["Refreshing mailbox..."] = "重新整理收件匣..."
L["Remove Contact"] = "移除聯絡人"
L["Reset Profile"] = "重置設定檔"
L["Return"] = "返回"
L["Select"] = "選擇"
L["Set subject field to value of coins sent if subject is blank."] = "在「主題:」欄位自動填寫寄件金額。"
L["Shows a clickable visual icon as to whether a mail will be returned or deleted on expiry."] = "視覺顯示點擊圖示是否郵件將被退回或刪除期滿。"
L["Skipping"] = "略過"
L["Some Messages May Have Been Skipped."] = "部份訊息可能會被略過。"
L["Thaumaturge Vashreen"] = "魔术师瓦西里恩"
L["The Postmaster"] = "邮政长"
L["There are %i more messages not currently shown."] = "有%i更多訊息沒有在目前顯示。"
L["There are %i more messages not currently shown. More should become available in %i seconds."] = "有%i更多訊息沒有在目前顯示。在%i秒內將會顯示更多。"
L["TradeBlock"] = "拒絕交易"
L["Use Mr.Plow after opening"] = "在開啟郵件之後使用Mr.Plow 整理背包"
L["Use Postal's auto-complete"] = "使用Postal的自動完成"
L["Verbose mode"] = "消息模式"
L["Wire"] = "自動填寫金額"

    return
end

L = AL3:NewLocale("Postal", "ptBR")
if L then
L["|cffeda55fAlt-Click|r to send this item to %s."] = "|cffeda55fAlt-Click|r para enviar este item para %s."
L["|cffeda55fControl-Click|r to attach similar items."] = "|cffeda55fCtrl-Clique|r para anexar itens semelhantes"
L["|cffeda55fCtrl-Click|r to return it to sender."] = "|cffeda55fCtrl-Click|r para retorná-lo ao remetente."
L["|cffeda55fShift-Click|r to take the contents."] = "|cffeda55fShift-Click|r para pegar o conteúdo."
L[ [=[|cFFFFCC00*|r Selected mail will be batch opened or returned to sender by clicking Open or Return.
|cFFFFCC00*|r You can Shift-Click 2 checkboxes to mass select every mail between the 2 checkboxes.
|cFFFFCC00*|r You can Ctrl-Click a checkbox to mass select or unselect every mail from that sender.
|cFFFFCC00*|r Select will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r Select will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r Cartas selecionadas serão abertas ou retornadas ao remetente em lote clicando em Abrir ou Retornar.
|cFFFFCC00*|r Você pode usar Shift-Clique em duas caixas de seleção para marcar em massa cada carta entre as duas caixas de seleção.
|cFFFFCC00*|r Você pode usar Ctrl-Clique numa caixa de seleção para marcar ou desmarcar em massa todos as cartas daquele remetente.
|cFFFFCC00*|r Selecionar nunca irá excluir nenhuma carta (cartas sem texto são auto-excluídas pelo jogo quando todos os anexos e moedas são obtidos).
|cFFFFCC00*|r Selecionar irá pular cartas a cobrar e cartas da Blizzard.
|cFFFFCC00*|r Desative a opção Verbal para parar o spam no chat enquanto estiver abrindo cartas.]=]
L[ [=[|cFFFFCC00*|r Shift-Click to take item/money from mail.
|cFFFFCC00*|r Ctrl-Click to return mail.
|cFFFFCC00*|r Alt-Click to move an item from your inventory to the current outgoing mail (same as right click in default UI).]=] ] = [=[|cFFFFCC00*|r Shift-Clique para pegar o item/dinheiro da carta.
|cFFFFCC00*|r Ctrl-Clique para retornar a carta.
|cFFFFCC00*|r Alt-Clique para mover um item do seu inventário para a carta atual (mesma coisa de clique direito na IU padrão).
|cFFFFCC00*|r Mousewheel para rolar a caixa de entrada.]=]
L[ [=[|cFFFFCC00*|r Simple filters are available for various mail types.
|cFFFFCC00*|r Shift-Click the Open All button to override the filters and take ALL mail.
|cFFFFCC00*|r OpenAll will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r OpenAll will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r Filtros simples estão disponíveis para vários tipos de cartas.
|cFFFFCC00*|r Shift-Clique no botão Abrir Tudo para ignorar os filtros e pegar TODAS as cartas.
|cFFFFCC00*|r AbrirTudo nunca irá excluir nenhuma carta (cartas sem texto são auto-excluídas pelo jogo quando todos os anexos e moedas são obtidos).
|cFFFFCC00*|r AbrirTudo irá pular cartas a cobrar e cartas da Blizzard.
|cFFFFCC00*|r Desative a opção Verbal para parar o spam no chat enquanto estiver abrindo cartas.]=]
L[ [=[|cFFFFCC00*|r This module will list your contacts, friends, guild mates, alts and track the last 10 people you mailed.
|cFFFFCC00*|r It will also autocomplete all names in your BlackBook.]=] ] = [=[|cFFFFCC00*|r Esse módulo irá listar seus contatos, amigos, companheiros de guilda, alts e registrar as ultimas 10 pessoas que você mandou cartas.
|cFFFFCC00*|r Também irá auto-completar todos os nomes no seu LivroNegro.]=]
L["A button that collects all attachments and coins from mail."] = "Um botão que coleta todos os anexos e moedas da carta."
L["Add check boxes to the inbox for multiple mail operations."] = "Adicionar caixas de seleção na caixa de entrada para operações de múltiplas cartas."
L["Add Contact"] = "Adicionar Contato"
L["Add multiple item mail tooltips"] = "Adicionar múltiplas dicas de interface de itens de correio"
L["Adds a contact list next to the To: field."] = "Adiciona uma lista de contato próximo ao campo de A:"
L["AH-related mail"] = "Carta relacionada à CL"
L["All Alts"] = "Todos os alts"
L["Allows you to copy the contents of a mail."] = "Permite a você copiar o conteúdo de uma carta."
L["Alts"] = "Alts"
L["Auto-Attach similar items on Control-Click"] = "Anexar itens semelhantes com Ctrl-Clique"
L["Autofill last person mailed"] = "Auto-preencher última pessoa enviada"
L["Auto-Send on Alt-Click"] = "Auto-enviar com Alt-Clique"
L["BlackBook"] = "LivroNegro"
L["Block incoming trade requests while in a mail session."] = "Bloquear pedidos de negociar quando estiver numa sessão de correio."
L["CarbonCopy"] = "CópiaCarbono"
L["Chat Output"] = "Mensagens no Chat"
L["Choose"] = "Escolher"
L["Clear list"] = "Limpar lista"
L["Collected"] = "Coletado(s)"
L["Contacts"] = "Contatos"
L["Copy From"] = "Copiar de"
L["Copy this mail"] = "Copiar essa carta"
L["Delete"] = "Excluir"
L["Disable Blizzard's auto-completion popup menu"] = "Desativar menu popup de auto-completar da Blizzard."
L["DoNotWant"] = "NãoQuerer"
L["Enable Alt-Click to send mail"] = "Ativar Alt-Clique para enviar carta"
L["Exclude randoms you interacted with"] = "Excluir aleatórios com quem você interagiu"
L["Express"] = "Expresso"
L["Friends"] = "Amigos"
L["Guild"] = "Guilda"
L["Help"] = "Ajuda"
L["In Progress"] = "Em Progresso"
L["Keep free space"] = "Manter espaço livre"
L["Mouse click short cuts for mail."] = "Atalhos de clique do mouse para cartas."
L["Name auto-completion options"] = "Nomear opções de auto-completar"
L["New Profile"] = "Novo Perfil"
L["New Profile Name:"] = "Nome do Novo Perfil:"
L["Non-AH related mail"] = "Carta não relacionada à CL"
L["Not all messages are shown, refreshing mailbox soon to continue Open All..."] = "Nem todas as mensagens estão sendo exibidas, atualizando caixa de correio em breve para continuar a Abrir Tudo..."
L["Not taking more items as there are now only %d regular bagslots free."] = "Não pegando mais itens pois há agora apenas %d espaços regulares da mochila livres."
L["Open"] = "Abrir"
L["Open All"] = "Abrir Todos"
L["Open all Auction cancelled mail"] = "Abrir todas as cartas de Leilões cancelados"
L["Open all Auction expired mail"] = "Abrir todas as cartas de Leilões expirados"
L["Open all Auction successful mail"] = "Abrir todas as cartas de Leilões bem-sucedidos"
L["Open all Auction won mail"] = "Abrir todas as cartas de Leilões ganhos"
L["Open all mail with attachments"] = "Abrir todas as cartas com anexos"
L["Open all Outbid on mail"] = "Abrir todas as cartas de Lances ultrapassados"
L["Open mail from the Postmaster"] = "Abrir todas as cartas do Chefe do Correio"
L["OpenAll"] = "AbrirTudo"
L["Opening Speed"] = "Velocidade de Abertura"
L["Other options"] = "Outras opções"
L["Part %d"] = "Parte %d"
L["Please post bugs or suggestions at the wowace forums thread at |cFF00FFFFhttp://forums.wowace.com/showthread.php?t=3909|r. When posting bugs, indicate your locale and Postal's version number v%s."] = "Por favor poste bugs ou sugestões nos fórums do wowace em |cFF00FFFFhttp://forums.wowace.com/showthread.php?t=3909|r. Quando estiver postando bugs, indique seu locale e a versão do Postal v%s."
L["Prints the amount of money collected during a mail session."] = "Mostra a quantidade de dinheiro coletado durante uma sessão de cartas."
L["Processing Message"] = "Processando Mensagem"
L["Profile"] = "Perfil"
L["Rake"] = "Resumo"
L["Recently Mailed"] = "Enviado Recentemente"
L["Refreshing mailbox..."] = "atualizando caixa de correio..."
L["Remove Contact"] = "Remover Contato"
L["Reset Profile"] = "Resetar Perfil"
L["Return"] = "Retornar"
L["Select"] = "Selecionar"
L["Set subject field to value of coins sent if subject is blank."] = "Definir campo de assunto para o valor de moedas enviado se o assunto for branco."
L["Shows a clickable visual icon as to whether a mail will be returned or deleted on expiry."] = "Mostra um ícone visual clicável para saber se uma carta será retornada ou excluída ao expirar."
L["Skipping"] = "Pulando"
L["Some Messages May Have Been Skipped."] = "Algumas Mensagens Podem Ter Sido Puladas."
L["Thaumaturge Vashreen"] = "Taumaturgo Vashreen"
L["The Postmaster"] = "O Chefe do Correio"
L["There are %i more messages not currently shown."] = "Ainda tem mais %i mensagens não mostradas atualmente."
L["There are %i more messages not currently shown. More should become available in %i seconds."] = "Ainda tem mais %i mensagens não mostradas atualmente. Mais devem ficar disponíveis em %i segundos."
L["TradeBlock"] = "BloquearNegociações"
L["Use Mr.Plow after opening"] = "Usar Mr.Plow depois de abrir"
L["Use Postal's auto-complete"] = "Usar o auto-completar do Postal"
L["Verbose mode"] = "Modo verbal"
L["Wire"] = "Telegrama"

    return
end

L = AL3:NewLocale("Postal", "itIT")
if L then
L["|cffeda55fAlt-Click|r to send this item to %s."] = "|cffeda55fAlt-Click|r per spedire questo oggetto a %s."
L["|cffeda55fControl-Click|r to attach similar items."] = "Control-Click per allegare oggetti simili"
L["|cffeda55fCtrl-Click|r to return it to sender."] = "|cffeda55fCtrl-Click|r per rimandarla al mittente."
L["|cffeda55fShift-Click|r to take the contents."] = "|cffeda55fShift-Click|r per prendere il contenuto."
L[ [=[|cFFFFCC00*|r Selected mail will be batch opened or returned to sender by clicking Open or Return.
|cFFFFCC00*|r You can Shift-Click 2 checkboxes to mass select every mail between the 2 checkboxes.
|cFFFFCC00*|r You can Ctrl-Click a checkbox to mass select or unselect every mail from that sender.
|cFFFFCC00*|r Select will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r Select will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r Le lettere selezionate saranno aperte o rimandate al mittente cliccando su Apri o Rimanda
|cFFFFCC00*|r Con Shift-Click puoi selezionare due spunti per selezionare tutte le lettere tra i due spunti.
|cFFFFCC00*|r Con Ctrl-Click su uno spunto puoi selezionare o deselezionare tutte le lettere di quel mittente.
|cFFFFCC00*|r Seleziona non cancellerà mai nessuna lettera (le lettere senza testo saranno cancellate automaticamente dal gioco quando sono stati presi tutti gli allegati e i soldi).
|cFFFFCC00*|r Seleziona salterà tutte le lettere P.C. e le lettere da Blizzard.
|cFFFFCC00*|r Disabilita l'opzione testuale per fermare lo spam durante l'apertura delle lettere]=]
L[ [=[|cFFFFCC00*|r Shift-Click to take item/money from mail.
|cFFFFCC00*|r Ctrl-Click to return mail.
|cFFFFCC00*|r Alt-Click to move an item from your inventory to the current outgoing mail (same as right click in default UI).]=] ] = [=[|cFFFFCC00*|r Shift-Click per prendere gli oggetti o le monete dalla posta.
|cFFFFCC00*|r Ctrl-Click per rimandare indietro la posta.
|cFFFFCC00*|r Alt-Click per muovere un oggetto dall'inventario alla lettera in uscita attuale (come il tasto destro del mouse nell' UI di default).]=]
L[ [=[|cFFFFCC00*|r Simple filters are available for various mail types.
|cFFFFCC00*|r Shift-Click the Open All button to override the filters and take ALL mail.
|cFFFFCC00*|r OpenAll will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r OpenAll will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r Semplici filtri sono disponibili per vari tipi di lettere.
|cFFFFCC00*|r Shift-Click sul bottone Apri Tutto per non tener conto dei filtri e raccogliere TUTTE le lettere.
|cFFFFCC00*|r Apri Tutto non cancellerà mai nessuna lettera (le lettere senza testo saranno cancellate automaticamente dal gioco quando sono stati presi tutti gli allegati e i soldi).
|cFFFFCC00*|r Apri Tutto salterà tutte le lettere P.C. e le lettere da Blizzard.
|cFFFFCC00*|r Disabilita l'opzione Testuale per bloccare lo spam in chat durante l'apertura delle lettere]=]
L[ [=[|cFFFFCC00*|r This module will list your contacts, friends, guild mates, alts and track the last 10 people you mailed.
|cFFFFCC00*|r It will also autocomplete all names in your BlackBook.]=] ] = [=[|cFFFFCC00*|r Questo modulo elencherà i tuoi contatti, gli amici, i compagni di gilda, gli alts e le ultime 10 persone a cui avrai scritto.
|cFFFFCC00*|r Completerà anche automaticamente tutti i nomi presenti nella Lista.]=]
L["A button that collects all attachments and coins from mail."] = "Un pulsante che raccoglie tutti gli allegati e le monete dalle lettere."
L["Add check boxes to the inbox for multiple mail operations."] = "Aggiunge spunti per la posta in arrivo per operazioni di posta multipla."
L["Add Contact"] = "Aggiungi Contatto"
L["Add multiple item mail tooltips"] = "Aggiunge più voci alle informazioni nella lettera"
L["Adds a contact list next to the To: field."] = "Aggiunge una lista dei contatti vicino al campo A:"
L["AH-related mail"] = "Lettera relativa alla Casa d'Aste"
L["All Alts"] = "Tutti gli Alt"
L["Allows you to copy the contents of a mail."] = "Ti permette di copiare il contenuto di una lettera"
L["Alts"] = "Alts"
L["Auto-Attach similar items on Control-Click"] = "Allega in automatico oggetti simili con Control-Click"
L["Autofill last person mailed"] = "Completa automaticamente con l'ultima persona a cui hai scritto"
L["Auto-Send on Alt-Click"] = "Auto invia con Alt-Click"
L["BlackBook"] = "Lista Nera"
L["Block incoming trade requests while in a mail session."] = "Blocca le richieste di commercio mentre si stanno leggendo le lettere."
L["CarbonCopy"] = "Copia Carbone"
L["Chat Output"] = "Resoconto Chat"
L["Choose"] = "Scegli"
L["Clear list"] = "Pulisci lista"
L["Collected"] = "Raccolti"
L["Contacts"] = "Contatti"
L["Copy From"] = "Copia da"
L["Copy this mail"] = "Copia questa lettera"
L["Delete"] = "Cancella"
L["Disable Blizzard's auto-completion popup menu"] = "Disabilita il menù popup di auto-completamento della Blizzard"
L["DoNotWant"] = "Non-Lo-Voglio"
L["Enable Alt-Click to send mail"] = "Abilita Alt-Click per mandare le lettere"
L["Exclude randoms you interacted with"] = "Esculdi persone a caso con cui hai interagito"
L["Express"] = "Veloce"
L["Friends"] = "Amici"
L["Guild"] = "Gilda"
L["Help"] = "Aiuto"
L["In Progress"] = "In elaborazione"
L["Keep free space"] = "Mantieni uno spazio libero"
L["Mouse click short cuts for mail."] = "Tasti di scelta rapida per le lettere."
L["Name auto-completion options"] = "Opzioni di auto-completamento del nome"
L["New Profile"] = "Nuovo Profilo"
L["New Profile Name:"] = "Nome del Nuovo Profilo:"
L["Non-AH related mail"] = "Lettere non relative alla Casa d'Aste"
L["Not all messages are shown, refreshing mailbox soon to continue Open All..."] = "Non tutti i messaggi sono stati visualizzati, ricarica la casella postale per continuare ad aprire tutto"
L["Not taking more items as there are now only %d regular bagslots free."] = "Non prendo altri oggetti se ci sono solo %d posti liberi nelle borse"
L["Open"] = "Apri"
L["Open All"] = "Apri Tutto"
L["Open all Auction cancelled mail"] = "Apri tutte le lettere annullate della casa d'aste"
L["Open all Auction expired mail"] = "Apri tutte le lettere scadute della casa d'aste"
L["Open all Auction successful mail"] = "Apri tutte le lettere di successo della casa d'aste"
L["Open all Auction won mail"] = "Apri tutte le lettere di vincita della casa d'aste"
L["Open all mail with attachments"] = "Apri tutte le lettere con allegati"
L["Open all Outbid on mail"] = "Apri tutte le lettere di offerta superata"
L["Open mail from the Postmaster"] = "Apri tutte le lettere dal Postino"
L["OpenAll"] = "Apri-tutto"
L["Opening Speed"] = "Velocità d'apertura"
L["Other options"] = "Altre opzioni"
L["Part %d"] = "Parte %d"
L["Please post bugs or suggestions at the wowace forums thread at |cFF00FFFFhttp://forums.wowace.com/showthread.php?t=3909|r. When posting bugs, indicate your locale and Postal's version number v%s."] = "Per favore riporta bug o suggerimenti al thread del forum wowace |cFF00FFFFhttp://forums.wowace.com/showthread.php?t=3909|r. Quando riporti un bug, indica la localizzazione e la versione v%s di Postal."
L["Prints the amount of money collected during a mail session."] = "Scrivi l'ammontare di monete raccolte durante una sessione di posta"
L["Processing Message"] = "Messaggio in elaborazione"
L["Profile"] = "Profilo"
L["Rake"] = "Somma"
L["Recently Mailed"] = "Spedite Recentemente"
L["Refreshing mailbox..."] = "Ricaricamento casella postale"
L["Remove Contact"] = "Rimuovi Contatto"
L["Reset Profile"] = "Resetta il profilo"
L["Return"] = "Rimanda"
L["Select"] = "Seleziona"
L["Set subject field to value of coins sent if subject is blank."] = "Indica l'ammontare di monete mandate nel campo del soggetto se è lasciato bianco"
L["Shows a clickable visual icon as to whether a mail will be returned or deleted on expiry."] = "Mostra un'icona visiva cliccabile se una lettera verrà restituita o cancellata alla scadenza."
L["Skipping"] = "Saltare"
L["Some Messages May Have Been Skipped."] = "Alcuni messaggi potrebbero esser stati saltati."
L["Thaumaturge Vashreen"] = "Taumaturgo Vashreen"
L["The Postmaster"] = "Il Postino"
L["There are %i more messages not currently shown."] = "Ci sono più di %i messaggi non correntemente mostrati."
L["There are %i more messages not currently shown. More should become available in %i seconds."] = "Ci sono più di %i messaggi non correntemente mostrati. Altri saranno visibili in %i secondi."
L["TradeBlock"] = "Blocca Scambio"
L["Use Mr.Plow after opening"] = "Usa Mr.Plow dopo aver aperto"
L["Use Postal's auto-complete"] = "Usa l'auto-completamento di Postal"
L["Verbose mode"] = "Modalità Testuale"
L["Wire"] = "telegramma"

    return
end
