-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/addons/handynotes/localization/

local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes", "zhTW")
if not L then return end

L[ [=[
Alt+Right Click To Add a HandyNote]=] ] = [=[
Alt+右鍵點擊新增一個註記]=]
L["(No Title)"] = "(無標題)"
L["|cFF00FF00Hint: |cffeda55fCtrl+Shift+LeftDrag|cFF00FF00 to move a note"] = "|cFF00FF00提示：|cffeda55fCtrl+Shift+左键拖曳|cFF00FF00可移動一個註記"
L["Add Handy Note"] = "新增註記"
L["Add this location to TomTom waypoints"] = "新增這個位置到TomTom waypoints"
L["Configuration for each individual plugin database."] = "為每個個別的插件資料庫配置。"
L["Delete Handy Note"] = "刪除註記"
L["Description/Notes:"] = "使用說明/註記："
L["Edit Handy Note"] = "編輯註記"
L["Enable HandyNotes"] = "啟用HandyNotes"
L["Enable or disable HandyNotes"] = "啟用或者停用HandyNotes"
L["ERROR_CREATE_NOTE1"] = "當HandyNotes無法建立一個註記時是因為它無法獲得當前的位置。通常這是因為你所在的位置地區沒有地圖。"
L["HandyNotes"] = "HandyNotes"
L["Icon Alpha"] = "圖示透明度"
L["Icon Scale"] = "圖示大小"
L["Minimap Icon Alpha"] = "小地圖圖示透明度"
L["Minimap Icon Scale"] = "小地圖圖示大小"
L["Overall settings"] = "整體設定"
L["Overall settings that affect every database"] = "整體設定將影響每一個資料庫"
L["Plugin databases"] = "插件資料庫"
L["Plugins"] = "插件"
L["Portal"] = "傳送門"
L["Show on continent map"] = "在大陸地圖上顯示"
L["Show the following plugins on the map"] = "在地圖上顯示以下的插件"
L["Syntax:"] = "語法："
L["The alpha transparency of the icons"] = "圖示的透明程度"
L["The overall alpha transparency of the icons on the Minimap"] = "小地圖圖示的整體透明程度"
L["The overall alpha transparency of the icons on the World Map"] = "世界地圖圖示的整體透明程度"
L["The overall scale of the icons on the Minimap"] = "小地圖圖示的整體大小"
L["The overall scale of the icons on the World Map"] = "世界地圖圖示的整體大小"
L["The scale of the icons"] = "圖示的大小"
L["These settings control the look and feel of HandyNotes globally. The icon's scale and alpha here are multiplied with the plugin's scale and alpha."] = "這些設定控制HandyNotes整體的外觀及風格。這裡的圖示大小和透明度將乘上插件本身的大小和透明度。"
L["These settings control the look and feel of the HandyNotes icons."] = "這些設定控制HandyNotes圖示的外觀及風格。"
L["Title"] = "標題"
L["World Map Icon Alpha"] = "世界地圖圖示透明度"
L["World Map Icon Scale"] = "世界地圖圖示大小"

