-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/addons/handynotes/localization/

local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes", "zhCN")
if not L then return end

L[ [=[
Alt+Right Click To Add a HandyNote]=] ] = "Alt+右击添加随记"
L["(No Title)"] = "（无标题）"
L["|cFF00FF00Hint: |cffeda55fCtrl+Shift+LeftDrag|cFF00FF00 to move a note"] = "|cFF00FF00提示：|cffeda55fCtrl+Shift+左键拖拽|cFF00FF00可以移动一个随记"
L["Add Handy Note"] = "添加随记"
L["Add this location to TomTom waypoints"] = "在 TomTom 中添加此位置"
L["Configuration for each individual plugin database."] = "为每个插件数据库单独配置"
L["Delete Handy Note"] = "删除随记"
L["Description/Notes:"] = "描述/注释："
L["Edit Handy Note"] = "编辑随记"
L["Enable HandyNotes"] = "启用 HandyNotes"
L["Enable or disable HandyNotes"] = "启用或者禁用 HandyNotes"
L["ERROR_CREATE_NOTE1"] = "HandyNotes 不能创建注释，因为它无法获得您当前所在的位置。这通常是因为您所在的区域没有地图。"
L["HandyNotes"] = "HandyNotes"
L["Icon Alpha"] = "图标透明度"
L["Icon Scale"] = "图标缩放"
L["Minimap Icon Alpha"] = "小地图图标透明度"
L["Minimap Icon Scale"] = "小地图图标缩放"
L["Overall settings"] = "全局设置"
L["Overall settings that affect every database"] = "作用于所有数据库的全局设置"
L["Plugin databases"] = "插件数据库"
L["Plugins"] = "插件"
L["Portal"] = "传送门"
L["Show on continent map"] = "在大陆地图上显示"
L["Show the following plugins on the map"] = "在地图上显示下列插件"
L["Syntax:"] = "参数："
L["The alpha transparency of the icons"] = "图标的透明度"
L["The overall alpha transparency of the icons on the Minimap"] = "小地图上图标的全局透明度值"
L["The overall alpha transparency of the icons on the World Map"] = "世界地图上图标的全局透明度值"
L["The overall scale of the icons on the Minimap"] = "小地图上图标的全局缩放值"
L["The overall scale of the icons on the World Map"] = "世界地图上图标的全局缩放值"
L["The scale of the icons"] = "图标的缩放值"
L["These settings control the look and feel of HandyNotes globally. The icon's scale and alpha here are multiplied with the plugin's scale and alpha."] = "这些设置可以全局控制 HandyNotes 的外观及风格。这里的图标的缩放和透明度会乘以插件的缩放及透明度。"
L["These settings control the look and feel of the HandyNotes icons."] = "这些设置控制 HandyNotes 图标的外观及风格。"
L["Title"] = "标题"
L["World Map Icon Alpha"] = "世界地图图标透明度"
L["World Map Icon Scale"] = "世界地图图标缩放"

