-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/addons/handynotes-suramartelemancy/localization/

local myname, ns = ...

local L = LibStub("AceLocale-3.0"):NewLocale(myname, "zhCN")
if not L then return end

L["Astravar Harbor"] = "阿斯塔瓦港"
L["Evermoon Terrace"] = "永月平台"
L["Falanaar"] = "法兰纳尔"
L["Felsoul Hold"] = "邪魂壁垒"
L["Lunastre Estate"] = "月郡地产"
L["Moon Guard (entrance)"] = "护月壁垒 (入口)"
L["Moon Guard Stronghold"] = "护月壁垒"
L["Ruins of Elune'eth"] = "艾露尼丝废墟"
L["Sanctum of Order"] = "秩序大殿"
L["Sanctum of Order (entrance)"] = "秩序大殿 (入口)"
L["Tel'anor"] = "泰尔安诺"
L["Twilight Vineyards"] = "暮光酒庄"
L["Waning Crescent"] = "残月酒馆"
