-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/addons/handynotes-suramartelemancy/localization/

local myname, ns = ...

local L = LibStub("AceLocale-3.0"):NewLocale(myname, "zhTW")
if not L then return end

L["Astravar Harbor"] = "艾斯特瓦港"
L["Evermoon Terrace"] = "永月露臺"
L["Falanaar"] = "法拉納爾"
L["Felsoul Hold"] = "魔魂堡"
L["Lunastre Estate"] = "路納斯特莊園"
L["Moon Guard (entrance)"] = "月之守衛 (入口)"
L["Moon Guard Stronghold"] = "月之守衛要塞"
L["Ruins of Elune'eth"] = "伊露恩斯遺址"
L["Sanctum of Order"] = "秩序聖所"
L["Sanctum of Order (entrance)"] = "秩序聖所 (入口)"
L["Tel'anor"] = "泰爾亞諾"
L["Twilight Vineyards"] = "暮光葡萄園"
L["Waning Crescent"] = "弦月旅店"

