-- QuestAnnounce Locale File
-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://wow.curseforge.com/addons/quest-announce-2-0/localization/

local AL3 = LibStub("AceLocale-3.0")
local debug = false
--[===[@debug@
debug = true
--@end-debug@]===]

local L = AL3:NewLocale("QuestAnnounce", "enUS", true, debug)
if L then
L["【爱不易】"] = true
L["Accepted: "] = true
L["Quest Done: "] = true
L["Announce Every"] = true
L["Announce progression every x number of steps (0 will announce on quest objective completion only)"] = true
L["Are you sure you want to announce to this channel?"] = true
L["Chat Frame"] = true
L["Completed: "] = true
L["Debug"] = true
L["Enable"] = true
L["Enable/Disable QuestAnnounce"] = true
L["Enable/Disable QuestAnnounce Debug Mode"] = true
L["Enable/Disable QuestAnnounce Sounds"] = true
L["Guild"] = true
L["Instance"] = true
L["Officer"] = true
L["Party"] = true
L["Progress: "] = true
L["QuestAnnounce Test Message"] = true
L["Raid Warning Frame"] = true
L["Say"] = true
L["Settings"] = true
L["Sound"] = true
L["UI Errors Frame"] = true
L["What channels do you want to make the announcements?"] = true
L["Where do you want to make the announcements?"] = true
L["Whisper"] = true
L["Whisper Who"] = true

if GetLocale() == "enUS" or GetLocale() == "enGB" then return end
end

local L = AL3:NewLocale("QuestAnnounce", "deDE")
if L then
L["Announce Every"] = "alle ankündigen / anzeigen "
L["Announce progression every x number of steps (0 will announce on quest objective completion only)"] = "kündige jede x Zahl der Schritte im Ablauf an (0 gibt nur den Questabschluss an.)"
L["Are you sure you want to announce to this channel?"] = "Sind Sie sicher, dass Sie den richtigen Channel gewählt haben?"
L["Chat Frame"] = "Chatfenster"
L["Completed: "] = "Abgeschlossen "
L["Debug"] = "Debug"
L["Enable"] = "Aktiviert"
L["Enable/Disable QuestAnnounce"] = [=[Aktiviert / Deaktiviert Quest Announce
]=]
L["Enable/Disable QuestAnnounce Debug Mode"] = "Schaltet den Debugmodus an oder aus"
L["Enable/Disable QuestAnnounce Sounds"] = "Sound An oder Aus schalten."
L["Guild"] = "Gilde"
L["Instance"] = "Instanz"
L["Officer"] = "Offizier"
L["Party"] = "Gruppe"
L["Progress: "] = "Fortschritt "
L["QuestAnnounce Test Message"] = "Quest Announcer Testnachricht"
L["Raid Warning Frame"] = "Schlachtzugswarnungfenster"
L["Say"] = "Sagen"
L["Settings"] = "Einstellungen"
L["Sound"] = "Sound"
L["UI Errors Frame"] = "UI-Fehler-Fenster"
L["What channels do you want to make the announcements?"] = "In welchem Channel wollen Sie die Ankündigungen machen?"
L["Where do you want to make the announcements?"] = "Wo wollen Sie die Durchsagen machen?"
L["Whisper"] = "Flüstern"
L["Whisper Who"] = "Flüstern zu"

return
end

local L = AL3:NewLocale("QuestAnnounce", "esES") or AL3:NewLocale("QuestAnnounce", "esMX")
if L then
-- L["Announce Every"] = "Announce Every"
-- L["Announce progression every x number of steps (0 will announce on quest objective completion only)"] = "Announce progression every x number of steps (0 will announce on quest objective completion only)"
-- L["Are you sure you want to announce to this channel?"] = "Are you sure you want to announce to this channel?"
-- L["Chat Frame"] = "Chat Frame"
L["Completed: "] = "terminado" -- Needs review
L["Debug"] = "depurar" -- Needs review
-- L["Enable"] = "Enable"
L["Enable/Disable QuestAnnounce"] = "Activar / Desactivar" -- Needs review
L["Enable/Disable QuestAnnounce Debug Mode"] = "Activar / Desactivar la depuración QuestAnnounce" -- Needs review
-- L["Enable/Disable QuestAnnounce Sounds"] = "Enable/Disable QuestAnnounce Sounds"
-- L["Guild"] = "Guild"
-- L["Instance"] = "Instance"
-- L["Officer"] = "Officer"
-- L["Party"] = "Party"
L["Progress: "] = "progreso" -- Needs review
-- L["QuestAnnounce Test Message"] = "QuestAnnounce Test Message"
-- L["Raid Warning Frame"] = "Raid Warning Frame"
-- L["Say"] = "Say"
-- L["Settings"] = "Settings"
-- L["Sound"] = "Sound"
-- L["UI Errors Frame"] = "UI Errors Frame"
-- L["What channels do you want to make the announcements?"] = "What channels do you want to make the announcements?"
-- L["Where do you want to make the announcements?"] = "Where do you want to make the announcements?"
-- L["Whisper"] = "Whisper"
-- L["Whisper Who"] = "Whisper Who"

return
end

local L = AL3:NewLocale("QuestAnnounce", "frFR")
if L then
-- L["Announce Every"] = "Announce Every"
-- L["Announce progression every x number of steps (0 will announce on quest objective completion only)"] = "Announce progression every x number of steps (0 will announce on quest objective completion only)"
-- L["Are you sure you want to announce to this channel?"] = "Are you sure you want to announce to this channel?"
-- L["Chat Frame"] = "Chat Frame"
-- L["Completed: "] = "Completed: "
-- L["Debug"] = "Debug"
-- L["Enable"] = "Enable"
-- L["Enable/Disable QuestAnnounce"] = "Enable/Disable QuestAnnounce"
-- L["Enable/Disable QuestAnnounce Debug Mode"] = "Enable/Disable QuestAnnounce Debug Mode"
-- L["Enable/Disable QuestAnnounce Sounds"] = "Enable/Disable QuestAnnounce Sounds"
-- L["Guild"] = "Guild"
-- L["Instance"] = "Instance"
-- L["Officer"] = "Officer"
-- L["Party"] = "Party"
-- L["Progress: "] = "Progress: "
-- L["QuestAnnounce Test Message"] = "QuestAnnounce Test Message"
-- L["Raid Warning Frame"] = "Raid Warning Frame"
-- L["Say"] = "Say"
-- L["Settings"] = "Settings"
-- L["Sound"] = "Sound"
-- L["UI Errors Frame"] = "UI Errors Frame"
-- L["What channels do you want to make the announcements?"] = "What channels do you want to make the announcements?"
-- L["Where do you want to make the announcements?"] = "Where do you want to make the announcements?"
-- L["Whisper"] = "Whisper"
-- L["Whisper Who"] = "Whisper Who"

return
end

local L = AL3:NewLocale("QuestAnnounce", "koKR")
if L then
L["Announce Every"] = "모두 방송"
L["Announce progression every x number of steps (0 will announce on quest objective completion only)"] = "방송의 단계별 진행마다 X 번호"
-- L["Are you sure you want to announce to this channel?"] = "Are you sure you want to announce to this channel?"
-- L["Chat Frame"] = "Chat Frame"
L["Completed: "] = "완료됨:"
L["Debug"] = "디버그"
L["Enable"] = "사용함"
L["Enable/Disable QuestAnnounce"] = "Quest Announce 사용함/사용안함"
L["Enable/Disable QuestAnnounce Debug Mode"] = "Quest Announce 디버그 모드 사용함/사용안함"
-- L["Enable/Disable QuestAnnounce Sounds"] = "Enable/Disable QuestAnnounce Sounds"
-- L["Guild"] = "Guild"
-- L["Instance"] = "Instance"
-- L["Officer"] = "Officer"
-- L["Party"] = "Party"
L["Progress: "] = "상태:"
-- L["QuestAnnounce Test Message"] = "QuestAnnounce Test Message"
-- L["Raid Warning Frame"] = "Raid Warning Frame"
-- L["Say"] = "Say"
L["Settings"] = "설정"
-- L["Sound"] = "Sound"
-- L["UI Errors Frame"] = "UI Errors Frame"
-- L["What channels do you want to make the announcements?"] = "What channels do you want to make the announcements?"
-- L["Where do you want to make the announcements?"] = "Where do you want to make the announcements?"
-- L["Whisper"] = "Whisper"
-- L["Whisper Who"] = "Whisper Who"

return
end

local L = AL3:NewLocale("QuestAnnounce", "ruRU")
if L then
-- L["Announce Every"] = "Announce Every"
-- L["Announce progression every x number of steps (0 will announce on quest objective completion only)"] = "Announce progression every x number of steps (0 will announce on quest objective completion only)"
-- L["Are you sure you want to announce to this channel?"] = "Are you sure you want to announce to this channel?"
-- L["Chat Frame"] = "Chat Frame"
-- L["Completed: "] = "Completed: "
-- L["Debug"] = "Debug"
-- L["Enable"] = "Enable"
L["Enable/Disable QuestAnnounce"] = "запустить работу questannounce"
-- L["Enable/Disable QuestAnnounce Debug Mode"] = "Enable/Disable QuestAnnounce Debug Mode"
-- L["Enable/Disable QuestAnnounce Sounds"] = "Enable/Disable QuestAnnounce Sounds"
-- L["Guild"] = "Guild"
-- L["Instance"] = "Instance"
-- L["Officer"] = "Officer"
-- L["Party"] = "Party"
-- L["Progress: "] = "Progress: "
-- L["QuestAnnounce Test Message"] = "QuestAnnounce Test Message"
-- L["Raid Warning Frame"] = "Raid Warning Frame"
-- L["Say"] = "Say"
-- L["Settings"] = "Settings"
-- L["Sound"] = "Sound"
-- L["UI Errors Frame"] = "UI Errors Frame"
-- L["What channels do you want to make the announcements?"] = "What channels do you want to make the announcements?"
-- L["Where do you want to make the announcements?"] = "Where do you want to make the announcements?"
-- L["Whisper"] = "Whisper"
-- L["Whisper Who"] = "Whisper Who"

return
end

local L = AL3:NewLocale("QuestAnnounce", "zhCN")
if L then
L["【爱不易】"] = "【爱不易】"
L["Accepted: "] = "接受任务："
L["Quest Done: "] = "任务完成："
L["Announce Every"] = "任务通报方式"
L["Announce progression every x number of steps (0 will announce on quest objective completion only)"] = "通报进度每第 x 步"
L["Are you sure you want to announce to this channel?"] = "你确定你要通报到这个频道吗？"
L["Chat Frame"] = "聊天框"
L["Completed: "] = ""
L["Debug"] = "调试"
L["Enable"] = "启用"
L["Enable/Disable QuestAnnounce"] = "启用/禁用 QuestAnnounce"
L["Enable/Disable QuestAnnounce Debug Mode"] = "调试模式切换"
L["Enable/Disable QuestAnnounce Sounds"] = "启用/禁用 QuestAnnounce 音效"
L["Guild"] = "公会"
L["Instance"] = "副本"
L["Officer"] = "官员"
L["Party"] = "小队"
L["Progress: "] = ""
L["QuestAnnounce Test Message"] = "QuestAnnounce测试消息"
L["Raid Warning Frame"] = "团队警告框"
L["Say"] = "说"
L["Settings"] = "设置"
L["Sound"] = "音效"
L["UI Errors Frame"] = "错误信息提示框"
L["What channels do you want to make the announcements?"] = "想要任务广播通报到哪个频道?"
L["Where do you want to make the announcements?"] = "您希望在哪里公告？"
L["Whisper"] = "密语"
L["Whisper Who"] = "密语给谁"

return
end

local L = AL3:NewLocale("QuestAnnounce", "zhTW")
if L then
L["【爱不易】"] = "【愛不易】"
L["Accepted: "] = "接受任務："
L["Quest Done: "] = "任務完成："
L["Announce Every"] = "任務進度廣播方式"
L["Announce progression every x number of steps (0 will announce on quest objective completion only)"] = "每x步通報進度一次(為0將只在任務結束時廣播)"
L["Are you sure you want to announce to this channel?"] = "你確定要發送到這個頻道嗎？"
L["Chat Frame"] = "聊天框"
L["Completed: "] = "已完成: "
L["Debug"] = "調試"
L["Enable"] = "啟用"
L["Enable/Disable QuestAnnounce"] = "啟用/禁用 Quest Announce"
L["Enable/Disable QuestAnnounce Debug Mode"] = "啟用/禁用 QuestAnnounce 調試模式"
L["Enable/Disable QuestAnnounce Sounds"] = "啓用/禁用 QuestAnnounce 聲效"
L["Guild"] = "公會"
L["Instance"] = "例"
L["Officer"] = "官員"
L["Party"] = "小隊"
L["Progress: "] = "任務進度: "
L["QuestAnnounce Test Message"] = "QuestAnnounce測試消息"
L["Raid Warning Frame"] = "團隊警告提示框"
L["Say"] = "說"
L["Settings"] = "配置"
L["Sound"] = "聲效"
L["UI Errors Frame"] = "插件錯誤提示框"
L["What channels do you want to make the announcements?"] = "你想要在哪個頻道發送任務廣播？"
L["Where do you want to make the announcements?"] = "你想要在什麽位置顯示任務廣播？"
L["Whisper"] = "密語"
L["Whisper Who"] = "密誰"

return
end

local L = AL3:NewLocale("QuestAnnounce", "ptBR")
if L then
-- L["Announce Every"] = "Announce Every"
-- L["Announce progression every x number of steps (0 will announce on quest objective completion only)"] = "Announce progression every x number of steps (0 will announce on quest objective completion only)"
-- L["Are you sure you want to announce to this channel?"] = "Are you sure you want to announce to this channel?"
-- L["Chat Frame"] = "Chat Frame"
-- L["Completed: "] = "Completed: "
-- L["Debug"] = "Debug"
-- L["Enable"] = "Enable"
-- L["Enable/Disable QuestAnnounce"] = "Enable/Disable QuestAnnounce"
-- L["Enable/Disable QuestAnnounce Debug Mode"] = "Enable/Disable QuestAnnounce Debug Mode"
-- L["Enable/Disable QuestAnnounce Sounds"] = "Enable/Disable QuestAnnounce Sounds"
-- L["Guild"] = "Guild"
-- L["Instance"] = "Instance"
-- L["Officer"] = "Officer"
-- L["Party"] = "Party"
-- L["Progress: "] = "Progress: "
-- L["QuestAnnounce Test Message"] = "QuestAnnounce Test Message"
-- L["Raid Warning Frame"] = "Raid Warning Frame"
-- L["Say"] = "Say"
-- L["Settings"] = "Settings"
-- L["Sound"] = "Sound"
-- L["UI Errors Frame"] = "UI Errors Frame"
-- L["What channels do you want to make the announcements?"] = "What channels do you want to make the announcements?"
-- L["Where do you want to make the announcements?"] = "Where do you want to make the announcements?"
-- L["Whisper"] = "Whisper"
-- L["Whisper Who"] = "Whisper Who"

return
end 
