FRIENDS_MENU_XP_LOADED = nil
FRIENDS_MENU_XP_CANNOT_TARGET = "FriendsMenuXP can't target <$name$>."

FMXP_BUTTON_ADD_FRIEND = "Add Friend"
FMXP_BUTTON_SEND_WHO = "Query Detail"
FMXP_BUTTON_ADD_GUILD = "Guild Invite"
FMXP_BUTTON_GET_NAME = "Get Name"
FMXP_BUTTON_ACHIEVEMENTS = "Achievements"
FMXP_BUTTON_ARMORY = "Armory"

FMXP_BUTTON_REPORT_PLAYER_FOR = REPORT_PLAYER_FOR.." "
