Auctionator.Shopping.Events = {
  ListSelected = "AUCTIONATOR_LIST_SELECTED",
  ListDeleted = "AUCTIONATOR_LIST_DELETED",
  ListCreated = "AUCTIONATOR_LIST_CREATED",
  ListRenamed = "AUCTIONATOR_LIST_RENAMED",

  ListItemAdded = "AUCTIONATOR_LIST_ITEM_ADDED",
  ListItemReplaced = "AUCTIONATOR_LIST_ITEM_REPLACED",
  ListItemSelected = "AUCTIONATOR_LIST_ITEM_SELECTED",
  ListItemDeleted = "AUCTIONATOR_LIST_ITEM_DELETED",
  ListOrderChanged = "AUCTIONATOR_LIST_ORDER_CHANGED",
  DeleteFromList = "AUCTIONATOR_DELETE_FROM_CURRENT_LIST",
  EditListItem = "AUCTIONATOR_EDIT_LIST_ITEM",
  CopyIntoList = "AUCTIONATOR_COPY_INTO_LIST",

  OneItemSearch = "AUCTIONATOR_ONE_ITEM_SEARCH",
  RecentSearchesUpdate = "AUCTIONATOR_RECENT_SEARCHES_UPDATE",

  SearchForTerms = "AUCTIONATOR_SEARCH_FOR_TERMS",
  CancelSearch = "AUCTIONATOR_CANCEL_SEARCH",

  ListSearchStarted = "AUCTIONATOR_LIST_SEARCH_STARTED",
  ListSearchIncrementalUpdate = "AUCTIONATOR_LIST_SEARCH_INCREMENTAL_UPDATE",
  ListSearchEnded = "AUCTIONATOR_LIST_SEARCH_ENDED",
  ListSearchRequested = "AUCTIONATOR_LIST_SEARCH_REQUESTED",
  ListAbortSearch = "AUCTIONATOR_LIST_ABORT_SEARCH",

  DialogOpened = "SHOPPING_DIALOG_OPENED",
  DialogClosed = "SHOPPING_DIALOG_CLOSED",

  ShowHistoricalPrices = "SHOPPING_SHOW_HISTORICAL_PRICES",
}
