if ( GetLocale() == "zhCN" ) then

	EUF_TEXT_OPTION_HEADER 			    = "EUF头像增强 参数设定";
	EUF_TEXT_OPTION_ENABLE 			    = "启用Enigma Unit Frames";
	EUF_TEXT_OPTION_PLAYERFRM                   = "显示头像边框";
	EUF_TEXT_OPTION_PLAYERHP                    = "显示玩家生命值";
	EUF_TEXT_OPTION_PLAYERMP                    = "显示玩家魔法值";
	EUF_TEXT_OPTION_PLAYERXP                    = "显示玩家经验值条";
	EUF_TEXT_OPTION_PLAYERXPAUTO                = "80级自动隐藏经验值条";
	EUF_TEXT_OPTION_PLAYERPOSITION              = "显示玩家坐标";
	EUF_TEXT_OPTION_PLAYERPOSITIONMANA          = "将坐标替换为生命值百分比";
	EUF_TEXT_OPTION_PLAYERPETHPMP               = "显示宠物的HP和MP"
	EUF_TEXT_OPTION_PLAYERPOSITIONAUTO          = "在副本里显示生命值百分比";
	EUF_TEXT_OPTION_PLAYERAUTOHEALTHCOLOR       = "生命值调节生命值条颜色";
	EUF_TEXT_OPTION_PLAYEREXTBAR                = "显示扩展边框";
	EUF_TEXT_OPTION_PLAYERCLASSICONBIG          = "显示玩家职业图标(大)";
	EUF_TEXT_OPTION_PLAYERCLASSICONSMALL        = "显示玩家职业图标(小)";
	EUF_TEXT_OPTION_PLAYER3DPORTRAIT            = "显示玩家3D头像";

	EUF_TEXT_OPTION_PARTYHP                     = "显示队友生命值";
	EUF_TEXT_OPTION_PARTYMP                     = "显示队友魔法值";
	EUF_TEXT_OPTION_PARTYAUTOHEALTHCOLOR        = "生命值调节生命值条颜色";
	EUF_TEXT_OPTION_PARTYLEVEL                  = "显示队友级别";
	EUF_TEXT_OPTION_PARTYCLASS                  = "显示队友职业";
	EUF_TEXT_OPTION_PARTYCLASSABRV              = "以缩写方式显示职业";
	EUF_TEXT_OPTION_PARTYCOLOR                  = "队友名字显示职业颜色";
	EUF_TEXT_OPTION_PARTYMANAFILTER             = "无魔法的职业不显示魔法值";
	EUF_TEXT_OPTION_PARTYCLASSICONBIG           = "显示队友职业图标(大)";
	EUF_TEXT_OPTION_PARTYCLASSICONSMALL         = "显示队友职业图标(小)";
	EUF_TEXT_OPTION_PARTY3DPORTRAIT             = "显示队友3D头像";
	EUF_TEXT_OPTION_PARTYHIDE                   = "隐藏队伍框架";

	EUF_TEXT_OPTION_TARGETHP                    = "显示目标生命值";
	EUF_TEXT_OPTION_TARGETMP                    = "显示目标魔法值";
	EUF_TEXT_OPTION_TARGETHPPERCENT             = "显示目标生命值百分比";
	EUF_TEXT_OPTION_TARGETMPPERCENT             = "显示目标魔法值百分比";
	EUF_TEXT_OPTION_TARGETAUTOHEALTHCOLOR       = "生命值调节生命值条颜色";
	EUF_TEXT_OPTION_TARGETPERCENTBOSS           = "目标为首领时显示百分比";
	EUF_TEXT_OPTION_TARGETOTWARNING             = "仇恨报警";
	EUF_TEXT_OPTION_TARGETINFO                  = "显示目标信息";
	EUF_TEXT_OPTION_TARGETINFOLEVEL             = "级别";
	EUF_TEXT_OPTION_TARGETINFORACE              = "种族";
	EUF_TEXT_OPTION_TARGETINFOCLASS             = "职业";
	EUF_TEXT_OPTION_TARGETINFOELITE             = "精英类型";
	EUF_TEXT_OPTION_TARGETINFOTARGET            = "显示目标的目标(简略)";
	EUF_TEXT_OPTION_TARGETINFOBROKENSHIELD      = "显示目标破甲值";
	EUF_TEXT_OPTION_TARGETTARGETHPMPBAR         = "显示目标的目标生命值/魔法值条";
	EUF_TEXT_OPTION_TARGETTARGETHPPERCENT       = "显示目标的目标生命值百分比";
	EUF_TEXT_OPTION_TARGETTARGETHPPERCENTCOLOR  = "自动调整生命值百分比颜色";
	EUF_TEXT_OPTION_TARGETCLASSICONBIG          = "显示目标职业图标(大)";
	EUF_TEXT_OPTION_TARGETCLASSICONSMALL        = "显示目标职业图标(小)";
	EUF_TEXT_OPTION_TARGETTARGETFRAME           = "显示目标的目标(标准)";
	EUF_TEXT_OPTION_TARGETTARGETTARGETFRAME     = "显示目标的目标的目标(标准)";
	EUF_TEXT_OPTION_MOVINGTARGETTARGETFRAME     = "移动目标的目标(标准)";
	EUF_TEXT_OPTION_TARGET3DPORTRAIT            = "显示目标3D头像";
	EUF_TEXT_OPTION_TARGETINDICATOR             = "目标头像显示战斗数值";

	EUF_TEXT_OPTION_NOTINSTALLED                = "参数设定模块未安装, 无法启动窗口设定模式.";
	EUF_TEXT_OPTION_HELP1                       = "请使用命令行模式设定, 用法如下:";
	EUF_TEXT_OPTION_HELP2                       = "/euf 选项 参数    (示例: /euf PlayerHp 0)";
	EUF_TEXT_OPTION_HELP3                       = "具体选项请参考readme.txt, 参数为0/1或on/off";
	EUF_TEXT_OPTION_SET                         = "已将参数 [%s] 设定为 %s";
	EUF_TEXT_OPTION_INVALIDPARAM                = "无效参数";
	EUF_TEXT_OPTION_NOTCOMPATIBLE               = "以前的参数设置与新版本的参数设置不兼容, 以前的参数设置将被清除, 请重新设定.";

	EUF_TEXT_OPTION_DISPLAYTYPE                 = "显示方式";
	EUF_TEXT_OPTION_NUM                         = "数字";
	EUF_TEXT_OPTION_PERCENT                     = "百分比";
	EUF_TEXT_OPTION_ELITE                       = "精英";
	EUF_TEXT_OPTION_RARE                        = "稀有";
	EUF_TEXT_OPTION_PLAYER                      = "玩家信息";
	EUF_TEXT_OPTION_PARTY                       = "队伍信息";
	EUF_TEXT_OPTION_TARGET                      = "目标信息";
	EUF_TEXT_OPTION_TARGETTARGET                = "目标的目标";
	EUF_TEXT_DEFAULTOPTIONS                     = "默认设置"
	EUF_TEXT_CONFIRM                            = "确定";

	EUF_TEXT_TARGET 			    = "目标 ";
	EUF_TEXT_BROKENSHIELD 			    = "破甲 ";
	EUF_TEXT_LEVELTAG 			    = "%s级";
	EUF_TEXT_ELITE 				    = "精英";
	EUF_TEXT_WORLDBOSS 			    = "世界精英";
	EUF_TEXT_RARE 				    = "稀有";
	EUF_TEXT_RAREELITE 			    = "稀有精英";
elseif (GetLocale() == "zhTW") then

	EUF_TEXT_OPTION_HEADER                      = "EUF頭像 參數設定";
	EUF_TEXT_OPTION_ENABLE                      = "啟用Enigma Unit Frames";
	EUF_TEXT_OPTION_PLAYERFRM                   = "顯示頭像邊框";
	EUF_TEXT_OPTION_PLAYERHP                    = "顯示玩家生命值";
	EUF_TEXT_OPTION_PLAYERMP                    = "顯示玩家魔法值";
	EUF_TEXT_OPTION_PLAYERXP                    = "顯示玩家經驗值條";
	EUF_TEXT_OPTION_PLAYERXPAUTO                = "80級自動隱藏經驗值條";
	EUF_TEXT_OPTION_PLAYERPOSITION              = "顯示玩家座標";
	EUF_TEXT_OPTION_PLAYERPOSITIONMANA          = "將座標替換為生命值百分比";
	EUF_TEXT_OPTION_PLAYERPETHPMP               = "顯示寵物的HP和MP"
	EUF_TEXT_OPTION_PLAYERPOSITIONAUTO          = "在副本裡顯示生命值百分比";
	EUF_TEXT_OPTION_PLAYERAUTOHEALTHCOLOR       = "依血量高低變化生命值條顏色";
	EUF_TEXT_OPTION_PLAYEREXTBAR                = "顯示擴展邊框";
	EUF_TEXT_OPTION_PLAYERCLASSICONBIG          = "顯示玩家職業圖標(大)";
	EUF_TEXT_OPTION_PLAYERCLASSICONSMALL        = "顯示玩家職業圖標(小)";
	EUF_TEXT_OPTION_PLAYER3DPORTRAIT            = "顯示玩家3D頭像";

	EUF_TEXT_OPTION_PARTYHP                     = "顯示隊友生命值";
	EUF_TEXT_OPTION_PARTYMP                     = "顯示隊友魔法值";
	EUF_TEXT_OPTION_PARTYAUTOHEALTHCOLOR        = "依血量高低變化生命值條顏色";
	EUF_TEXT_OPTION_PARTYLEVEL                  = "顯示隊友級別";
	EUF_TEXT_OPTION_PARTYCLASS                  = "顯示隊友職業";
	EUF_TEXT_OPTION_PARTYCLASSABRV              = "以縮寫方式顯示職業";
	EUF_TEXT_OPTION_PARTYCOLOR                  = "隊友名字顯示職業顏色";
	EUF_TEXT_OPTION_PARTYMANAFILTER             = "無魔法的職業不顯示魔法值";
	EUF_TEXT_OPTION_PARTYCLASSICONBIG           = "顯示隊友職業圖標(大)";
	EUF_TEXT_OPTION_PARTYCLASSICONSMALL         = "顯示隊友職業圖標(小)";
	EUF_TEXT_OPTION_PARTY3DPORTRAIT             = "顯示隊友3D頭像";
	EUF_TEXT_OPTION_PARTYHIDE                   = "隱藏隊伍框架";

	EUF_TEXT_OPTION_TARGETHP                    = "顯示目標生命值";
	EUF_TEXT_OPTION_TARGETMP                    = "顯示目標魔法值";
	EUF_TEXT_OPTION_TARGETHPPERCENT             = "顯示目標生命值百分比";
	EUF_TEXT_OPTION_TARGETMPPERCENT             = "顯示目標魔法值百分比";
	EUF_TEXT_OPTION_TARGETAUTOHEALTHCOLOR       = "依血量高低變化生命值條顏色";
	EUF_TEXT_OPTION_TARGETPERCENTBOSS           = "目標為首領時顯示百分比";
	EUF_TEXT_OPTION_TARGETOTWARNING             = "仇恨警報";
	EUF_TEXT_OPTION_TARGETINFO                  = "顯示目標訊息";
	EUF_TEXT_OPTION_TARGETINFOLEVEL             = "級別";
	EUF_TEXT_OPTION_TARGETINFORACE              = "種族";
	EUF_TEXT_OPTION_TARGETINFOCLASS             = "職業";
	EUF_TEXT_OPTION_TARGETINFOELITE             = "精英類型";
	EUF_TEXT_OPTION_TARGETINFOTARGET            = "顯示目標的目標(簡略)";
	EUF_TEXT_OPTION_TARGETINFOBROKENSHIELD      = "顯示目標破甲值";
	EUF_TEXT_OPTION_TARGETTARGETHPMPBAR         = "顯示目標的目標生命值/魔法值條";
	EUF_TEXT_OPTION_TARGETTARGETHPPERCENT       = "顯示目標的目標生命值百分比";
	EUF_TEXT_OPTION_TARGETTARGETHPPERCENTCOLOR  = "自動調整生命值百分比顏色";
	EUF_TEXT_OPTION_TARGETCLASSICONBIG          = "顯示目標職業圖標(大)";
	EUF_TEXT_OPTION_TARGETCLASSICONSMALL        = "顯示目標職業圖標(小)";
	EUF_TEXT_OPTION_TARGETTARGETFRAME           = "顯示目標的目標(標準)";
	EUF_TEXT_OPTION_TARGETTARGETTARGETFRAME     = "顯示目標的目標的目標(標準)";
	EUF_TEXT_OPTION_MOVINGTARGETTARGETFRAME     = "調整目標的目標頭像位置(標準)";
	EUF_TEXT_OPTION_TARGET3DPORTRAIT            = "顯示目標3D頭像";
	EUF_TEXT_OPTION_TARGETINDICATOR             = "目標頭像顯示戰鬥數值";

	EUF_TEXT_OPTION_NOTINSTALLED                = "參數設定模塊未安裝, 無法啟動視窗設定模式.";
	EUF_TEXT_OPTION_HELP1                       = "請使用命令行模式設定, 用法如下:";
	EUF_TEXT_OPTION_HELP2                       = "/euf 選項 參數    (示例: /euf PlayerHp 0)";
	EUF_TEXT_OPTION_HELP3                       = "具體選項請參考readme.txt, 參數為0/1或on/off";
	EUF_TEXT_OPTION_SET                         = "已將參數 [%s] 設定為 %s";
	EUF_TEXT_OPTION_INVALIDPARAM                = "無效參數";
	EUF_TEXT_OPTION_NOTCOMPATIBLE               = "以前的參數設置與新版本的參數設置不兼容, 以前的參數設置將被清除, 請重新設定.";

	EUF_TEXT_OPTION_DISPLAYTYPE                 = "顯示方式";
	EUF_TEXT_OPTION_NUM                         = "數字";
	EUF_TEXT_OPTION_PERCENT                     = "百分比";
	EUF_TEXT_OPTION_ELITE                       = "精英";
	EUF_TEXT_OPTION_RARE                        = "稀有";
	EUF_TEXT_OPTION_PLAYER                      = "玩家訊息";
	EUF_TEXT_OPTION_PARTY                       = "隊伍訊息";
	EUF_TEXT_OPTION_TARGET                      = "目標訊息";
	EUF_TEXT_OPTION_TARGETTARGET                = "目標的目標";
	EUF_TEXT_DEFAULTOPTIONS                     = "默認設置";
	EUF_TEXT_CONFIRM                            = "確定";

	EUF_TEXT_TARGET 			    = "目標 ";
	EUF_TEXT_BROKENSHIELD 			    = "破甲 ";
	EUF_TEXT_LEVELTAG 			    = "%s級";
	EUF_TEXT_ELITE 				    = "精英";
	EUF_TEXT_WORLDBOSS 			    = "世界精英";
	EUF_TEXT_RARE 				    = "稀有";
	EUF_TEXT_RAREELITE 			    = "稀有精英";
else
	EUF_TEXT_OPTION_HEADER 			    = "EUF头像增强 参数设定";
	EUF_TEXT_OPTION_ENABLE 			    = "启用Enigma Unit Frames";
	EUF_TEXT_OPTION_PLAYERFRM                   = "显示头像边框";
	EUF_TEXT_OPTION_PLAYERHP                    = "显示玩家生命值";
	EUF_TEXT_OPTION_PLAYERMP                    = "显示玩家魔法值";
	EUF_TEXT_OPTION_PLAYERXP                    = "显示玩家经验值条";
	EUF_TEXT_OPTION_PLAYERXPAUTO                = "80级自动隐藏经验值条";
	EUF_TEXT_OPTION_PLAYERPOSITION              = "显示玩家坐标";
	EUF_TEXT_OPTION_PLAYERPOSITIONMANA          = "将坐标替换为生命值百分比";
	EUF_TEXT_OPTION_PLAYERPETHPMP               = "显示宠物的HP和MP"
	EUF_TEXT_OPTION_PLAYERPOSITIONAUTO          = "在副本里显示生命值百分比";
	EUF_TEXT_OPTION_PLAYERAUTOHEALTHCOLOR       = "生命值调节生命值条颜色";
	EUF_TEXT_OPTION_PLAYEREXTBAR                = "显示扩展边框";
	EUF_TEXT_OPTION_PLAYERCLASSICONBIG          = "显示玩家职业图标(大)";
	EUF_TEXT_OPTION_PLAYERCLASSICONSMALL        = "显示玩家职业图标(小)";
	EUF_TEXT_OPTION_PLAYER3DPORTRAIT            = "显示玩家3D头像";

	EUF_TEXT_OPTION_PARTYHP                     = "显示队友生命值";
	EUF_TEXT_OPTION_PARTYMP                     = "显示队友魔法值";
	EUF_TEXT_OPTION_PARTYAUTOHEALTHCOLOR        = "生命值调节生命值条颜色";
	EUF_TEXT_OPTION_PARTYLEVEL                  = "显示队友级别";
	EUF_TEXT_OPTION_PARTYCLASS                  = "显示队友职业";
	EUF_TEXT_OPTION_PARTYCLASSABRV              = "以缩写方式显示职业";
	EUF_TEXT_OPTION_PARTYCOLOR                  = "队友名字显示职业颜色";
	EUF_TEXT_OPTION_PARTYMANAFILTER             = "无魔法的职业不显示魔法值";
	EUF_TEXT_OPTION_PARTYCLASSICONBIG           = "显示队友职业图标(大)";
	EUF_TEXT_OPTION_PARTYCLASSICONSMALL         = "显示队友职业图标(小)";
	EUF_TEXT_OPTION_PARTY3DPORTRAIT             = "显示队友3D头像";
	EUF_TEXT_OPTION_PARTYHIDE                   = "隐藏队伍框架";

	EUF_TEXT_OPTION_TARGETHP                    = "显示目标生命值";
	EUF_TEXT_OPTION_TARGETMP                    = "显示目标魔法值";
	EUF_TEXT_OPTION_TARGETHPPERCENT             = "显示目标生命值百分比";
	EUF_TEXT_OPTION_TARGETMPPERCENT             = "显示目标魔法值百分比";
	EUF_TEXT_OPTION_TARGETAUTOHEALTHCOLOR       = "生命值调节生命值条颜色";
	EUF_TEXT_OPTION_TARGETPERCENTBOSS           = "目标为首领时显示百分比";
	EUF_TEXT_OPTION_TARGETOTWARNING             = "仇恨报警";
	EUF_TEXT_OPTION_TARGETINFO                  = "显示目标信息";
	EUF_TEXT_OPTION_TARGETINFOLEVEL             = "级别";
	EUF_TEXT_OPTION_TARGETINFORACE              = "种族";
	EUF_TEXT_OPTION_TARGETINFOCLASS             = "职业";
	EUF_TEXT_OPTION_TARGETINFOELITE             = "精英类型";
	EUF_TEXT_OPTION_TARGETINFOTARGET            = "显示目标的目标(简略)";
	EUF_TEXT_OPTION_TARGETINFOBROKENSHIELD      = "显示目标破甲值";
	EUF_TEXT_OPTION_TARGETTARGETHPMPBAR         = "显示目标的目标生命值/魔法值条";
	EUF_TEXT_OPTION_TARGETTARGETHPPERCENT       = "显示目标的目标生命值百分比";
	EUF_TEXT_OPTION_TARGETTARGETHPPERCENTCOLOR  = "自动调整生命值百分比颜色";
	EUF_TEXT_OPTION_TARGETCLASSICONBIG          = "显示目标职业图标(大)";
	EUF_TEXT_OPTION_TARGETCLASSICONSMALL        = "显示目标职业图标(小)";
	EUF_TEXT_OPTION_TARGETTARGETFRAME           = "显示目标的目标(标准)";
	EUF_TEXT_OPTION_TARGETTARGETTARGETFRAME     = "显示目标的目标的目标(标准)";
	EUF_TEXT_OPTION_MOVINGTARGETTARGETFRAME     = "移动目标的目标(标准)";
	EUF_TEXT_OPTION_TARGET3DPORTRAIT            = "显示目标3D头像";
	EUF_TEXT_OPTION_TARGETINDICATOR             = "目标头像显示战斗数值";

	EUF_TEXT_OPTION_NOTINSTALLED                = "参数设定模块未安装, 无法启动窗口设定模式.";
	EUF_TEXT_OPTION_HELP1                       = "请使用命令行模式设定, 用法如下:";
	EUF_TEXT_OPTION_HELP2                       = "/euf 选项 参数    (示例: /euf PlayerHp 0)";
	EUF_TEXT_OPTION_HELP3                       = "具体选项请参考readme.txt, 参数为0/1或on/off";
	EUF_TEXT_OPTION_SET                         = "已将参数 [%s] 设定为 %s";
	EUF_TEXT_OPTION_INVALIDPARAM                = "无效参数";
	EUF_TEXT_OPTION_NOTCOMPATIBLE               = "以前的参数设置与新版本的参数设置不兼容, 以前的参数设置将被清除, 请重新设定.";

	EUF_TEXT_OPTION_DISPLAYTYPE                 = "显示方式";
	EUF_TEXT_OPTION_NUM                         = "数字";
	EUF_TEXT_OPTION_PERCENT                     = "百分比";
	EUF_TEXT_OPTION_ELITE                       = "精英";
	EUF_TEXT_OPTION_RARE                        = "稀有";
	EUF_TEXT_OPTION_PLAYER                      = "玩家信息";
	EUF_TEXT_OPTION_PARTY                       = "队伍信息";
	EUF_TEXT_OPTION_TARGET                      = "目标信息";
	EUF_TEXT_OPTION_TARGETTARGET                = "目标的目标";
	EUF_TEXT_DEFAULTOPTIONS                     = "默认设置"
	EUF_TEXT_CONFIRM                            = "确定";

	EUF_TEXT_TARGET 			    = "目标 ";
	EUF_TEXT_BROKENSHIELD 			    = "破甲 ";
	EUF_TEXT_LEVELTAG 			    = "%s级";
	EUF_TEXT_ELITE 				    = "精英";
	EUF_TEXT_WORLDBOSS 			    = "世界精英";
	EUF_TEXT_RARE 				    = "稀有";
	EUF_TEXT_RAREELITE 			    = "稀有精英";
end

