-- Rematch zhTW.lua
-- v4.7.0
-- 2017-06-19
-- Translator: 彩虹ui https://www.facebook.com/rainbowui/


local _,L = ...

if GetLocale()=="zhTW" then

-- New strings in 4.7.1
	L["For random pets, randomize the pets' abilities also."] = "使用隨機寵物時，也要隨機選擇寵物的技能。"
	L["Random %s"] = "隨機%s"
	L["This pet is already in the queue and Active Sort is enabled.\n\nWhile enabled, the queue has complete control over the order of pets in the queue.\n\nDo you want to turn off Active Sort to move this pet in the queue?"] = "這個寵物已經在等候區內，並且已經啟用主動排序。\n\n啟用時，等候區內寵物的順序是完全由等候區來控制。\n\n是否要停用主動排序以便在等候區內移動這個寵物?"
	L["Ignored Pet"] = "已忽略的寵物"
	L["Unknown"] = "未知"
	L["Loaded Team"] = "已載入的隊伍"
	L["Randomize Abilities Too"] = "也要隨機選擇技能"
	L["Current Leveling Pet"] = "目前正在升級的寵物"

-- New strings in 4.7.0
	L["Any Type"] = "任何類型"
	L["When this team loads, this spot will be ignored."] = "載入這個隊伍時，將會忽略此欄位。"
	L["Leveling Slot"] = "升級欄位"
	L["This slot is controlled by the leveling queue.\n\nTeams saved with leveling slots will load leveling pets from the queue into these slots."] = "這個欄位會保留給升級等候區使用。\n\n使用升級欄位的隊伍會從等候區中載入要升級的寵物到此欄位中。"
	L["Random Pet"] = "隨機寵物"
	L["When this team loads, a random high level pet will go in this spot."] = "載入這個隊伍時，此欄位會是隨機的高等級寵物。"
	L["Deadmines"] = "死亡礦坑"
	L["Ignored Slot"] = "忽略欄位"
	L["Ignore This Slot"] = "忽略這個欄位"
	L["These variables are defined as the script runs for each pet:\n\n\124cffffd200owned\124r \124cffaaaaaa(boolean)\124r\nWhether the pet is owned by the player.\n\n\124cffffd200petID\124r \124cffaaaaaa(string)\124r\nUnique ID of the owned pet, such as \"BattlePet-0-000004A98F18\".\n\n\124cffffd200speciesID\124r \124cffaaaaaa(number)\124r\nShared ID of the pet's family. Black Tabby Cats are species 42.\n\n\124cffffd200customName\124r \124cffaaaaaa(string)\124r\nName given to the pet by the player.\n\n\124cffffd200level\124r \124cffaaaaaa(number)\124r\nLevel of the pet, or nil for uncollected pets.\n\n\124cffffd200xp\124r \124cffaaaaaa(number)\124r\nAmount of xp the pet has in its current level.\n\n\124cffffd200maxXp\124r \124cffaaaaaa(number)\124r\nTotal amount of xp required to reach the pet's next level.\n\n\124cffffd200displayID\124r \124cffaaaaaa(number)\124r\nA numeric representation of a pet's model skin.\n\n\124cffffd200isFavorite\124r \124cffaaaaaa(boolean)\124r\nWhether the pet is favorited by the player.\n\n\124cffffd200name\124r \124cffaaaaaa(string)\124r\nTrue name of the pet species.\n\n\124cffffd200icon\124r \124cffaaaaaa(string)\124r\nTexture path of the pet's icon.\n\n\124cffffd200petType\124r \124cffaaaaaa(number)\124r\nValue between 1 and 10 for its type. 1=Humanoid, 2=Dragonkin, etc.\n\n\124cffffd200creatureID\124r \124cffaaaaaa(number)\124r\nThe npcID of the pet when it's summoned.\n\n\124cffffd200sourceText\124r \124cffaaaaaa(string)\124r\nFormatted text describing where the pet is from.\n\n\124cffffd200description\124r \124cffaaaaaa(string)\124r\nLore text of the species.\n\n\124cffffd200isWild\124r \124cffaaaaaa(boolean)\124r\nWhether the pet was a captured wild pet.\n\n\124cffffd200canBattle\124r \124cffaaaaaa(boolean)\124r\nWhether the pet can battle.\n\n\124cffffd200tradable\124r \124cffaaaaaa(boolean)\124r\nWhether the pet can be caged.\n\n\124cffffd200unique\124r \124cffaaaaaa(boolean)\124r\nWhether no more than one of the pet can be known at a time.\n\n\124cffffd200abilityList\124r \124cffaaaaaa(table)\124r\nArray of abilityIDs used by the species.\n\n\124cffffd200levelList\124r \124cffaaaaaa(table)\124r\nArray of levels the abilityIDs are learned.\n\nFurther information about pets can be retrieved with the \124cffffd200petInfo\124r system. See Process\\PetInfo.lua for more information."] = nil
	L["Put Random Pet Here"] = "隨機放置寵物在這裡"
	L["Teams saved with random slots will load a random high level pet into these slots."] = "使用隨機欄位的隊伍會載入隨機的高等級寵物到此欄位中。"
	L["Stop Ignoring This Slot"] = "不再忽略這個欄位"
	L["Stop Randomizing This Slot"] = "不再隨機這個欄位"
	L["Teams saved with ignored slots will not load anything into these slots."] = "使用忽略欄位的隊伍不會載入任何寵物到此欄位中。"
	L["Random %s Pet"] = "隨機%s寵物"

-- New strings in 4.6.8
	L["Export this team as a string you can copy elsewhere, such as forums or emails.\n\nOther Rematch users can paste this team into their Rematch via Import Team."] = "將這個隊伍匯出成字串，以便複製到其他地方，例如討論區或電子郵件。\n\n其他使用戰寵送作隊的玩家可以透過匯入隊伍的功能，將這個隊伍貼入。"
	L["Format this team into plain text to copy elsewhere, such as forums or emails.\n\nThe plain text format is best for sharing a team with others that may not use Rematch."] = "將這個隊伍格式化成純文字，以便複製到其他地方，例如討論區或電子郵件。\n\n純文字格式是與其他未使用戰寵送作隊的玩家分享隊伍的最佳方式。"
	L["Wailing Caverns"] = "哀嚎洞穴"
	L["Share In Legacy Format"] = "使用傳統格式分享"
	L["Prioritize Breed On Import"] = "匯入時以品級優先"
	L["Note: These are just your teams and their notes and preferences. Tab information, sort orders, win records and other settings are not included.\n\nFor the most complete backup of all your addon data, please backup your Word of Warcraft\\WTF folder."] = "特別注意：這裡只會備份你的隊伍、隊伍註記和隊伍偏好設定。不包含標籤頁資訊、排列順序、勝利記錄和其他設定。\n\n要最完整的備份所有插件資料，請備份 Word of Warcraft\\WTF 資料夾。"
	L["When exporting teams or sending to another Rematch user, use the old format.\n\nUse this option when sharing teams with someone on an older Rematch that's unable to import or receive newer teams."] = "使用舊的格式匯出隊伍或傳送給其他戰寵送作隊使用者。\n\n使用這個選項來與舊版本、無法匯入或接收新隊伍的戰寵送作隊分享隊伍。"
	L["%sWARNING!\124r This will %sPERMANENTLY DELETE\124r all teams in this tab!"] = "%s警告!\124r 將會 %s永遠刪除\124r 這個標籤頁面中的所有隊伍!"
	L["Delete teams within the tab too"] = "一併刪除標籤頁面中的隊伍"
	L["When importing or receiving teams, fill the team with the best matched breed as the first priority instead of the highest level."] = "匯入和接收隊伍時，優先使用最符合品級的寵物放入隊伍，而不是最高等級。"
	L["Broken Isle"] = "破碎群島"
	L["Import a single team or many teams that were exported from Rematch."] = "匯入由戰寵送作隊匯出的一個或多個隊伍。"
	L["Copy As Plain Text"] = "複製純文字"

-- New strings in 4.6.2
	L["A New Pet!"] = "新寵物!"
	L["%s\n\n%sWARNING!\124r There may be an issue with pet toasts in ElvUI not positioning properly. While using ElvUI it's recommended pet toasts remain hidden unless you've moved alerts in ElvUI."] = "%s\n\n%s特別注意!\124r 寵物彈出式通知在 ElvUI 中不會顯示正確的位置。使用 ElvUI 時，建議隱藏寵物彈出式通知，除非你已經在 ElvUI 中移動過通知面板的位置。"

-- New strings in 4.6.1
	L["Only Load This Team"] = "只載入隊伍"
	L["Imported Team"] = "已匯入的隊伍"
	L["This will only load the team and not save it.\n\nThis is for loading teams you do not intend to use more than once, like Family Familiar teams."] = "只載入但不儲存隊伍。\n\n這是用來載入不會再次使用的隊伍，例如成員十分相似的隊伍。"

-- New strings in 4.6.0
	L["This allows you to create custom pet filters with a little bit of Lua code. See the reference buttons at the top of the New Script dialog for details.\n\nTo view or edit an existing script, click the Gear icon beside the script in the menu above."] = "讓你可以建立自訂的寵物過濾方式，只需要使用一點點 LUA 程式碼。詳情請看新增腳本程式對話框上方的參考資料按鈕。\n\n要檢視或編輯已有的腳本程式，點一下上方選單中腳本程式旁的齒輪圖示。"
	L["Or With Panel Tabs"] = "或面板標籤頁"
	L["Group favorites to the top of the queue."] = "將最愛的寵物顯示在等候區的最上方。"
	L["When a team loads, if any pet is injured or dead and there's another version with more health \124cffffffffand identical stats\124r, load the healthier version.\n\nPets in the leveling queue are exempt from this option.\n\n\124cffffffffNote:\124r This is only when a team loads. It will not automatically swap in healthier pets when you leave battle."] = "隊伍載入時，其中任何受傷或死亡的寵物，若有另一隻相同的寵物擁有更高的生命力和\124cffffffff完全相同的屬性\124r，便會載入這隻生命力較高的寵物。\n\n升級等候區中的寵物不適用於這個選項。\n\n\124cffffffff注意:\124r 只有載入隊伍時才會執行這個動作，戰鬥結束時並不會自動調換成生命力較高的寵物。"
	L["Do nothing when pets within Rematch are double-clicked. The normal behavior of double click throughout Rematch is to summon or dismiss the pet."] = "滑鼠點兩下戰寵送作隊中的寵物時不要執行任何動作。一般來說，在戰寵送作隊中點兩下會召喚或解散寵物。"
	L["Load Healthiest Pets"] = "載入生命力最高的寵物"
	L["The script environment is restricted with access to only common Lua and the following:\n\n\124cffffd200C_PetJournal \124cffaaaaaa(table)\124r\nThe default API for journal functions.\n\n\124cffffd200C_PetBattles \124cffaaaaaa(table)\124r\nThe default API for the battle UI.\n\n\124cffffd200GetBreed \124cffaaaaaa(function)\nArgument:\124r petID\n\124cffaaaaaaReturns:\124r The numeric breed (3-12) of a petID if one of the supported breed addons is enabled.\n\n\124cffffd200GetSource \124cffaaaaaa(function)\nArgument:\124r speciesID\n\124cffaaaaaaReturns:\124r The numeric source (1-10) of a speciesID. 1=Drop, 2=Quest, etc.\n\n\124cffffd200IsPetLeveling \124cffaaaaaa(function)\nArgument:\124r petID\n\124cffaaaaaaReturns:\124r Whether the given petID is in the leveling queue.\n\nA few iterator functions are also provided if you need to compare a pet against others. These are used in a for loop such as:\n\n\124cffcccccc    for speciesID in \124cffffd200AllSpeciesIDs()\124cffcccccc do\n      -- do something with speciesID\n    end\124r\n\n\124cffffd200AllSpeciesIDs \124cffaaaaaa(iterator function)\nReturns:\124r The next speciesID of all existing unique pets.\n\n\124cffffd200AllPetIDs \124cffaaaaaa(iterator function)\nReturns:\124r The next petID of all owned pets.\n\n\124cffffd200AllPets \124cffaaaaaa(iterator function)\nReturns:\124r The next petID or speciesID of all pets in the master list. Owned pets return a petID string, uncollected pets return a speciesID number.\n\n\124cffffd200AllAbilities \124cffaaaaaa(iterator function)\nArgument:\124r speciesID\n\124cffaaaaaaReturns:\124r The next abilityID and level of the ability for a speciesID.\n\124cffffd200Note:\124r abilityList and levelList are already defined for each pet as your script runs. Use this iterator if you need to gather abilities of other pets for comparison. See the Unique Abilities script for an example.\n\n\124cffffd200If you would like anything else exposed please post a comment on wowinterface, curse or warcraftpet's Rematch 4.0 thread."] = nil
	L["\124cffffd200-\124r Scripts are a way to create custom pet filters.\n\n\124cffffd200-\124r Scripts are Lua code and require some knowledge of the language and API to create your own filters.\n\n\124cffffd200-\124r Scripts run for each pet and should return true if the pet is to be listed.\n\n\124cffffd200-\124r Some variables are filled in as the script runs for each pet. See Pet Variables.\n\n\124cffffd200-\124r Scripts run in a restricted environment with no access outside its environment. See Exposed API.\n\n\124cffffd200-\124r All variables/tables created exist only in this environment and disappear when the filter finishes.\n\n\124cffffd200-\124r If the first line of the script is a --comment, it will be used as a tooltip in the Script menu."] = nil
	L["Don't let the Pets, Teams, Queue or Options tabs minimize the standalone window."] = "點選寵物、隊伍、等候區或選項標籤頁時不要最小化獨立視窗。"
	L["On Loaded Abilities Too"] = "載入的技能也是"
	L["Group rares to the top of the leveling queue."] = "將稀有的寵物顯示在等候區的最上方。"
	L["In addition to the flyouts, show the numbers 1 and 2 on loaded abilities in all but minimized views."] = "包括彈出式按鈕，在所有已載入的技能上顯示數字 1 和 2，只有最小化的檢視不用。"
	L["No Summon On Double Click"] = "滑鼠點兩下時不要召喚"
	L["Rares First"] = "稀有優先"
	L["Script Filters"] = "腳本程式過濾方式"

-- New strings in 4.5.0
	L["This is the leveling queue. Drag pets you want to level here.\n\nRight click any of the three battle pet slots and choose 'Put Leveling Pet Here' to mark it as a leveling slot you want controlled by the queue.\n\nWhile a leveling slot is active, the queue will fill the slot with the top-most pet in the queue. When this pet reaches level 25 (gratz!) it will leave the queue and the next pet in the queue will take its place.\n\nTeams saved with a leveling slot will reserve that slot for future leveling pets."] = "這是升級等候區，將想要升級的寵物拖曳到這裡。\n\n右鍵點擊3個戰寵欄位的其中任何一個並且選擇 '將要升級的寵物放在這裡'，會將這個欄位標記為升級欄位，並且交由升級等候區來控制。\n\n升級欄位啟用時，會自動將升級等候區最前面的寵物放在這個欄位中。當寵物達到 25 級後 (恭喜!) 就會離開等候區，然後由等候區中的下一個寵物接替它的位置。\n\n儲存的隊伍包含升級欄位時，會將這個欄位保留給未來要升級的寵物。"
	L["Don't show a popup offering to backup teams every once in a while. Generally, the popup appears sometime after the number of teams increases by 50."] = "不要每隔一段時間就跳出備份隊伍的詢問選項。一般來說，當隊伍增加數量超過 50 的時候會跳出來。"
	L["Backup All Rematch Teams?"] = "是否要備份戰寵送作隊的所有隊伍?"
	L["Don't Remind About Backups"] = "不要提醒備份"
	L["Choosing Yes will export all teams to copy and paste in an email to yourself or someplace safe.\n\nYou can also do this at any time from the Teams button at the top of the Teams panel of Rematch."] = "選擇 '是' 會匯出所有隊伍，以便複製貼上到電子郵件或其他安全的地方。\n\n任何時候都可以從戰寵送作隊的隊伍面板上方的隊伍按鈕來執行這個動作。"
	L["Leveling Queue"] = "升級等候區"
	L["You have %s%d\124r Rematch teams.\n\nWould you like to back them up?"] = "你有 %s%d\124r 個戰寵送作隊的隊伍。\n\n是否要備份隊伍資料?"
	L["Confirmation Options"] = "確認選項"
	L["Stop Leveling This Slot"] = "停止升級這個欄位"

-- Additional strings to Template.lua
	L["Cage this pet?"] = "是否要把這個寵物放入籠子?" -- Menus\PetMenus.lua
	L["You are in combat. Try again when out of combat."] = "目前正在戰鬥中，請於戰鬥結束後再操作一次。" -- Frames\Frame.lua, Frames\Journal.lua
	L["Undo"] = "還原" -- Cards\Notes.xml
	-- rematch.breedNames = {"平/平","攻/攻","速/速","血/血","血/攻","攻/速","血/速","攻/平","速/平","血/平"} -- Process\Breeds.lua
	
-- New strings in 4.4.9
	L["In addition to the filters in this menu, you can further refine the pet list with the search box. Some search examples:\n\nPets: %sBlack Tabby\124r\nZones: %sSilithus\124r\nAbilities: %sSandstorm\124r\nText in abilities: %sBleed\124r\nLevels: %slevel=21-23\124r\nStats: %sspeed>300\124r\n\nSearches in \"quotes\" will limit results to only complete matches.\n\nSearch results will be sorted by relevance unless the option %sDon't Sort By Relevance\124r is checked in the Options tab."] = "除了選單中的過濾方式之外，還可以使用搜尋框來進一步細分寵物清單。這裡列出一些搜尋範例: \n\n寵物: %s亮爪\124r\n地區: %s遊戲商城\124r\n技能: %s撕咬\124r\n技能中的文字: %s流血\124r\n等級: %slevel=21-23\124r\n屬性: %sspeed>300\124r\n\n使用 \"雙引號\" 時只會顯示完全符合的搜尋結果。\n\n搜尋結果會依據相關性排序，除非啟用選項標籤頁中的 %s不要依據相關性排序\124r。"
	L["Change Name Or Target"] = "更改名稱或對象"
	L["Stats Search"] = "屬性搜尋"

-- New strings in 4.4.7
	L["Don't Sort By Relevance"] = "不要依據相關性排序"
	L["When searching for something by name in the search box, do not sort the results by relevance.\n\nWhen sorted by relevance, pets with the search term in their name are listed first, followed by terms in notes, then abilities and then source text last."] = "在搜尋框輸入名字搜尋的時候，不要依據相關性排序搜尋結果。\n\n依據相關性排序時，名字中有搜尋關鍵字的寵物會排在最前面，接著是註記中有關鍵字的寵物，再來是技能，最後是詳細資訊文字。"
	L["Val'sharah"] = "維爾薩拉"
	L["Suramar"] = "蘇拉瑪爾"
	L["Stormheim"] = "斯鐸海姆"
	L["Highmountain"] = "高嶺"
	L["Dalaran"] = "達拉然"
	L["Azsuna"] = "艾蘇納"

-- New strings in 4.4.6
	L["About Teams"] = "關於隊伍"
	L["Teams named in %sWhite\124r have a target stored within them.\nTeams named in Gold do not.\n\n%sTo change pets or abilities in a team:\124r\n1) Load the team.\n2) Make any changes.\n3) Click Save at the bottom of the window."] = "有記錄對手的隊伍名稱為%s白色\124r。\n沒有對手的隊伍名稱是金色。\n\n%s要更改隊伍中的寵物或技能:\124r\n1) 載入隊伍。\n2) 做任何調整。\n3) 按視窗下面的儲存按鈕。"

-- New strings in 4.0.0
	L["Auto load upon targeting only, not mouseover.\n\n\124cffff4040WARNING!\124r This is not recommended! It can be too late to load pets if you target with right-click!"] = "選取為目標時才自動載入，而不是滑鼠指向。\n\n\124cffff4040警告!\124r 不建議使用! 如果你使用右鍵點選目標，會來不及載入寵物。"

-- Main.lua
	L["Rematch"] = "戰寵送作隊"
	L["Toggle Window"] = "開啟/關閉視窗"
	L["Auto Load"] = "自動載入"
	L["Team Notes"] = "隊伍註記"
	L["Pets Tab"] = "寵物標籤頁"
	L["Teams Tab"] = "隊伍標籤頁"
	L["Queue Tab"] = "等候區標籤頁"
	L["Toggle Rematch"] = "開啟/關閉戰寵送作隊"
	L["Load this team?"] = "是否載入這個隊伍?"
	L["They do not appear to be online."] = "他們似乎不在線上。"
	L["has also been added to your leveling queue!"] = "已經加入升級等候區!"
	L["The team named '%s' can't be found."] = "無法找到名稱為 '%s' 的隊伍。"
	L["Rematch Debug Info"] = "戰寵送作隊除錯資訊"

-- Utils.lua
	L["Leveling Pet"] = "升級寵物"

-- Widgets\PetListButtons.lua
	L["Empty Battle Pet Slot"] = "清空戰寵欄位"
	L["This pet can't level."] = "這個寵物無法升級。"
	L["Only pets that can battle and are under 25 can go in the leveling queue."] = "25級以下可以戰鬥的寵物，才能加入升級等候區。"

-- Widgets\Toolbar.lua
	L["Total Pets"] = "寵物數目"
	L["Unique Pets"] = "不重複"
	L["Save As..."] = "另存為..."
	L["Save the currently loaded pets to a new team."] = "將目前載入的寵物儲存為新的隊伍。"
	L["Save the currently loaded pets to the loaded team."] = "將目前載入的寵物儲存至已載入的隊伍。"
	L["Dismiss Pet"] = "解散寵物"
	L["Summon Pet"] = "召喚寵物"
	L["Summons a random pet from your favorites."] = "從最愛中隨機召喚寵物"
	L["Random Favorite"] = "隨機最愛"
	L["Random From All"] = "隨機全部"
	L["All pets are at full health."] = "所有寵物的生命值都已完全恢復。"
	L["This treat's buff is already active."] = "治療效果已經啟用。"
	L["%s\n\nPets At Max Level: %s%d\124r\nPets Not Collected: %s%d\124r\n\n%s Click to display more about your collection."] = "%s\n\n等級已滿寵物: %s%d\124r\n尚未收集寵物: %s%d\124r\n\n%s 點一下顯示更多收藏。"
-- Widgets\MinimapButton.lua
	L["Load Favorite Team"] = "載入最愛隊伍"
	L["Favorite Teams"] = "最愛隊伍"

-- Widgets\PanelTabs.lua

-- Process\PetLoading.lua
	L["You can't load a team during combat."] = "無法在戰鬥中載入隊伍。"
	L["You can't load a team during a pet battle."] = "無法在寵物對戰時載入隊伍。"
	L["You can't load a team in a matched pet battle."] = "無法從已配對的寵物對戰中載入隊伍。"
	L["Loading..."] = "正在載入..."
	L["Pets are missing from this team!"] = "無法找到這個隊伍的寵物!"
	L["Substitutes were found. Please review the loaded team and click Save if you'd like to keep the chosen pets."] = "發現替補。若要保留已經選擇的寵物，請重新檢視已經載入的隊伍並且按下儲存。"
	L["Don't Warn About Missing Pets"] = "無法找到寵物時不要警告"

-- Process\Roster.lua

-- Process\Filters.lua
	L["Favorites"] = "最愛"
	L["Types"] = "類型"
	L["Strong Vs"] = "普通 Vs"
	L["Tough Vs"] = "困難 Vs"
	L["Breed"] = "品級"
	L["Similar"] = "類似"
	L["Script"] = "腳本程式"
	L["Level"] = "等級"
	L["Leveling"] = "升級"
	L["Tradable"] = "可交易"
	L["Battle"] = "對戰"
	L["Quantity"] = "稀有程度"
	L["Team"] = "隊伍"
	L["Hidden"] = "隱藏"
	L["Zone"] = "地區"
	L["Notes"] = "註記"
	L["Search"] = "搜尋"
	L["Sort"] = "排序方式"

-- Process\PetList.lua
-- Process\QueueProcess.lua
	L["All done leveling pets!"] = "寵物已經全部升級完成!"
	L["Rematch's leveling queue is empty"] = "戰寵送作隊的升級等候區是空的"
	L["Now leveling:"] = "正在升級:"

-- Process\Sanctuary.lua

-- Menus\Menu.lua
	L["Help"] = "說明"

-- Menus\TeamMenus.lua
	L["Edit Win Record"] = "編輯勝利記錄"
	L["Edit Team"] = "編輯隊伍"
	L["Set Notes"] = "設定註記"
	L["Move To"] = "移動至"
	L["Move To Top"] = "移動至最上方"
	L["Move Up"] = "往上移"
	L["Move Down"] = "往下移"
	L["Move To End"] = "移動至最下方"
	L["Share"] = "分享"
	L["Delete this team?"] = "是否要刪除這個隊伍?"
	L["Unload Team"] = "取消載入隊伍"
	L["Put Leveling Pet Here"] = "將要升級的寵物放在這裡"
	L["Add a leveling pet to this team?"] = "是否要在這個隊伍中加入等候升級的寵物?"
	L["Import Team"] = "匯入隊伍"
	L["Import a single team or many teams that was exported from Rematch."] = "匯入從戰寵送作隊匯出的一個或多個隊伍。"
	L["Send Team"] = "傳送隊伍"
	L["Sharing is disabled in options."] = "在選項設定中已經停用分享。"
	L["Send this team to another online user of Rematch."] = "將這個隊伍傳送給另一位在線上的戰寵送作隊使用者"
	L["Prompt To Load"] = "提示載入"
	L["When your new target has a saved team not already loaded, and the target panel isn't on screen, display a popup asking if you want to load the team.\n\nThis is only for the first interaction with a target. You can always load a target's team from the target panel."] = "新的對手有已儲存的隊伍，但是卻未載入，而且畫面上沒有出現對手面板時，顯示彈出訊息來詢問是否要載入隊伍。\n\n只有第一次和對手互動時才會提示載入，但總是可以從對手面板載入對手的隊伍。"
	L["With Rematch Window"] = "同時也載入戰寵送作隊視窗"
	L["Prompt to load with the Rematch window instead of a separate popup dialog."] = "提示並且載入戰寵送作隊視窗，而不是只有彈出訊息對話框。"
	L["Always Prompt"] = "總是提示"
	L["Prompt every time you interact with a target with a saved team not already loaded, instead of only the first time."] = "每次和對手互動，但卻沒有載入已儲存的隊伍時都要提示，而不是只有第一次。"
	L["When you mouseover a new target that has a saved team not already loaded, immediately load it.\n\nThis is only for the first interaction with a target. You can always load a target's team from the target panel."] = "滑鼠指向一個新的對手，但卻沒有載入已儲存的隊伍時，立即載入。\n\n只有第一次和對手互動時才會提示載入，但總是可以從對手面板載入對手的隊伍。"
	L["Show After Loading"] = "載入後顯示"
	L["After a team auto loads, show the Rematch window."] = "載入隊伍後，顯示戰寵送作隊視窗。"
	L["Show On Injured"] = "受傷時顯示"
	L["When a team auto loads, show the Rematch window if any pets are injured."] = "自動載入隊伍時，如果任何一個寵物受傷的話，顯示戰寵送作隊視窗。"
	L["On Target Only"] = "選為對手才載入"
	L["Auto load upon targeting only, not mouseover.\n\n\124cffff4040WARNING!\124r This is not recommended! It can be too late to load pets if you target with right click!"] = "只有選取為對手時才自動載入，滑鼠指向不載入。\n\n\124cffff4040警告!\124r 不建議使用! 如果用滑鼠右鍵來選取為對手，會來不及載入寵物。"
	L["Export Listed Teams"] = "匯出列出的隊伍"
	L["Export all teams listed below to a string you can copy elsewhere, such as forums or emails.\n\nOther Rematch users can then paste these teams into their Rematch via Import Teams.\n\nYou can export a single team by right-clicking one and choosing its Share menu."] = "將下面列出的所有隊伍匯出成字串，以便複製到其他地方，例如討論區或電子郵件。\n\n其他戰寵送作隊的使用者可以透過匯入隊伍的功能，將這些隊伍貼入。\n\n要匯出單一隊伍，在隊伍上點滑鼠右鍵，選擇分享選單。"
	L["Backup All Teams"] = "備份所有隊伍"
	L["This will export all teams across all tabs into text that you can paste elsehwere, such as an email to yourself or a text file someplace safe. You can later restore these teams with the Import Teams option."] = "將所有標籤頁的所有隊伍匯出成文字，以便在其他任何地方貼上，例如寄送電子郵件給自己，或是將文字檔案放置在某個安全的地方。日後可以使用匯入隊伍選項來恢復這些隊伍。"
	L["Import Teams"] = "匯入隊伍"
	L["Import From Pet Battle Teams"] = "從戰寵隊伍匯入"
	L["Copy your existing teams from Pet Battle Teams to Rematch."] = "將戰寵隊伍中已有的隊伍複製到戰寵送作隊。"

-- Menus\PetMenus.lua
	L["Unnamed Pets"] = "未命名的寵物"
	L["-- Collected pets that still have their original name.\n\nreturn owned and not customName"] = "-- 已收集的寵物中，仍然保留原始名字的寵物。\n\nreturn owned and not customName"
	L["Partially Leveled"] = "升級到一半的"
	L["-- Pets that have earned some xp in battle.\n\nreturn xp and xp>0"] = "-- 在對戰中獲得經驗值的寵物。\n\nreturn xp and xp>0"
	L["Unique Abilities"] = "擁有不重複技能"
	L["-- Pets with abilities not shared by other pets.\n\nif not count then\n  -- create count of each ability per species\n  count = {}\n  for speciesID in AllSpeciesIDs() do\n    for abilityID in AllAbilities(speciesID) do\n      if not count[abilityID] then\n        count[abilityID] = 0\n      end\n      count[abilityID] = count[abilityID] + 1\n    end\n  end\nend\n\nfor _,abilityID in ipairs(abilityList) do\n  if count[abilityID]==1 then\n    return true\n  end\nend"] = "-- 寵物擁有獨一無二、其他寵物都沒有的技能。\n\nif not count then\n  -- create count of each ability per species\n  count = {}\n  for speciesID in AllSpeciesIDs() do\n    for abilityID in AllAbilities(speciesID) do\n      if not count[abilityID] then\n        count[abilityID] = 0\n      end\n      count[abilityID] = count[abilityID] + 1\n    end\n  end\nend\n\nfor _,abilityID in ipairs(abilityList) do\n  if count[abilityID]==1 then\n    return true\n  end\nend"
	L["Pets Without Rares"] = "缺少稀有品質"
	L["-- Collected battle pets that have no rare version.\n\nif not rares then\n  rares = {}\n  for petID in AllPetIDs() do\n    if select(5,C_PetJournal.GetPetStats(petID))==4 then\n      rares[C_PetJournal.GetPetInfoByPetID(petID)]=true\n    end\n  end\nend\n\nif canBattle and owned and not rares[speciesID] then\n  return true\nend"] = "-- 已收集的戰寵沒有稀有品質的版本。\n\nif not rares then\n  rares = {}\n  for petID in AllPetIDs() do\n    if select(5,C_PetJournal.GetPetStats(petID))==4 then\n      rares[C_PetJournal.GetPetInfoByPetID(petID)]=true\n    end\n  end\nend\n\nif canBattle and owned and not rares[speciesID] then\n  return true\nend"
	L["Hybrid Counters"] = "擁有混合技能"
	L["-- Pets with three or more attack types different than their pet type.\n\nlocal count = 0\nfor _,abilityID in ipairs(abilityList) do\n  local abilityType,noHints = select(7, C_PetBattles.GetAbilityInfoByID(abilityID) )\n  if not noHints and abilityType~=petType then\n    count = count + 1\n  end\nend\n\nreturn count>=3\n"] = "-- 擁有三個或以上非自身寵物類型的攻擊技能的寵物。\n\nlocal count = 0\nfor _,abilityID in ipairs(abilityList) do\n  local abilityType,noHints = select(7, C_PetBattles.GetAbilityInfoByID(abilityID) )\n  if not noHints and abilityType~=petType then\n    count = count + 1\n  end\nend\n\nreturn count>=3\n"
	L["Find Similar"] = "尋找類似"
	L["Enter a new name"] = "輸入新的名稱"
	L["List %d Teams"] = "列出 %d 組隊伍"
	L["Hide Pet"] = "隱藏寵物"
	L["Unhide Pet"] = "取消隱藏寵物"
	L["Slotted pets cannot be released."] = "放入欄位的寵物無法遺棄。"
	L["Release this pet?"] = "是否要遺棄這個寵物?"
	L["Once released, this pet is gone forever!"] = "一旦遺棄，寵物將會永遠消失!"
	L["Slotted pets cannot be caged."] = "放入欄位的寵物無法放入籠子。"
	L["Injured pets cannot be caged."] = "受傷的寵物無法放入籠子。"
	L["Start Leveling"] = "開始升級"
	L["Add To Leveling Queue"] = "加入升級等候區"
	L["Stop Leveling"] = "停止升級"
	L["Only Favorites"] = "只有最愛"
	L["Favorite Filters"] = "最愛過濾方式"
	L["Pet Filter"] = "寵物過濾方式"
	L["In addition to the filters in this menu, you can further refine the pet list with the search box. Some search examples:\n\nPets: %sBlack Tabby\124r\nZones: %sSilithus\124r\nAbilities: %sSandstorm\124r\nText in abilities: %sBleed\124r\nLevels: %slevel=21-23\124r\nStats: %sspeed>300\124r\n\nSearches in \"quotes\" will limit results to only complete matches."] = "除了選單中的過濾方式之外，還可以使用搜尋框來進一步細分寵物清單。這裡列出一些搜尋範例: \n\n寵物: %s亮爪\124r\n地區: %s遊戲商城\124r\n技能: %s撕咬\124r\n技能中的文字: %s流血\124r\n等級: %slevel=21-23\124r\n屬性: %sspeed>300\124r\n\n使用 \"雙引號\" 時只會顯示完全符合的搜尋結果。"
	L["Reset All"] = "全部重置"
	L["Checkbox Groups"] = "核取方塊群組"
	L["In filter menus, checkbox groups assume if nothing is checked you want to view all choices.\n\nYou can also:\n\n%s[Shift]+Click\124r to check all except the box clicked.\n\n%s[Alt]+Click\124r to uncheck all except the box clicked."] = "在過濾方式選單中，如果沒有勾選任何一項，表示想要檢視全部。\n\n還可以: \n\n%s[Shift]+左鍵點一下\124r 來勾選除了點到的核取方塊以外的所有項目。\n\n%s[Alt]+左鍵點一下\124r 來取消勾選除了點到的核取方塊以外的所有項目。"
	L["Low Level (1-7)"] = "低等級 (1-7)"
	L["Mid Level (8-14)"] = "中等級 (8-14)"
	L["High Level (15-24)"] = "高等級 (15-24)"
	L["Max Level (25)"] = "最高等級 (25)"
	L["Without Any 25s"] = "不包含25級"
	L["Moveset Not At 25"] = "尚未25"
	L["You can filter to a specific level or range of levels in the search box. For example, search for:\n\n\%slevel=1\124r\nor\n\%slevel=21-23\124r"] = "可以在搜尋框中指定等級或等級範圍來過濾。例如搜尋:\n\n\%slevel=1\124r\n或\n\%slevel=21-23\124r"
	L["All breed data is pulled from your installed %s%s\124r addon.\n\nThe breed \"New\" categorizes pets with no breed data. Keep your breed addon up to date to see if they have new data."] = "品級資料皆取自於你所安裝的插件 %s%s\124r。\n\n\"全新\"品級類別中的寵物沒有品級資料。請將品級插件保持在最新版本，以便取得新的資料。"
	L["Not Leveling"] = "無法升級"
	L["Not Tradable"] = "無法交易"
	L["Can Battle"] = "無法對戰"
	L["Can't Battle"] = "無法對戰"
	L["One Copy"] = "一隻"
	L["Two+ Copies"] = "兩隻以上"
	L["Three+ Copies"] = "三隻以上"
	L["In A Team"] = "同隊伍"
	L["Not In A Team"] = "不在同隊伍"
	L["Current Zone"] = "目前地區"
	L["Hidden Pets"] = "隱藏寵物"
	L["Has Notes"] = "有註記的"
	L["Reverse Sort"] = "反向排序"
	L["Favorites First"] = "最愛優先"
	L["Sort By"] = "排序方式"
	L["You can filter to a specific range of stats too. For example, search for:\n\n\%shealth>500\124r\nor\n\%sspeed=200-300\124r\n\nThe sort order is not ordinarily reset when filters are reset. The option %sReset Sort With Filters\124r in the Options tab will reset the sort when you reset the filters."] = "也可以依據指定屬性的範圍來過濾。例如搜尋:\n\n\%shealth>500\124r\n或\n\%sspeed=200-300\124r\n\n重置過濾方式時，通常不會一起重置排序方式。選項標籤頁中的 %s同時重置過濾和排序方式\124r 選項會在重置過濾方式的時候一併重置排序方式。"
	L["Find Pets With This Ability"] = "搜尋擁有這個能力的寵物"
	L["Hide this pet?"] = "是否要隱藏這個寵物?"
	L["Don't Ask When Hiding Pets"] = "隱藏寵物時不要詢問"
	L["Are you sure you want to hide all versions of %s%s\124r?\n\nHidden pets will not show up in the pet list or searches. You can view or unhide these pets in the 'Other' filter."] = "是否要隱藏所有版本的 %s%s\124r?\n\n隱藏的寵物不會在寵物清單和搜尋結果中出現。你可以在 '其他' 過濾方式中檢視寵物或取消隱藏。"
	L["Save Filter"] = "儲存過濾方式"
	L["A filter must be active before it can be saved."] = "過濾方式必須先啟用才能儲存。"
	L["Save this as a favorite filter?"] = "是否要儲存為最愛的過濾方式?"
	L["Filters: %s%s\124r\n\nChoose a name to use in the Favorite Filters menu:"] = "過濾方式: %s%s\124r\n\n在最愛的過濾方式選單中選擇要使用的名稱:"
	L["Note: Search text and Sort order are not included in the filter."] = "請注意: 過濾方式中不包含搜尋文字和排列順序。"
	L["Delete Filter"] = "刪除過濾方式"
	L["Are you sure you want to delete the filter named %s%s\124r?"] = "是否確定要刪除名稱為 %s%s\124r 的過濾方式?"
	L["New Script"] = "新增腳本程式"
	L["Create a new pet filter."] = "建立新的寵物過濾方式。"
	L["Delete Script"] = "刪除腳本程式"
	L["Are you sure you want to delete the script named %s%s\124r?"] = "是否確定要刪除名稱為 %s%s\124r 的腳本程式?"

	-- Menus\Npcs.lua
	L["Eastern Kingdom"] = "東部王國"
	L["Kalimdor"] = "卡林多"
	L["Outland"] = "外域"
	L["Northrend"] = "北裂境"
	L["Cataclysm"] = "浩劫與重生"
	L["Pandaria"] = "潘達利亞"
	L["Beasts of Fable"] = "寓言裡的野獸"
	L["Celestial Tournament"] = "天尊武道會"
	L["Draenor"] = "德拉諾"
	L["Garrison"] = "要塞"
	L["Menagerie"] = "寵物園"
	L["Tanaan Jungle"] = "塔南森林"
	L["No Target"] = "沒有對手"
	L["Noteworthy Targets"] = "值得一戰的對手"
	L["These are noteworthy targets such as tamers and legendary pets.\n\nChoose one to view the pets you would battle.\n\nTargets with a \124TInterface\\RaidFrame\\ReadyCheck-Ready:14\124t already have a team saved."] = "馴獸師和傳說寵物都是值得一戰的對手。\n\n選擇一個你想要對戰的寵物來瀏覽。\n\n\標示 \124TInterface\\RaidFrame\\ReadyCheck-Ready:14\124t 的對戰對手已有儲存的隊伍。"

-- Dialogs\Dialog.lua
	L["Tab:"] = "標籤頁:"

-- Dialogs\Save.xml
	L["Name:"] = "名稱:"
	L["Target:"] = "對手:"

-- Cards\PetCard.lua
	L["Damage\nTaken"] = "受到的\n傷害"
	L["from"] = "來自"
	L["abilities"] = "技能"
	L["Unpin Pet Card"] = "取消固定顯示寵物卡"
	L["While pinned, pet cards will display where you last moved it.\n\nClick this to unpin the pet card and snap it back to the pets."] = "固定顯示時，寵物卡會一直顯示在最後移動的位置。"
	L["Pet Card"] = "寵物卡"
	L["Hold [Alt] to view more about this pet."] = "按住 [Alt] 檢視關於這個寵物的詳細資訊。"
	L["XP: %d/%d (%d%%)"] = "經驗值: %d/%d (%d%%)"
	L["Possible Breeds"] = "可能的品級"
	L["Slotted"] = "複數"
	L["This pet is loaded in one of the three battle pet slots."] = "這個寵物是從三個戰寵欄位的其中一個載入的。"
	L["Favorite"] = "最愛"
	L["This pet is marked as a Favorite from its right-click menu."] = "透過右鍵選單將這個寵物被標示為最愛。"
	L["This pet is in Rematch's leveling queue."] = "這個寵物在戰寵送作隊的升級等候區中。"
	L["Determines how stats are distributed.  All breed data is pulled from your installed %s%s\124r addon."] = "決定屬性分佈。 所有品級資料皆取自於你所安裝的插件 %s%s\124r。"
	L["%d Teams"] = "%d 組隊伍"
	L["Teams"] = "隊伍"
	L["%s Click to search for all teams that include this pet."] = "%s點擊搜尋包含這個寵物的所有隊伍。"
	L["%s Click to search for all versions of this pet."] = "%s點擊搜尋這個寵物的所有版本。"
	L["When this team loads, your current leveling pet will go in this spot."] = "載入這個隊伍時，首要升級的寵物會出場比賽。"
	L["This is an opponent pet."] = "這是敵對的寵物。"
	L["All breed data pulled from %s%s\124r."] = "品級資料取自於插件 %s%s\124r。"
	L["Stats At Level 25 \124cff0070ddRare"] = "25級時的屬性\124cff0070dd稀有"
	L["No known breeds :("] = "未知的品級 :("
	L["Species ID"] = "寵物種類ID"
	L["All versions of this pet share this unique \"species\" number."] = "這個寵物的所有版本都會共用這個專屬的 \"寵物種類ID\" 數字。"
	

-- Cards\AbilityCard.lua
	L["Vs"] = nil

-- Cards\Notes.lua
	L["Pet Notes"] = "寵物註記"
	L["Delete Notes"] = "刪除註記"
	L["Are you sure you want to delete the notes for %s\124r?"] = "是否要刪除 %s\124r 的註記?"
	L["Undo"] = "復原"	-- Notes.xml

-- Cards\WinRecord.lua
	L["Win Record"] = "勝利記錄"
	L["Wins:"] = "勝利:"
	L["Losses:"] = "戰敗:"
	L["Draws:"] = "平手:"
	L["Totals Across All Teams"] = "所有隊伍的總數"
	L["%s%s\124r Battles"] = "%s%s\124r 場對戰"
	L["+1 Win"] = "+1 勝利"
	L["+1 Loss"] = "+1 戰敗"
	L["+1 Draw"] = "+1 平手"
	L["Reset Win Record"] = "重置勝利記錄"
	L["Are you sure you want to remove all wins, losses and draws from the team \"%s\"?"] = "是否確定要移除隊伍 \"%s\"  的所有勝利、戰敗和平手的記錄?"
	L["Reset All Win Records"] = "重置所有勝利記錄"
	L["Are you sure?"] = "是否確定要這麼做?"
	L["This will remove win record data for all teams and cannot be undone!"] = "將會移除所有隊伍的勝利記錄資料，而且無法復原!"
	L["Convert Team Names To Win Records"] = "將隊伍名稱轉換為勝利記錄"
	L["Convert"] = "轉換"
	L["This will look for teams with names that may include win-loss-draw stats and pull those into an actual win record before removing the numbers from the team name.\n\nDo you want to convert these teams?\n\nThe currently loaded team will be unloaded to prevent major complications.\n\n\124cffff1111Please backup your teams before attempting this!"] = "在移除隊伍名稱中的數字之前，檢查名稱中可能包含勝利-戰敗-平手資訊的隊伍，將資訊放入真正的勝利記錄中。\n\n是否要轉換這些隊伍?\n\n將會取消載入目前已載入的隊伍，讓轉換過程可以更順利。\n\n124cffff1111開始前請先備份你的隊伍!"
	L["Done!"] = "完成!"
	L["%s%d teams and %d battles were converted."] = "已轉換 %s%d 個隊伍和 %d 場對戰。"
	L["Hold [Alt] to view totals for all teams."] = "按住 [Alt] 檢視所有隊伍的總合。" -- Cards\WinRecord.xml

-- Panels\PetPanel.lua
	L["Strong vs"] = "普通 vs"
	L["Tough vs"] = "困難 vs"
	L["Pets: %s%d"] = "寵物: %s%d"
	L["Filters: %s%s"] = "過濾方式: %s%s"

-- Panels\LoadoutPanel.lua
	L["Target has a saved team"] = "對手已有儲存的隊伍"
	L["Load"] = "載入"
	L["Load the team saved for this target."] = "載入這個對手已儲存的隊伍"
	L["This target has no saved team"] = "對手沒有已儲存的隊伍"
	L["Save the currently loaded pets to this target."] = "儲存目前已經載入的寵物，供這個對手使用。"

-- Panels\TeamPanel.lua

-- Panels\QueuePanel.lua
	L["Ascending Level"] = "等級由低至高"
	L["Descending Level"] = "等級由高至低"
	L["Median Level"] = "等級中間值"
	L["Type"] = "類型"
	L["Queue"] = "等候區"
	L["Sort by:"] = "排序方式:"
	L["Sort all pets in the queue from level 1 to level 24."] = "依據等級1至24來排序等候區中的所有寵物。"
	L["Sort all pets in the queue for levels closest to 10.5."] = "依據等級接近10.5來排序等候區中的所有寵物。"
	L["Sort all pets in the queue from level 24 to level 1."] = "依據等級24至1來排序等候區中的所有寵物。"
	L["Sort all pets in the queue by their types."] = "依據類型來排序等候區中的所有寵物。"
	L["Active Sort"] = "主動排序"
	L["The queue will stay sorted in the order chosen. The order of pets may automatically change as they gain xp or get added/removed from the queue.\n\nYou cannot manually change the order of pets while the queue is actively sorted."] = "等候區會依據選擇的先後來排序。當寵物獲得經驗值，或從等候區新增/移除時，排列順序可能會自動改變。\n\n等候區主動排序時，將無法手動更改寵物的順序。"
	L["Pause Preferences"] = "暫停偏好"
	L["Suspend all preferred loading of pets from the queue, except for pets that can't load."] = "暫停所有從等候區載入寵物的特別偏好，除了那些無法載入的寵物。"
	L["Fill Queue"] = "加入等候區"
	L["Fill the leveling queue with one of each version of a pet that can level from the filtered pet list, and for which you don't have a level 25 or one in the queue already."] = "將已過濾清單中的寵物，可以戰鬥且沒有一個滿等級25的寵物，都加入一隻到升級等候區。"
	L["Fill Queue More"] = "加入更多到等候區"
	L["Fill the leveling queue with one of each version of a pet that can level from the filtered pet list, regardless whether you have any at level 25 or one in the queue already."] = "將已過濾的寵物瀏覽器中，可以戰鬥的寵物都加入到升級等候區，不論是否已經有等級25的同樣寵物，或是否已經加入。"
	L["Empty Queue"] = "清空等候區"
	L["Remove all leveling pets from the queue."] = "移除等候區中所有等待升級的寵物。"
	L["Are you sure you want to remove all pets from the leveling queue?"] = "是否要移除升級等候區中的所有寵物?"
	L["No Active Sort"] = "停用主動排序"
	L["Turn off Active Sort. Queued pets can then be rearranged and will not automatically reorder themselves.\n\nTo turn Active Sort back on, check %sActive Sort\124r in the Queue menu."] = "關閉主動排序。允許手動排列等候的寵物，而且不會自動調整順序。\n\n要重新打開主動排序，請按下等候區選單中的 %s主動排序\124r。"
	L["Turn Off Active Sort?"] = "是否要關閉主動排序?"
	L["Leveling Pets: %s%s"] = "升級中寵物: %s%s"
	L["Active Sort:"] = "主動排序:"
	L["Add these pets to the queue?"] = "是否要將這些寵物加入到等候區?"
	L["This will add %s%d\124r pets to the leveling queue.\n\nYou can be more selective by filtering pets.\n\nFor instance, if you filter pets to High Level (15-24) and Rare, Fill Queue will only add rare pets between level 15 and 24."] = "將 %s%d\124r 寵物加入到等候區。\n\n使用過濾方式來選擇要加入的寵物。\n\n舉例來說，如果過濾方式是高等級 (15-24) 和稀有，那麼只有等級15到24的稀有寵物才會加入等候區。"
	L["This will add %s%d\124r pets to the leveling queue."] = "將 %s%d\124r 寵物加入到升級等候區。"

-- Panels\MiniQueue.lua

-- Panels\MiniPanel.lua
	L["This target has a saved team"] = "對手有已儲存的隊伍"

-- Panels\OptionPanel.lua
	L["All Options"] = "所有選項"
	L["Targeting Options"] = "對手選項"
	L["Auto load upon targeting only, not mouseover.\n\n\124cffff4040WARNING!\124r This is not recommended! It can be too late to load pets if you target with right click!"] = "只有選取為對手時才自動載入，滑鼠指向不載入。\n\n\124cffff4040警告!\124r 不建議使用! 如果用滑鼠右鍵來選取為對手，會來不及載入寵物。"
	L["Always Show When Targeting"] = "選取對手時總是顯示"
	L["Regardless whether a target's team is already loaded, show the Rematch window when you target something with a saved team."] = "不論是否已經載入對手的隊伍，選取的對手有已儲存的隊伍時，顯示戰寵送作隊視窗。"
	L["Preferred Window Mode"] = "偏好的視窗模式"
	L["Minimized Standalone"] = "小型獨立視窗"
	L["When automatically showing the Rematch window, show the minimized standalone window."] = "自動顯示戰寵送作隊視窗時，顯示小型獨立視窗。"
	L["Maximized Standalone"] = "大型獨立視窗"
	L["When automatically showing the Rematch window, show the maximized standalone window."] = "自動顯示戰寵送作隊視窗時，顯示大型獨立視窗。"
	L["Pet Journal"] = "寵物日誌"
	L["When automatically showing the Rematch window, show the pet journal."] = "自動顯示戰寵送作隊視窗時，顯示寵物日誌。"
	L["Standalone Window Options"] = "獨立視窗選項"
	L["Use Custom Scale"] = "使用自訂縮放大小"
	L["Change the relative size of the standalone window to anywhere between 50% and 200% of its standard size."] = "更改獨立視窗的相對大小，介於標準大小的50%與200%之間。"
	L["Single Panel Mode"] = "單一面板模式"
	L["Collapse the maximized standalone window to one panel instead of two side by side.\n\nUsers of earlier versions of Rematch may find this mode more familiar."] = "收合大型獨立視窗，使用單一而不是兩個相鄰的面板。\n\n戰寵送作隊早期版本的使用者會對這個模式比較熟悉。"
	L["Combine Pets And Queue"] = "合併寵物和等候區"
	L["In single panel mode, combine the Pets and Queue tabs together. A narrow queue will display to the right of the pet list instead of in a separate tab."] = "在單一面板模式中，合併寵物和等候區標籤頁。較窄的等候區會顯示在寵物清單的右方，而不是另一個分開的標籤頁。"
	L["Keep Window On Screen"] = "保持顯示視窗"
	L["Don't hide the standalone window when the ESCape key is pressed or most other times it would hide, such as going to the game menu."] = "按下 Esc 鍵或其他可能隱藏視窗的時候，都不要隱藏獨立視窗，例如開啟遊戲選單。"
	L["Even For Pet Battles"] = "寵物對戰時也要顯示"
	L["Keep the standalone window on the screen even when you enter pet battles."] = "寵物對戰時也保持顯示獨立視窗。"
	L["Even Across Sessions"] = "下次登入時也要顯示"
	L["If the standalone window was on screen when logging out, automatically summon it on next login."] = "如果登出時有顯示獨立視窗，下次登入時也要自動顯示。"
	L["Don't Minimize With ESC Key"] = "按Esc時不要最小化"
	L["Don't minimize the standalone window when the ESCape key is pressed."] = "按下Esc鍵時不要最小化獨立視窗。"
	L["Lower Window Behind UI"] = "顯示在UI下方"
	L["Push the standalone window back behind other parts of the UI so other parts of the UI can appear ontop."] = "將視窗顯示在其他UI介面的下方，讓其他UI顯示在上面。"
	L["Move Panel Tabs To Right"] = "面板標籤頁移動至右側"
	L["Align the Pets, Teams, Queue and Options tabs to the right side of the standalone window."] = "將寵物、隊伍、等候區和選項標籤頁對齊到獨立視窗的右側。"
	L["Minimal Minimized Window"] = "最小化小型視窗"
	L["Remove the titlebar and tabs when the standalone window is minimized."] = "獨立視窗最小化時，不要顯示標題列和標籤頁。"
	L["Appearance Options"] = "外觀選項"
	L["Compact List Format"] = "小型清單格式"
	L["Use an alternate style of lists for Pets, Teams and Queue to display more on the screen at once.\n\n\124cffff4040This option requires a Reload."] = "使用另一種清單樣式來顯示寵物、隊伍和等候區，讓畫面上一次可以顯示更多項目。\n\n\124cffff4040需要重新載入介面。"
	L["Use Smaller Text Too"] = "同時使用較小的文字"
	L["Also use smaller text in the Compact List Format so more text displays on each button."] = "在小型清單格式中同時也使用較小的文字，讓每個按鈕可以顯示更多文字。"
	L["Color Pet Names By Rarity"] = "寵物名字依據稀有程度著色"
	L["Make the names of pets you own the same color as its rarity. Blue for rare, green for uncommon, etc."] = "讓你所擁有的寵物名字顏色和牠的稀有程度相同。稀有是藍色、精良是綠色...等等。"
	L["Hide Rarity Borders"] = "隱藏稀有程度邊框"
	L["Don't color the icon border for pets you own in the same color as its rarity."] = "你所擁有寵物的圖示外框，不要使用和稀有程度相同的顏色。"
	L["Hide Level At Max Level"] = "最高等級時隱藏等級"
	L["If a pet is level 25, don't show its level on the pet icon."] = "如果寵物的等級是25，寵物圖示不要顯示等級。"
	L["Show Ability Numbers"] = "顯示技能數字"
	L["In the ability flyout, show the numbers 1 and 2 to help with the common notation such as \"Pet Name 122\" to know which abilities to use."] = "對於選中的技能，顯示數字 1 和 2 以方便識別使用的是哪個技能。例如 \"寵物名字 122\""
	L["Toolbar Options"] = "工具列選項"
	L["Move Toolbar To Bottom"] = "工具列移動至下方"
	L["Move the toolbar buttons (Revive Battle Pets, Battle Pet Bandages, Safari Hat, etc) to the bottom of the standalone window.\n\nAlso convert the red panel buttons (Save, Save As, Find Battle) to toolbar buttons."] = "將工具列按鈕 (復活戰寵、戰寵繃帶、狩旅團之帽...等等) 移動到獨立視窗的下方。\n\n同時將紅色面板按鈕 (儲存、另存為、尋找對戰) 顯示為工具列按鈕。"
	L["Reverse Toolbar Buttons"] = "反向排列工具列按鈕"
	L["Reverse the order of the toolbar buttons (Revive Battle Pets, Battle Pet Bandages, Safari Hat, etc)."] = "反向排列工具列按鈕的順序 (復活戰寵、戰寵繃帶、狩旅團之帽...等等)。"
	L["Hide On Toolbar Right Click"] = "滑鼠右鍵點擊工具列時隱藏"
	L["When a toolbar button is used with a right click, dismiss the Rematch window after performing its action."] = "使用滑鼠右鍵點工具列按鈕時，執行按鈕動作後關閉戰寵送作隊視窗。"
	L["Safari Hat Reminder"] = "提醒使用狩旅團之帽"
	L["Draw attention to the safari hat button while a pet below max level is loaded.\n\nAlso show the Rematch window when a low level pet loads and the safari hat is not equipped."] = "載入不是最高等級的寵物時，明顯顯示狩旅團之帽按鈕。\n\n同時在沒有裝備狩旅團之帽並且載入低等寵物時，顯示戰寵送作隊視窗。"
	L["Pet Card & Notes Options"] = "寵物卡 & 註記選項"
	L["Allow Pet Cards To Be Pinned"] = "允許固定寵物卡"
	L["When dragging a pet card to another part of the screen, pin the card so all future pet cards display in the same spot, until the pet card is moved again or the unpin button is clicked."] = "將寵物卡拖曳到畫面上的另一個位置後，固定住寵物卡，讓所有想要看的寵物卡都能夠一次顯示。直到再次移動寵物卡，或是按下取消固定的按鈕。"
	L["Click For Pet Cards & Notes"] = "點擊顯示寵物卡 & 註記"
	L["Instead of automatically showing pet cards and notes when you mouseover them, require clicking the pet or notes button to display them."] = "滑鼠點擊寵物和註記按鈕時顯示寵物卡和註記，而不是滑鼠指向。"
	L["Faster Pet Cards & Notes"] = "快速顯示寵物卡 & 註記"
	L["Instead of a small delay before showing pet cards and notes, immediately show them as you mouseover pets and notes buttons."] = "滑鼠指向寵物和註記按鈕時立即顯示寵物卡和註記，不要有短暫的延遲。"
	L["Use Pet Cards In Battle"] = "對戰中使用寵物卡"
	L["Use the pet card on the unit frames during a pet battle instead of the default tooltip."] = "對戰時在單位框架顯示寵物卡，取代預設的提示說明。"
	L["Use Pet Cards For Links"] = "名稱連結使用寵物卡"
	L["Use the pet card when viewing a link of a pet someone else sent you instead of the default link."] = "檢視其他人所貼的寵物連結時顯示寵物卡，取代預設的連結說明。"
	L["Show Team Cards"] = "顯示隊伍卡"
	L["Show a card with team details when you mouseover a team.\n\n%sIMPORTANT:\124r While this option is enabled, clicking a team will lock the team card instead of loading it. %sDouble-Click\124r to load a team with this option enabled, just as you would Double-Click a pet to summon it."] = "滑鼠指向隊伍時，顯示包含隊伍詳細資訊的卡片。\n\n%s特別注意:\124r 啟用這個選項時，滑鼠點一下隊伍將會鎖定隊伍卡片而不是載入隊伍。%s點兩下\124r隊伍才會將它載入，就如同點兩下寵物會召喚它一樣。"
	L["Keep Notes On Screen"] = "保持顯示註記"
	L["Don't hide notes when the ESCape key is pressed or other times it would hide, such as changing tabs or closing Rematch."] = "按下Esc鍵或其他會隱藏註記的時候，不要隱藏註記。例如切換標籤頁或關閉戰寵送作隊。"
	L["Show Notes Upon Targeting"] = "顯示對手的註記"
	L["When your target has a saved team with notes, automatically display and lock the notes."] = "選擇的對手有已經儲存的隊伍和註記時，自動顯示並且鎖定註記。"
	L["Show Notes In Battle"] = "對戰中顯示註記"
	L["If the loaded team has notes, display and lock the notes when you enter a pet battle."] = "如果載入的隊伍有註記，進入寵物對戰時顯示並且鎖定註記。"
	L["Only Once Per Team"] = "每個隊伍只顯示一次"
	L["Only display notes automatically the first time entering battle, until another team is loaded."] = "只有第一次進入對戰時自動顯示註記，直到載入下一個隊伍。"
	L["Alternate Lore Font"] = "較大的知識文字"
	L["Use a more normal-looking font for lore text on the back of the pet card."] = "寵物卡背面的寵物知識文字使用較大的字體。"
	L["Team Options"] = "隊伍選項"
	L["Hide Targets Below Teams"] = "隱藏隊伍下方的對手"
	L["Hide the target name that appears beneath a team that is not named the same as its target."] = "隱藏出現在隊伍下方、和對手不同的名稱。"
	L["Always Show Team Tabs"] = "總是顯示隊伍標籤頁"
	L["Show team tabs along the right side of the window even if you're not on the team panel."] = "就算不是隊伍面板，視窗右側仍然要顯示隊伍標籤頁。"
	L["Move Team Tabs To Left"] = "隊伍標籤頁移動至左側"
	L["Move the team tabs along the right side of the standalone window to the left side."] = "將獨立視窗右側的隊伍標籤頁移動至左側。"
	L["Auto Track Win Record"] = "自動儲存勝利記錄"
	L["At the end of each battle, automatically record whether the loaded team won or lost.\n\nForfeits always count as a loss.\n\nYou can still manually update a team's win record at any time."] = "每場對戰結束後，載入的隊伍無論輸贏，都會自動記錄結果。\n\n棄權一定算是戰敗。\n\n你仍然可以在任何時候手動更新隊伍的勝利記錄。"
	L["For PVP Battles Only"] = "只記錄PVP對戰"
	L["Automatically track whether the loaded team won or lost only in a PVP battle and never for a PVE battle."] = "只有在每場PVP(與玩家)對戰結束後，載入的隊伍無論輸贏，都會自動記錄結果。不記錄PVE對戰。"
	L["Display Total Wins Instead"] = "顯示勝利次數"
	L["Instead of displaying the win percentage of a team on the win record button, display the total number of wins.\n\nTeam tabs that are sorted by win record will sort by total wins also."] = "勝利記錄按鈕顯示隊伍勝利的總次數，而不是百分比。\n\n依據勝利記錄排序的隊伍標籤頁，也會依據勝利總次數排序。"
	L["Hide Win Record Buttons"] = "隱藏勝利記錄按鈕"
	L["Hide the win record button displayed to the right of each team.\n\nYou can still manually edit a team's win record from its right-click menu and automatic tracking will continue if enabled."] = "隱藏隊伍右方的勝利記錄按鈕。你仍然可以從滑鼠右鍵選單中編輯隊伍的勝利記錄。如果有啟用自動儲存功能，仍會持續記錄。"
	L["Leveling Queue Options"] = "升級等候區選項"
	L["Prefer Living Pets"] = "偏好活的寵物"
	L["When loading pets from the queue, skip dead pets and load living ones first."] = "從等候區載入寵物時，跳過已死亡的寵物，優先載入活生生的。"
	L["And At Full Health"] = "和生命力全滿的寵物"
	L["Also prefer uninjured pets when loading pets from the queue."] = "從等候區載入寵物時，也要優先載入沒有受傷的寵物。"
	L["Double Click To Send To Top"] = "點兩下排列至最上方"
	L["When a pet in the queue panel is double clicked, send it to the top of the queue instead of summoning it."] = "在等候區的面板點兩下寵物時，將牠傳送到等候區的最上方，而不是召喚。"
	L["Hide Leveling Pet Toast"] = "隱藏升級中寵物的烤焦麵包"
	L["Don't display the popup 'toast' when a new pet is automatically loaded from the leveling queue."] = "自動從升級等候區載入新寵物時，不要顯示彈出的 '烤焦麵包'。"
	L["Automatically Level New Pets"] = "自動升級新寵物"
	L["When you capture or learn a pet, automatically add it to the leveling queue."] = "捕獲或學會寵物時，自動加入到升級等候區。"
	L["Only Pets Without A 25"] = "無一等級25的寵物限定"
	L["Only automatically level pets which don't have a version already at 25 or in the queue."] = "相同寵物中沒有任何一個等級25或在等候區中，才要自動升級寵物。"
	L["Only Rare Pets"] = "稀有寵物限定"
	L["Only automatically level rare quality pets."] = "僅自動升級稀有品級的寵物。"
	L["Pet Filter Options"] = "寵物過濾方式選項"
	L["Reset Filters On Login"] = "登入時重置過濾方式"
	L["When logging in, start with all pets listed and no filters active."] = "登入時，所有寵物列表都沒有預設啟用的過濾方式。"
	L["Reset Sort With Filters"] = "重置過濾時也重新排序"
	L["When clearing filters, also reset the sort back to the default: Sort by Name, Favorites First."] = "清除過濾方式時也一併將排序重置為預設值: 依照名字、最愛優先排序。"
	L["Don't Reset Search With Filters"] = "重置過濾時不清除搜尋框"
	L["When manually clearing filters, don't clear the search box too.\n\nSome actions, such as logging in or Find Similar, will always clear search regardless of this setting."] = "手動清除過濾方式時，不要清除搜尋框。\n\n某些動作，例如登入或搜尋類似，總是會清除搜尋框，無視於這個設定。"
	L["Sort By Chosen Name"] = "使用自己取的名稱排序"
	L["When pets are sorted by name, sort them by the name given with the Rename option instead of their original name."] = "寵物的排序方式為名稱時，使用透過重新命名選項所取的名稱來排序，而不是原始的名稱。"
	L["Miscellaneous Options"] = "其他選項"
	L["Show After Pet Battle"] = "寵物對戰結束後顯示"
	L["Show the Rematch window after leaving a pet battle."] = "升級寵物的對戰結束後顯示戰寵送作隊視窗。"
	L["Disable Sharing"] = "停用分享"
	L["Disable the Send button and also block any incoming pets sent by others. Import and Export still work."] = "停用傳送按鈕，也會阻擋其他玩家傳送過來的任何寵物。匯出和匯入仍能正常使用。"
	L["Don't display a popup when a team loads and a pet within the team can't be found."] = "載入的隊伍中無法找到的寵物時，不要顯示彈出訊息。"
	L["Don't ask for confirmation when hiding a pet.\n\nYou can view hidden pets in the 'Other' pet filter."] = "隱藏寵物時不要詢問。\n\n在 '其他' 寵物過濾方式中可以看到隱藏的寵物。"
	L["Use Minimap Button"] = "使用小地圖按鈕"
	L["Place a button on the minimap to toggle Rematch and load favorite teams."] = "在小地圖旁放置一個按鈕，可供切換顯示寵物送作隊和載入最愛的隊伍。"
	L["Keep Companion"] = "保持作伴的寵物"
	L["After a team is loaded, summon back the companion that was at your side before the load; or dismiss the pet if you had none summoned."] = "隊伍載入後，將原本在身邊作伴的寵物重新召喚回來，若身邊原本沒有寵物，就解散寵物。"
	L["Hide Tooltips"] = "隱藏滑鼠提示"
	L["Hide the more common tooltips in Rematch."] = "隱藏戰寵送作隊一般的滑鼠提示。"
	L["Hide Extra Help"] = "隱藏進階說明"
	L["Hide the informational \"Help\" items found in many menus and on the pet card."] = "隱藏多種選單和寵物卡的資訊型 \"說明\"。"
	L["Use Default Pet Journal"] = "使用預設的寵物日誌"
	L["Turn off Rematch integration with the default pet journal.\n\nYou can still use Rematch in its standalone window, accessed via key binding, /rematch command or from the Minimap button if enabled in options."] = "關閉戰寵送作隊和預設寵物日誌整合的功能。\n\n仍然可以透過綁定的按鍵、指令 /rematch 和小地圖按鈕 (選項中有啟用時) 來使用獨立視窗的戰寵送作隊。"
	L["Rematch version %s"] = "Rematch 版本 %s"
	L["The%s icon indicates new options."] = "%s 圖示代表新的選項。"
	L["Anchor"] = "位置"
	L["Bottom Right"] = "右下"
	L["Top Right"] = "右上"
	L["Bottom Left"] = "左下"
	L["Top Left"] = "左上"
	L["Anchor: %s"] = "位置: %s"
	L["When the standlone window is minimized, send it to the %s corner."] = "獨立視窗最小化時，縮小至%s角。"
	L["Current Scale: %d%%"] = "目前縮放大小: %d%%"
	L["Click here to choose a different scale for the standalone window."] = "點這裡替獨立視窗選擇不同的縮放大小。"
	L["\n\n%sThis will close the journal and open the standalone window."] = "\n\n%s會關閉日誌並開啟獨立視窗。"
	L["Reload the UI now?"] = "是否要立即重新載入介面?"
	L["You've chosen to change the setting for Compact List Format.\n\nThis change doesn't take effect until a reload or logout."] = "你已經選擇要更改小型清單格式的設定。\n\n必須重新載入或登出，這項變更才會生效。"
	L["Custom Scale"] = "自訂縮放大小"
	L["Keep this scale?"] = "是否要保留這個縮放大小?"
	L["This scale determines the relative size of the standalone window, where 100% is the standard size."] = "將會偵測獨立視窗的相對大小來縮放，100%是標準的大小。"
	L["Show Species ID On Pet Cards"] = "顯示寵物種類ID"
	L["Display the numerical species ID of a pet as a stat on their pet card."] = "在寵物卡屬性的位置顯示寵物種類ID數字。"

-- Widgets\BottomPanel.lua
	L["You can also double-click a pet to summon or dismiss it."] = "也可以點兩下來召喚或解散寵物。"
	L["Disable Rematch"] = "停用寵物送作隊"
	L["Uncheck this to restore the default pet journal.\n\nYou can still use Rematch in its standlone window, accessed via key binding, /rematch command or from the Minimap button if enabled in options."] = "取消打勾恢復成預設的寵物日誌。\n\n仍然可以在獨立視窗中使用寵物送作隊，透過綁定的按鍵、/rematch 指令或小地圖按鈕 (有啟用的話) 來開啟。"

-- Widgets\TeamTabs.lua
	L["Edit Tab"] = "編輯標籤頁"
	L["Change the name or icon of this tab."] = "更改這個標籤頁的名稱或圖示。"
	L["Custom Sort"] = "自訂排序"
	L["Remove Custom Sort"] = "移除自訂排序"
	L["Are you sure you want to remove the custom sort order?\n\nThe saved order of teams will be lost and turning this option back on will not restore the old order."] = "是否確定要移除自訂排序?\n\n將會失去已經儲存的隊伍順序，再次將這個選項啟用也無法恢復原有的順序。"
	L["While checked, you can rearrange the order of teams within this tab from the teams' right-click menu."] = "啟用時，可以從隊伍的滑鼠右鍵選單來重新排列這個標籤頁中的隊伍。"
	L["Sort By Wins"] = "依勝利次數排序"
	L["This option is disabled while Custom Sort is active."] = "啟用自訂排序時，這個選項會被停用。"
	L["Sort teams in this tab by their wins.\n\nFavorited teams will still list at the top."] = "將這個標籤頁中的隊伍依據勝利次數排序。\n\n最愛的隊伍仍會顯示在最上方。"
	L["Set leveling preferences for all teams within this tab.\n\nIf a team within this tab also has preferences, the tab's preferences will take priority over the team's preferences."] = "為這個標籤頁中的所有隊伍設定升級偏好設定。\n\n當標籤頁本身也有偏好設定時，標籤頁的偏好設定會優先於隊伍偏好設定。"
	L["Export Tab"] = "匯出標籤頁"
	L["Export all teams in this tab to a string you can copy elsewhere, such as forums or emails.\n\nOther Rematch users can then paste these teams into their Rematch via Import Teams.\n\nYou can export a single team by right-clicking one and choosing its Share menu."] = "將標籤頁中的所有隊伍匯出成純文字，以便複製到其他地方，例如討論區或電子郵件。\n\n已經使用戰寵送作隊的玩家可以透過匯入隊伍的功能，將這個隊伍貼入。\n\n要匯出單一隊伍，在隊伍上點滑鼠右鍵，選擇分享選單。"
	L["Delete Tab"] = "刪除標籤頁"
	L["Delete this tab and move all of its teams to the default tab."] = "刪除這個標籤頁，將裡面的所有隊伍移動至預設標籤頁。"
	L["Create New Tab"] = "建立新的標籤頁"
	L["Teams: %d"] = "隊伍: %d"
	L["New Tab"] = "新標籤頁"
	L["Choose a name and icon"] = "選擇名稱和圖示"
	L["Delete this tab?"] = "是否確定要刪除這個標籤頁?"
	L["Deleting this tab will move its teams to the %s tab."] = "刪除標籤頁會將裡面的隊伍移動至 %s 標籤頁。"

-- Widgets\LoadedTeamPanel.lua
	L["Reload Team"] = "重新載入隊伍"
	L["When a team is loaded its name goes here. You can reload the team by clicking here or right-click for team options such as setting notes."] = "隊伍載入後會在這裡顯示隊伍名稱。點擊這裡可以重新載入隊伍，或點滑鼠右鍵顯示隊伍選項，例如設定註記。"
	L["Last Loaded Team"] = "上次載入的隊伍"

-- Dialogs\Save.lua
	L["Target For This Team"] = "這個隊伍的對手"
	L["A target stored in a team is used to decide which team to load when you return to that target.\n\nYou can save an unlimited number of teams to fight a target, but a target can only be saved in one team."] = "再次和遇到對手時，會使用隊伍中所儲存的對手來決定要載入哪個隊伍。\n\n每個隊伍只能儲存一個對手，但可以儲存無限數量的隊伍與同一個對手對戰。"
	L["Save As.."] = "另存為..."
	L["Save this team?"] = "是否要儲存這個隊伍?"
	L["Save Notes & Preferences Too"] = "同時同時儲存註記和偏好設定"
	-- L["Save Without Leveling Slots"] = "儲存時不保留升級欄位"
	L["All teams must have a name."] = "所有隊伍都必須要有名稱。"
	L["This target already has a team."] = "這個對手已經有隊伍。"
	L["A team already has this name."] = "已經有隊伍使用這個名稱。"
	L["Overwrite Team"] = "覆蓋隊伍"
	L["Overwrite this team?"] = "是否確定要覆蓋這個隊伍?"
	L["The target %s%s\124r already has a team.\n\nA target can only have one team."] = "對手 %s%s\124r 已經有隊伍。\n\n一個對手只能有一個隊伍。"
	L["A team named %s%s\124r already exists.\n\nTeams without a target must have a unique name."] = "%s%s\124r 隊伍名稱被使用。\n\n沒有對手的隊伍名稱不能重複。"

-- Dialogs\Preferences.lua
	L["Minimum Health"] = "最低生命力值"
	L["This is the minimum health preferred for a leveling pet.\n\nThe queue will prefer leveling pets with at least this much health (adjusted by expected damage taken if any chosen)."] = "升級寵物的最低生命力偏好設定。\n\n等候區升級的寵物生命力至少必須達到最低標準 (能適應選取對手的預期傷害)。"
	L["Minimum Level"] = "最低等級"
	L["This is the minimum level preferred for a leveling pet.\n\nLevels can be partial amounts. Level 4.33 is level 4 with 33% xp towards level 5."] = "升級寵物的最低等級偏好設定。\n\n等級可以有小數點，等級 4.33 代表等級 4 和 33% 經驗值到等級 5。"
	L["Maximum Health"] = "最高生命力值"
	L["This is the maximum health preferred for a leveling pet."] = "升級寵物的最高生命力偏好設定。"
	L["Maximum Level"] = "最高等級"
	L["This is the maximum level preferred for a leveling pet.\n\nLevels can be partial amounts. Level 23.45 is level 23 with 45% xp towards level 24."] = "升級寵物的最高等級偏好設定。\n\n等級可以有小數點，等級 23.45 代表等級 23 和 45% 經驗值到等級 24。"
	L["Or any"] = "或任何"
	L["Allow low-health Magic and Mechanical pets to ignore the Minimum Health, since their racials allow them to often survive a hit that would ordinarily kill them."] = "允許低生命力的魔法和機械寵物忽略最低生命力值，因為種族技能讓它們在受到致命的一擊後常常還能生存下來。"
	L["Expected Damage Taken"] = "預期受到的傷害"
	L["Tab"] = "標籤頁"
	L["Leveling Preferences"] = "升級偏好設定"
	L["Team Preferences"] = "隊伍偏好設定"
	L["Tab Preferences"] = "標籤頁偏好設定"
	L["  For %s pets: %s%d%s"] = " - %s 個寵物: %s%d%s"
	L["%s %sTab Preferences"] = "%s %s標籤頁偏好設定"
	L["%s%s Preferences Paused"] = "已暫停 %s%s 偏好設定"
	L["%s Resume Preferences"] = "%s 恢復偏好設定"
	L["%s Pause Preferences"] = "%s 暫停偏好設定"
	L["Leveling Preferences For %s:"] = "%s的升級偏好設定:"
	L["Expected damage taken"] = "預期受到的傷害"
	L["The minimum health of pets can be adjusted by the type of damage they are expected to receive."] = "根據預期受到的傷害類型，寵物所能適應的最低生命力值。"
	L["Damage expected"] = "預期傷害"
	L["  For %s pets: \124cffffd200%d"] = " - %s 個寵物: \124cffffd200%d"

-- Dialogs\Sideline.lua
	L["New Team"] = "新隊伍"

-- Dialogs\Share.lua
	L["%s (NPC#%d)"] = nil
	L["%s (%s NPC#%d)"] = nil
	L["%d: %s"] = nil
	L["%d: %s (%d,%d,%d)"] = nil
	L["Preferred leveling pets: %s."] = nil
	L["at least %d health"] = nil
	L["at least %d health (or any Magic/Mechanical)"] = nil
	L["at least %d health (%s damage expected)"] = nil
	L["at least %d health (or any Magic/Mechanical, %s damage expected)"] = nil
	L["at most %d health"] = nil
	L["at least level %s"] = nil
	L["at most level %s"] = nil
	L["Export Team"] = "匯出隊伍"
	L["Press Ctrl+C to copy these teams to the clipboard."] = "按下 Ctrl+C 將這些隊伍複製到剪貼簿。"
	L["Press Ctrl+C to copy this team to the clipboard."] = "按下 Ctrl+C 將這個隊伍複製到剪貼簿。"
	L["Include Preferences"] = "包含偏好設定"
	L["Include Notes"] = "包含註記"
	L["Press Ctrl+V to paste a team from the clipboard."] = "按下 Ctrl+V 從剪貼簿貼上隊伍。"
	L["This is not a recognizable team."] = "無法辨識隊伍。"
	L["An existing team already has this %s."] = "已經有隊伍使用這個 %s。"
	L["target"] = "對手"
	L["name"] = "名稱"
	L["Create a new copy"] = "建立新的複製"
	L["Overwrite existing team"] = "覆蓋已有的隊伍"
	L["%s%d\124r teams are in this import."] = "此次匯入 %s%d\124r 個隊伍。"
	L["%s%d\124r have a name or target already used."] = "%s%d\124r 已有名稱，或對手已經被使用。"
	L["Create new copies"] = "建立新的複製"
	L["Overwrite existing teams"] = "覆蓋已有的隊伍"
	L["Send"] = "傳送"
	L["Who do you want to send this team to?"] = "要將隊伍傳送給誰?"
	L["Sending..."] = "正在傳送..."
	L["No response. Lag or they don't have Rematch?"] = "沒有回應，網路延遲或對方沒有使用戰寵送作隊?"
	L["Team successfully received!"] = "已經成功的接收隊伍!"
	L["Sending...%d%%"] = "正在傳送...%d%%"
	L["They're busy. Try again later."] = "對方忙碌中，請稍後再試。"
	L["They're in combat. Try again later."] = "對方對戰中，請稍後再試。"
	L["They have team sharing disabled."] = "對方停用分享功能。"
	L["Incoming Rematch Team!"] = "有戰寵送作隊隊伍傳送進來!"
	L["%s%s\124r has sent you a team named \"%s\" (for %s)."] = "%s%s\124r 傳送給你一個隊伍，名稱為 \"%s\" (對手是 %s)。"
	L["%s%s\124r has sent you a team for %s."] = "%s%s\124r 傳送給你一個隊伍，對手是 %s。"
	L["%s%s\124r has sent you a team named \"%s\"."] = "%s%s\124r 傳送給你一個隊伍，名稱為 \"%s\"。"
	L["Import these teams?"] = "是否要匯入隊伍?"
	L["Import"] = "匯入"
	L["%s%d\124r Rematch teams have the same name."] = "%s%d\124r 的戰寵送作隊已經有相同的隊伍名稱。"
	L["Please Wait..."] = "請稍後..."
	L["Press Ctrl+C to copy these teams to the clipboard. Then paste them into an email to yourself or a text file someplace safe.\n\nIf you ever need to restore your teams, paste them back in with Import Teams."] = "按下 Ctrl+C 將這些隊伍複製到剪貼簿。然後便可以貼入到電子郵件中寄送給自己，或是貼入到文字檔案中，放到在某個安全的地方。\n\n當日後需要恢復隊伍時，再貼回到匯入隊伍的功能中。"

-- Dialogs\Tooltip.lua

-- Dialogs\ScriptFilter.lua
	L["Pet Variables"] = "寵物變數"
	L["Exposed API"] = "公開的 API"
	L["Test"] = "測試"
	L["line "] = "行 "
	L["Pet Filter Script Error"] = "寵物過濾方式腳本程式發生錯誤"
	L["Error in %s"] = "發生錯誤於 %s"
	L["\124TInterface\\RaidFrame\\ReadyCheck-NotReady:16\124t Error %s"] = nil
	L["\124TInterface\\RaidFrame\\ReadyCheck-Ready:16\124t Script ran without errors!"] = nil

-- Dialogs\Collection.lua
	L["Total Collected Pets"] = "全部收集的寵物"
	L["Unique Collected Pets"] = "收集的不重複寵物"
	L["Pets Not Collected"] = "尚未收集的寵物"
	L["Percent Collected"] = "收集百分比"
	L["Max Level Pets"] = "滿等的寵物"
	L["Rare Quality Pets"] = "稀有品級寵物"
	L["Unique Pets In The Game"] = "遊戲中的不重複寵物"
	L["Collection Statistics"] = "收藏統計"
	L["There are %s%d\124r unique pets in the game."] = "遊戲中的不重複寵物有 %s%d\124r 個。"
	L["Pets Collected"] = "已收集的寵物"
	L["Pets At Max Level"] = "滿等的寵物"
	L["Total"] = "全部"
	L["Unique"] = "不重複"
	L["Duplicate Collected Pets"] = "重複收集的寵物"
	L["Average Battle Pet Level"] = "戰寵平均等級"
	L["You have %s%.1f%%\124r of all unique pets."] = "全部的不重複寵物中，你有 %s%.1f%%\124r。"
	L["All unique pets in the game."] = "遊戲中的所有不重複寵物。"
	L["All pets you've collected, including duplicates."] = "你所收集的所有寵物，包含重複的。"
	L["The unique pets you've collected, not including duplicates."] = "你所收集的不重複寵物，不包含重複的。"
	L["The unique pets you're missing."] = "你還沒有的不重複寵物。"
	L["How much of each category's unique pets you've collected as a percent."] = "你在每個類別所收集的不重複寵物百分比。"
	L["All of your level 25 pets, including duplicates."] = "所有等級25的寵物，包含重複的。"
	L["All of your rare quality pets, including duplicates."] = "所有稀有品質的寵物，包含重複的。"
	L["Pet Types"] = "寵物類型"
	L["Sources"] = "來源"
	
-- Frames\Frame.lua
	L["Pets"] = "寵物"
	L["Options"] = "選項"
	L["Toggle Single Panel Mode"] = "開啟/關閉單一視窗模式"
	L["Toggle between one panel or two panels side by side."] = "在單一面板和雙面板之間作切換。"

-- Frames\Configure.lua

-- Frames\Journal.lua
	L["Enable Rematch"] = "啟用戰寵送作隊"
	L["Check this to use Rematch in the pet journal."] = "啟用這個選項，在寵物日誌中使用戰寵送作隊。"

-- Frames\Battle.lua

-- Process\Battle.lua
	L["Show Pet Card"] = "顯示寵物卡"

-- Process\Breeds.lua
	L["NEW"] = "新的"	-- line 72, 76

end
