local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_Oribos", "zhTW", false, true)

if not L then return end
-- Traditional Chinese localization by RainbowUI ( https://www.curseforge.com/members/rainbowui )
if L then
L["Blizzard"] = "遊戲內建"
L["Both"] = "兩個都要"
L["config_auctioneer"] = "拍賣場"
L["config_auctioneer_desc"] = "顯示拍賣場的位置。"
L["config_banker"] = "銀行"
L["config_banker_desc"] = "顯示拍銀行的位置。"
L["config_barber"] = "美容院"
L["config_barber_desc"] = "顯示美容院的位置。"
L["config_easy_waypoints"] = "快速導航"
L["config_easy_waypoints_desc"] = "簡化建立路線導航的方法，只要點一下滑鼠右鍵便能設定導航目的地，CTRL + 右鍵點擊會有更多選項。"
L["config_fmaster_waypoint"] = "鳥點導航"
L["config_fmaster_waypoint_desc"] = "進入樞運之環時，自動導航到鳥點。"
L["config_guildvault"] = "公會銀行"
L["config_guildvault_desc"] = "顯示公會銀行的位置。"
L["config_icon_alpha"] = "圖示透明度"
L["config_icon_alpha_desc"] = "圖示的透明度。"
L["config_icon_scale"] = "圖示大小"
L["config_icon_scale_desc"] = "圖示的縮放大小。"
L["config_innkeeper"] = "旅店"
L["config_innkeeper_desc"] = "顯示旅店的位置。"
L["config_mail"] = "郵箱"
L["config_mail_desc"] = "顯示郵箱的位置。"
L["config_onlymytrainers"] = "只顯示我的專業相關的訓練師和商人"
L["config_onlymytrainers_desc"] = [[
只會影響主要專業的訓練師和商人。

|cFFFF0000注意: 只有兩個主要專業都學會了以後才有效果。|r
]]
L["config_others"] = "其他"
L["config_others_desc"] = "顯示其他所有的地圖探索點。"
L["config_picons"] = "顯示專業圖示:"
L["config_picons_trainer_desc"] = "訓練師顯示專業技能的圖示，而不是訓練師圖示。"
L["config_picons_vendor_desc"] = "商人顯示專業技能的圖示，而不是商人圖示。"
L["config_plugin_desc"] = "在世界地圖和小地圖中顯示奧睿博司的 NPC 和地圖探索點的位置。"
L["config_plugin_name"] = "奧睿博司"
L["config_portal"] = "傳送門"
L["config_portal_desc"] = "顯示傳送門的位置。"
L["config_portaltrainer"] = "傳送門訓練師"
L["config_portaltrainer_desc"] = "顯示法師傳送門訓練師的位置。"
L["config_reforge"] = "護甲強化"
L["config_reforge_desc"] = "顯示護甲強化的位置。"
L["config_restore_nodes"] = "恢復被隱藏的地圖探索點"
L["config_restore_nodes_desc"] = "恢復所有點右鍵選擇隱藏的地圖探索點。"
L["config_restore_nodes_print"] = "所有被隱藏的地圖探索點都已恢復"
L["config_stablemaster"] = "獸欄管理員"
L["config_stablemaster_desc"] = "顯示獸欄管理員的位置。"
L["config_tab_general"] = "一般"
L["config_tab_scale_alpha"] = "大小 / 透明度"
L["config_tpplatform"] = "傳送平台"
L["config_tpplatform_desc"] = "顯示傳送平台的位置。"
L["config_trainer"] = "專業訓練師"
L["config_trainer_desc"] = "顯示專業訓練師的位置。"
L["config_transmogrifier"] = "塑形師"
L["config_transmogrifier_desc"] = "顯示塑形師的位置。"
L["config_travelguide_note"] = "|cFFFF0000*已透過 HandyNotes: TravelGuide 啟動。|r"
L["config_vendor"] = "商人"
L["config_vendor_desc"] = "顯示商人的位置。"
L["config_void"] = "虛空倉庫"
L["config_void_desc"] = "顯示虛空倉庫的位置。"
L["config_waypoint_dropdown"] = "選擇"
L["config_waypoint_dropdown_desc"] = "選擇要使用的導航方式。"
L["config_what_to_display"] = "選擇要顯示什麼"
L["config_what_to_display_desc"] = "這些設定控制要顯示哪類的圖示。"
L["config_zonegateway"] = "區域通道"
L["config_zonegateway_desc"] = "顯示各地圖區域的通道位置。"
L["dev_config_force_nodes"] = "強制顯示地圖點"
L["dev_config_force_nodes_desc"] = "強制顯示所有的地圖探索點，不論職業、陣營或誓盟。"
L["dev_config_show_prints"] = "顯示 print()"
L["dev_config_show_prints_desc"] = "在聊天視窗中顯示 print() 的訊息。"
L["dev_config_tab"] = "開發"
L["handler_context_menu_add_map_pin"] = "設置地圖航點"
L["handler_context_menu_add_tomtom"] = "加入 TomTom"
L["handler_context_menu_addon_name"] = "地圖標記: 奧睿博司"
L["handler_context_menu_hide_node"] = "隱藏這個地圖點"
L["handler_tooltip_data"] = "正在取得資料..."
L["handler_tooltip_quest"] = "解鎖任務"
L["handler_tooltip_requires"] = "需要"
L["handler_tooltip_requires_level"] = "需要玩家等級"
L["Into the Maw"] = "進入淵喉"
L["Mailbox"] = "郵箱"
L["Portal to Orgrimmar"] = "奧格瑪傳送門"
L["Portal to Stormwind"] = "暴風城傳送門"
L["To Keeper's Respite"] = "前往守衛者歇息地"
L["To Ring of Fates"] = "前往命運之環"
L["To Ring of Transference"] = "前往樞運之環"
L["TomTom"] = true
end