local _, T = ...
-- See https://www.townlong-yak.com/addons/venture-plan/localization

local C, z, V, K = GetLocale(), nil
V =
    C == "deDE" and { -- 84/84 (100%)
      "\"… oder nicht. Lies dies besser bis zum Ende.\"", "\"Kapitel 1: Magier müssen in den Nahkampf.\"", "\"Glaubt nicht seinen Lügen! Gleichgewichtsdruiden sind keine Notrationen.\"", "\"Alles geschah wie vorhergesagt.\"", "\"Nichts lief wie erwartet.\"", "\"Schnapp dir den Sieg aus den Klauen der Niederlage!\"", "\"So nah und doch so fern.\"", "\"Das Ergebnis war wie vorhergesagt.\"", "\"Gab es jemals Zweifel?\"", "\"Bei deinem Glück gibt es nur eine Möglichkeit, wie dies endet.\"",
      "%d |4Abenteuer:Abenteuer; verbleibend...", "%d |4Gefährte ist:Gefährten sind; in einer vorläufigen Gruppe.", "%d |4Gefährte ist:Gefährten sind; bereit für Abenteuer.", "%d |4Gruppe:Gruppen; verbleibend...", "(Nahkampf)", "(Fernkampf)", "Eine detaillierte Aufzeichnung eines Abenteuers, das deine Gefährten absolviert haben.", "Abenteuer läuft ab in:", "Abenteuerbericht", "Alle Gefährten sind bereit für Abenteuer.",
      "Gruppe zuweisen", "Vorläufige Gruppe zuweisen", "Wird auch bei Niederlage vergeben.", "Erhöht den Schaden, den der nächstgelegene Verbündete austeilt, für zwei Runden um {1}. Reduziert den vom nächstgelegenen Verbündeten erlittenen Schaden zwei Runden lang um {2}%. Verursacht sich selbst {3} Schaden.", "Überprüfung der Gesundheitsregeneration...", "Lösche alle vorläufigen Gruppen", "Zum Abschließen hier klicken", "Gesundheit der Gefährten hat sich geändert.", "Alle abschließen", "Aktueller Fortschritt: %s",
      "Fluch der Ungewissheit", "Verfluchter Abenteurerführer", "Verfluchter taktischer Leitfaden", "Schwächt alle Feinde und verursacht in jeder der nächsten {2} Runde {1} Schaden. Mehrere Anwendungen dieses Effekts überschneiden sich.", "Schwächt alle Feinde und verursacht in dieser Runde und in jeder der nächsten drei Runden {1} Schaden. Erhöht den Schaden, den der nächstgelegene Gegner erhält, für drei Runden um {2}.", "Besiegt", "Zum Scheitern verurteilter Lauf", "Dauer:", "Gruppe bearbeiten", "In jeder zweiten Runde wird ein zufälliger Feind für {}% seiner maximalen Gesundheit angegriffen.",
      "Wenn diese Mission fehlschlägt, erhält jeder Gefährte %s.", "Wird das erste Mal in Runde %d gewirkt.", "Gefährten XP", "Zukünfte in Betracht gezogen:", "Heilt den nächstgelegenen Verbündeten um {1}. Erhöht den gesamten Schaden, den der nächstgelegene Verbündete erleidet, zwei Runden lang um {2}%.", "In vorläufiger Gruppe - %s", "Eingehende Angriffe:", "Fügt einem zufälligen Feind {} Schaden zu.", "Fügt allen Gegnern in Reichweite {} Schaden zu.", "Fügt allen Gegnern im Nahkampf {} Schaden zu und erhöht den eigenen verursachten Schaden drei Runden lang um 20%.",
      "Nicht genug Anima.", "Es passiert nichts.", "Nicht alle Fähigkeiten wurden berücksichtigt.", "Nicht alle Ergebnisse wurden überprüft.", "Vorläufig:", "Menge: %s", "Verringert in der nächsten Runde den verursachten Schaden aller Gegner um {}%.", "Reduziert den verursachten Schaden aller Gegner für zwei Runden um {}%.", "Reduziert den erlittenen Schaden des nächstgelegenen Verbündeten für zwei Runden um 5000%.", "Verbleibende feindliche Gesundheit: %s",
      "Benötigt einen Gefährten in der Gruppe", "Kommt bald wieder:", "Belohnungen:", "Abenteurer auswählen", "Vorläufige Gruppen losschicken", "Starte das Abenteuer", "Starte bald…", "Ziele:", "Vorläufige zugewiesene Gruppen können bis zum Klicken von \"%s\" geändert werden.", "Teile diese Neulinge vorläufig diesem Abenteuer zu.",
      "Der Leitfaden ist möglicherweise veraltet.", "Der Leitfaden zeigt Dir eine Reihe möglicher Zukünfte. In einigen Fällen endet das Abenteuer mit einem Triumph. In anderen in einem besonders schrecklichen Misserfolg.", "Diese Gefährten wirken sich derzeit auf Deine Truppenstufe aus:", "Impulse:", "Runden überlebt: %s", "Erfasste Runden: %s", "Benutzen: Unterbricht die Berechnung des Leitfadens.", "Benutzen: Lass das Buch die Truppen und Kampftaktiken auswählen.", "Benutzen: Lies den Leitfaden und bestimme das Schicksal deiner Abenteuergruppe.", "Siegreich",
      "Der Sieg konnte nicht garantiert werden.", "Würde gewinnen, wenn in: %s gestartet wird", "Deine Truppenstufe ist die mittlere Stufe deiner Gefährten (%s), abgerundet. Dieser verringert sich nicht, wenn du zusätzliche Gefährten rekrutierst.", "[CD: %dR]",
    }
    or C == "esES" and { -- 84/84 (100%)
      "\"... o no. Mejor lee esta cosa hasta el final.\"", "\"Capítulo 1: Los magos deben ir a melé.\"", "\"¡No te creas sus mentiras! Los druidas equilibrio no son comidas de emergencia\".", "\"Todo salió como se predijo\".", "\"Nada salió como se esperaba\".", "\"¡Has arrebatado la victoria a las fauces de la derrota!\"", "\"Tan cerca y tan lejos.\"", "\"El resultado fue según lo predicho\".", "\"¿Hubo alguna vez alguna duda?\"", "\"Con tu suerte solo hay una forma en la que esto puede acabar\".",
      "%d |4aventura:aventuras; restantes...", "%d |4compañero está:compañeros están; en un grupo provisional.", "%d |4compañero está listo:compañeros están listos; para las aventuras.", "%d |4grupo:grupos; restantes...", "(melé)", "(a distancia)", "Un historial detallado de una aventura completada por tus compañeros.", "La aventura expira en:", "Informe de la aventura", "Todos los compañeros están listos para las aventuras.",
      "Asigna Grupo", "Asigna Grupo Provisional", "Se otorga incluso si los aventureros han sido derrotados.", "Bufa al aliado más cercano, incrementando todo el daño inflingido un {1} y reduciendo todo el daño recibido un {2}% durante dos turnos. Inflinge {3} de daño a si mismo.", "Comprobando la recuperación de la salud...", "Borrar todos los grupos provisionales", "Click para completar", "La salud del compañero ha cambiado.", "Completar todo", "Progreso actual: %s",
      "Maldición de la incertidumbre", "Guía del Aventurero Maldito", "Guía Táctica Maldita", "Pone desvantajas a todos los enemigos, inflingiendo {1} de daño durante cada uno de los siguientes {2} turnos. Este efecto se puede superponer varias veces.", "Pone desvantajas a todos los enemigos, inflingiendo {1} de daño ese turno y durante cada uno de los siguientes tres turnos. Adicionalmente, incrementa todo el daño recibido por el enemigo más cercano en {2} durante tres turnos.", "Derrotado", "Misión condenada", "Duración:", "Editar grupo", "Cada dos turnos, un enemigo aleatorio es atacado por un {}% de su salud máxima.",
      "Fallar esta misión otorga %s a cada compañero.", "Primer lanzamiento durante el turno %d.", "Experiencia de compañero", "Futuros considerados:", "Cura al aliado más cercano en {1}, e incrementa todo el daño recibido por el aliado un {2}% durante dos turnos.", "En el grupo provisional - %s", "Ataques entrantes:", "Inflige {} de daño a un enemigo aleatorio.", "Inflige {} daño a todos los enemigos a distancia.", "Inflige {} de daño a todos los enemigos a melé, e incrementa el daño realizado un 20% durante tres turnos.",
      "Ánima insuficiente", "No hace nada.", "No se han tenido en cuenta todas las habilidades.", "No se han tenido en cuenta todas las posibilidades.", "Resultado Preliminar:", "Cantidad: %s", "Reduce el daño infligo por todos los enemigos {}% durante el siguiente turno.", "Reduce el daño realizado por todos los enemigos un {}% durante dos turnos.", "Reduce el daño recibido por el aliado más cercano un 5000% durante dos turnos.", "Salud enemiga restante: %s",
      "Requiere un compañero en el grupo", "Volverán pronto:", "Recompensas:", "Selecciona aventureros", "Enviar grupos provisionales", "Comienza la aventura", "Comenzará pronto..", "Objetivos:", "Los grupos provisionales pueden ser cambiados hasta que hagas click en %s.", "Asigna estas tropas provisionalmente a la aventura.",
      "La Guía puede estar desactualizada.", "La guía muestra algunos futuros posibles. En unos, la aventura acaba con éxito; en otros, fracasa de una manera particularmente horrible.", "Estos compañeros afectan actualmente a tu nivel de las tropas:", "Ticks:", "Turnos sobrevividos: %s", "Turnos empleados: %s", "Uso: interrumpe las deliberaciones de la guía.", "Uso: deja que el libro seleccione las tropas y las tácticas de la batalla.", "Uso: lee la guía, la cual determinará el destino de tu grupo de aventureros.", "Victorioso",
      "No se puede garantizar la victoria.", "Podría ganar si comienza con un: %s", "El nivel de tus tropas es la mediana de nivel de tus compañeros (%s), redondeando hacia abajo. No disminuye cuando reclutas compañeros adicionales.", "[CD: %dT]",
    }
    or C == "esMX" and { -- 83/84 (98%)
      "\"... o no. Mejor lee esto hasta el final.\" ", "\"Capítulo 1: Los Magos Deben ser Melé.\"", "\"¡No creas en sus mentiras! Los druidas equilibrio no son comida de emergencia.\"", "\"Todo ha ido según lo previsto.\"", "\"Nada salió como se esperaba\".", "\"¡Has arrebatado la victoria a las fauces de la derrota!\"", "\"Tan cerca, y tan lejos.\"", "\"El resultado fue según lo predicho\".", "\"¿Hubo alguna vez alguna duda?\"", "Con tu suerte, esto solo va acabar de una forma.",
      "%d |4aventura:aventuras; restantes...", z, "%d |4seguidor está listo:seguidores están listos; para las aventuras.", "%d |4grupo:grupos; restantes...", "(melé)", "(a distancia)", "Un registro detallado de una aventura completada por tus seguidores.", "La aventura expirará en:", "Informe de la Aventura", "Todos los seguidores están listos para las aventuras.",
      "Asignar Grupo", "Asignar Grupo Provisional.", "Se otorga incluso si los aventureros son derrotados.", "Incrementa el daño inflingido por el aliado más cercano en {1} durante dos turnos. Reduce el daño recibido por el aliado más cercano un {2}% durante dos turnos. Inflinge {3} de daño a si mismo.", "Comprobando la recuperación de la salud...", "Borrar todos los grupos tentativos", "Clic para completar", "La vida del seguidor ha cambiado.", "Completar todo", "Progreso actual: %s",
      "Maldición de la Incertidumbre", "Guía del Aventurero Maldito", "Guía Táctica Maldita", "Pone perjuicios a todos los enemigos, se inflige {1} de daño durante cada uno de los siguientes {2} turnos. Multiples aplicaciones de este efecto se superponen. ", "Pone perjuicios a todos los enemigos, inflingiendo {1} de daño este turno y cada uno de los siguientes tres turnos. Incrementa todo el daño recibido por el enemigo más cercano en {2} durante tres turnos.", "Derrotado", "Misión suicida", "Duración:", "Editar grupo", "En turnos alternos, un enemigo aleatorio es atacado, causándole {}% de su vida máxima.",
      "Fallar esta misión otorga %s a cada seguidor.", "Se lanza por primera vez en el turno %d.", "Experiencia del seguidor.", "Futuros considerados:", "Cura al aliado más cercano por {1}. Incrementa todo el daño recibido por el aliado más cercano un {2}% durante dos turnos.", "En el grupo provisional - %s", "Ataques enemigos:", "Inflige {} de daño a un enemigo aleatorio.", "Inflige {} daño a todos los enemigos a distancia.", "Inflige {} de daño a todos los enemigos a melé, e incrementa el daño realizado un 20% durante tres turnos.",
      "Ánima insuficiente", "No hace nada.", "No se han tenido en cuenta todas las habilidades.", "No se han tenido en cuenta todas las posibilidades.", "Resultado Preliminar:", "Cantidad: %s", "Reduce el daño infligo por todos los enemigos {}% durante el siguiente turno.", "Reduce el daño de todos los enemigos en {}% por dos turnos.", "Reduce el daño recibido por el aliado más cercano un 5000% durante dos turnos.", "Salud enemiga restante: %s",
      "Requiere un compañero en el grupo", "Volverán pronto:", "Recompensas:", "Selecciona compañeros", "Enviar grupos provisionales", "Comienza la aventura", "Iniciando... \n", "Objetivos:", "Las grupos provisionales se pueden cambiar hasta que haga clic en %s.", "Asigna estas tropas provisionalmente a la aventura.",
      "La Guía puede estar desactualizada.", "La guía muestra algunos futuros posibles. En unos, la aventura acaba con éxito; en otros, fracasa de una manera particularmente horrible.", "Estos compañeros afectan actualmente a tu nivel de las tropas:", "Ticks:", "Turnos sobrevividos: %s", "Turnos empleados: %s", "Uso: Interrumpe las deliberaciones de la guía.", "Uso: Deja que el libro seleccione las tropas y las tácticas de la batalla.", "Uso: lee la guía, la cual determinará el destino de tu grupo de aventureros.", "Victorioso",
      "No se puede garantizar la victoria.", "Podría ganar si comienza con un: %s", "El nivel de tus tropas es la media de la de tus compañeros (%s), redondeando hacia abajo.", "[CD: %dT]",
    }
    or C == "frFR" and { -- 83/84 (98%)
      "\"... ou pas. Mieux vaut lire ce truc jusqu'au bout.\"", "\"Chapitre 1: Les mages doivent être au corps à corps.\"", "\"Ne croyez pas ses mensonges ! Les druides équilibre ne sont pas des rations d'urgence.\"", "\"Tout s'est déroulé comme prévu.\"", "\"Rien ne s'est déroulé comme prévu.\"", "\"Victoire à l'arrachée !\"", "\"Si proche, et pourtant si loin.\"", "\"Le résultat avait été prédit.\"", "\"Y a-t-il eu des doutes ?\"", "\"Avec votre chance, cela ne peut se terminer que d'une seule manière.\"",
      "%d |4aventure restante:aventures restantes;...", z, "%d |4compagnon est prêt:compagnons sont prêts; pour l'aventure.", "%d |4groupe restant:groupes restants;...", "(corps à corps)", "(Distant)", "Enregistrement détaillé d'une aventure terminée par vos compagnons.", "L'aventure expire dans :", "Rapport d'aventure", "Tous les compagnons sont prêts pour des aventures.",
      "Assigner", "Assigner à un groupe provisoire", "Décerné même si les aventuriers sont vaincus.", "Renforce l'allié le plus proche, ce qui augmente ses dégâts de {1} et réduit les dégâts subis de {2}% pendant 2 tours. Inflige {3} dégâts à soi-même.", "Vérification de la guérison...", "Effacer les groupes provisoires", "Cliquez pour terminer", "Les points de vie du combattant ont changé.", "Tout compléter", "Niveau actuel : %s",
      "Malédiction d'incertitude", "Guide de l'aventurier maudit", "Guide Tactique Maudit", "Affaiblit tous les ennemis, infligeant {1} dégâts par tour pendant {2} tours. Effet cumulable.", "Affaiblit tous les ennemis, inflige {1} dégâts ce tour et pendant les trois prochains tours. Et augmente tous les dégâts subis par l'ennemi le plus proche de {2} pendant trois tours.", "Défaite", "Course condamnée", "Durée :", "Modifier groupe", "Un tour sur deux, un ennemi aléatoire est attaqué à raison de {}% de sa vie maximum.",
      "Échouer cette mission accorde %s à chaque compagnon.", "Premier sort pendant le tour %d.", "XP compagnon", "Scénarios analysés :", "Soigne l'allié le plus proche pour {1}, et augmente tous les dégâts subis par cet allié de {2}% pendant 2 tours.", "Dans un groupe provisoire - %s", "Attaques en approche :", "Inflige {} dégâts à un ennemi aléatoire.", "Inflige {} de dégâts à tous les ennemis à portée.", "Inflige {} dégâts à tous les ennemis au corps à corps, et augmente ses propres dégâts de 20% pour trois tours",
      "Anima insuffisant", "Ça ne fait rien.", "Toutes les capacités n'ont pas été prises en compte.", "Toutes les possibilités n'ont pas été déterminées.", "Préliminaire :", "Quantité : %s", "Réduit les dégâts infligés par tous les ennemis de {}% pendant le prochain tour.", "Réduit les dégâts infligés par tous les ennemis de {}% pendant 2 tours.", "Réduit les dégâts subis par l'allié le plus proche de 5000% pendant deux tours.", "Vie restante des ennemis : %s",
      "Nécessite un aventurier dans le groupe", "Bientôt de retour :", "Récompenses :", "Sélection des aventuriers", "Envoyer les groupes provisoires", "Commencer l'aventure", "Départ imminent...", "Cible :", "Les groupes provisoires peuvent être modifiés jusqu'à ce que vous cliquiez sur %s.", "Assigne provisoirement ces novices à cette aventure.",
      "Le Guide est peut-être obsolète.", "Le guide vous montre un certain nombre de futurs possibles. Chez certains, l'aventure se termine par un triomphe ; dans d'autres, un échec particulièrement horrible.", "Ces compagnons affectent le niveau de vos troupes :", "Impulsion :", "Tours survécus : %s", "Tours effectués : %s", "Utiliser : Interrompre les délibérations du guide.", "Utiliser : Laissez le livre s'occuper des troupes et de la stratégie.", "Utiliser : Lisez le guide pour déterminer le sort de votre groupe d'aventures.", "Victorieux",
      "La victoire n'est pas assurée.", "Serait victorieux si on commençait dans : %s", "Le niveau de vos troupes est égal au niveau médian de vos compagnons (%s), arrondi à l'entier inférieur. Il ne diminuera pas si vous recrutez d'autres compagnons.", "[CD: %dT]",
    }
    or C == "itIT" and { -- 84/84 (100%)
      "\"... o no. Meglio leggere questa cosa fino alla fine.\"", "\"Capitolo 1: I maghi devono essere in mischia.\"", "\"Non fidarti delle sue menzogne! I druidi dell'equilibrio non sono razioni di emergenza.\"", "\"Tutto è andato come predetto.\"", "\"Non è andato affatto come previsto.\"", "\"Strappa la vittoria dalle fauci della sconfitta!\"", "\"Così vicino eppure così lontano.\"", "\"Il risultato era quello predetto.\"", "\"Ci sono mai stati dubbi?\"", "\"Con la tua fortuna, non può che finire in una sola maniera\"",
      "%d |4avventura rimanente:avventure rimanenti;...", "%d |4avventuriero è:avventurieri sono; in un gruppo provvisorio.", "%d |4avventuriero è pronto:avventurieri sono pronti; per le avventure.", "%d |4gruppo rimanente:gruppi rimanenti;...", "(mischia)", "(a distanza)", "Un registro dettagliato di un'avventura completata dai tuoi avventurieri.", "Avventura in scadenza:", "Rapporto dell'Avventura", "Tutti gli avventurieri sono pronti per le avventure.",
      "Assegna gruppo", "Assegna gruppo provvisorio", "Ottenuto anche se gli avventurieri vengono sconfitti.", "Aumenta i danni effettuati dall'alleato più vicino di {1} per 2 turni e riduce i danni subiti dall'alleato più vicino del {2}% per 2 turni. Infligge {3} danni a se stesso.", "Verifica del recupero della salute ...", "Cancella tutti i gruppi provvisori", "Clicca per completare", "La salute dell'avventuriero è cambiata.", "Completa tutto", "Avanzamento corrente: %s",
      "Maledizione dell'incertezza", "Guida Maledetta dell'Avventuriero", "Guida Tattica Maledetta", "Penalizza tutti i nemici, infliggendo {1} danni durante ciascuno dei successivi {2} turni. Molteplici applicazioni di questo effetto si sovrappongono.", "Penalizza tutti i nemici, infliggendo {1} danni questo turno e durante ciascuno dei 3 turni successivi. Aumenta tutti i danni subiti dal nemico più vicino di {2} per 3 turni.", "Sconfitta", "Avventura Spacciata", "Durata:", "Modifica gruppo", "Ogni altro turno, a un nemico casuale viene inflitto il {}% della sua salute massima.",
      "Fallire questa missione conferisce %s a ciascun avventuriero.", "Lanciato per la prima volta durante il turno %d.", "EXP per seguaci", "Futuri esaminati:", "Cura l'alleato più vicino di {1} e aumenta tutti i danni subiti dall'alleato del {2}% per 2 turni.", "Nel gruppo provvisorio - %s", "Attacchi in arrivo:", "Infligge {} danni a un nemico casuale.", "Infligge {} danni a tutti i nemici a portata.", "Infligge {} danni a tutti i nemici in mischia e aumenta i propri danni inflitti del 20% per 3 turni.",
      "Anima insufficiente", "Non fa nulla.", "Non tutte le abilità sono state prese in considerazione.", "Non tutti i risultati sono stati esaminati.", "Preliminare:", "Quantità: %s", "Riduce il danno inflitto da tutti i nemici del {}% durante il prossimo turno.", "Riduce i danni inflitti a tutti i nemici del {}% per 2 turni.", "Riduce del 5000% i danni subiti dall'alleato più vicino per 2 turni.", "Salute rimanente dei nemici: %s",
      "Richiede un avventuriero nel gruppo", "Tornano fra:", "Ricompense:", "Seleziona avventurieri", "Invia i Gruppi Provvisori", "Avvia l'avventura", "Iniziano fra ...", "Bersagli:", "I gruppi provvisori possono essere modificati finché non fai clic su %s.", "Assegna provvisoriamente questi novellini a questa avventura.",
      "La Guida potrebbe non essere aggiornata.", "La guida mostra una serie di possibili futuri. In alcuni, l'avventura finisce in trionfo; in altri, vedi un orribile fallimento.", "Questi avventurieri attualmente influenzano il livello delle tue truppe:", "Istanti:", "Turni sopravvissuti: %s", "Turni richiesti: %s", "Usa: Interrompe le decisioni della guida.", "Usa: Lascia che il libro scelga truppe e tattiche di battaglia.", "Uso: Leggi la Guida, determinando il destino del tuo gruppo di avventurieri.", "Vittoria",
      "La vittoria potrebbe non essere garantita.", "Potrebbe vincere se partisse tra: %s", "Il livello delle tue truppe è il livello mediano dei tuoi avventurieri (%s), arrotondato per difetto. Non diminuisce quando recluti altri avventurieri.", "[CD: %d turni]",
    }
    or C == "koKR" and { -- 83/84 (98%)
      "\"혹은, 끝까지 읽어보는게 나을지도 모릅니다.\"", "\"제 1 장: 마법사는 근접해야 한다.\"", "\"거짓에 속지 마세요! 조화 드루이드는 비상식량이 아닙니다.\"", "\"모든 것이 예견한 대로 이루어졌습니다.\"", "\"예상이 영 빗나갔네요.\"", "\"절망의 수렁에서 승리를 거머쥐었습니다!\"", "\"아쉽지만 아직 멀었어.\"", "\"예상한 결과입니다.\"", "\"의심의 여지가 있을까요?\"", "\"당신의 운에 맡긴다면, 이 끝에는 오직 한가지 길 밖에 없습니다.\"",
      "%d |4개의 모험:개의 모험들; 남음...", z, "%d 명의 동료가 모험을 떠날 준비가 되었습니다.", "%d |4개 파티:개의 파티들; 남음...", "(근접)", "(원거리)", "당신이 완료한 모험에 대한 세부 기록입니다.", "만료까지 남은 시간:", "모험 보고서", "모든 동료들이 모험을 떠날 준비가 되어 있습니다.",
      "파티 지정", "임시 파티 지정", "동료들이 지더라도 받는 보상입니다.", "가장 가까운 아군을 북돋아 2턴 동안 공격력을 {1} 만큼 증가시키고 받는 피해를 {2}% 만큼 감소시킵니다. 자신은 {3}만큼 피해를 입습니다.", "체력 회복을 확인하는 중...", "임시 편성 초기화", "완료", "동료의 생명력이 변경되었습니다.", "모두 완료", "현재 단계: %s",
      "불확실성의 저주", "저주받은 모험가의 안내서", "저주받은 전술 안내서", "모든 적을 약화시켜, 다음 {2}라운드 동안 {1}의 피해를 입힙니다. 이 효과는 중첩됩니다.", "모든 적에게 디버프를 남겨, 이번 턴과 다음 3턴 동안 {1}만큼 피해를 줍니다. 또한 3턴 동안 가까운 적에게 받는 피해를 {2}만큼 증가시킵니다.", "패배", "파멸의 임무", "소요시간:", "파티 편집", "두 턴에 한 번씩, 무작위 적군은 최대 체력의 {}% 만큼 피해를 입습니다.",
      "임무에 패하고 각 동료마다 %s을 받습니다.", "첫번째 시전은 %d라운드 동안 유지됩니다", "동료 경험치", "계산된 미래들:", "가장 가까운 아군을 {1}만큼 치유합니다. 2턴 동안 가장 가까운 아군이 받는 모든 피해를 {2}%만큼 증가시킵니다.", "임시 파티에 합류 중 - %s ", "공격 받음:", "무작위 적에게 {}의 피해를 입힙니다.", "범위 내의 모든 적에게 {}의 피해를 입힙니다.", "근접 범위에 있는 모든 적에게 {} 의 피해를 주고 자신의 공격력을 3턴 동안 20%만큼 증가시킵니다.",
      "령이 부족합니다.", "아무런 효과가 없습니다.", "계산에 포함되지 않은 능력이 있습니다.", "모든 결과가 반영되지 않았습니다.", "예상:", "수량: %s", "다음 턴동안 모든 적의 피해를 {}%만큼 감소시킵니다.", "2턴동 안 모든 적의 공격력을 {}% 만큼 감소시킵니다.", "가장 가까운 아군이 받는 피해를 2라운드 동안 5000% 만큼 감소시킵니다.", "적의 남은 체력: %s",
      "최소 1명의 동료가 포함되어야 합니다", "복귀 예정:", "보상:", "동료 선택", "임시 파티 보내기", "모험 시작", "곧 출발합니다..", "대상:", "임시 파티는 %s 버튼을 클릭하기 전 까지 수정할 수 있습니다.", "이 임무의 임시 편성에 아래 신참들을 배정합니다.",
      "안내서가 최신이 아닐지도 모릅니다.", "안내서가 여러가지 가능성을 보여줍니다. 그 중엔 승리하는 미래도 있고, 끔찍하게 실패하는 미래도 있습니다.", "이 동료들이 부대 레벨에 영향을 줍니다:", "효과 적용 주기", "%s 턴 동안 생존", "%s 턴 소요됨", "사용: 심사숙고중인 안내서를 멈춥니다.", "사용: 안내서가 병력과 전술을 선택합니다.", "사용: 안내서를 읽어, 모험을 떠날 동료들의 운명을 가늠합니다.", "승리",
      "승리가 확실치 않습니다.", "%s 후에 보내면 승리할 수도 있음", "병력 레벨은 동료들 중 레벨순으로 중앙값에 해당하는 동료(%s)의 레벨을 내림한 값으로 결정됩니다.", "[재사용: %d라운드]",
    }
    or C == "ruRU" and { -- 83/84 (98%)
      "«... или нет. Лучше прочти это до конца.»", "\"Глава 1: Маги идут в рукопашную\"", "\"Не верьте в эту ложь! Баланс друиды — не сухпаёк.\"", "\"Все вышло так, как и было предсказано.\"", "\"Все пошло не так, как ожидалось.\"", "\"Вырвать победу из пасти поражения!\"", "\"Так близко и всё ещё так далеко.\"", "\"Исход оказался таким, каким и был предсказан.\"", "\"Разве были какие-либо сомнения?\"", "\"С твоей удачей существует лишь один исход\"",
      "%d |4приключение:приключения:приключений; осталось...", z, "%d |4спутник готов:спутника готовы:спутников готовы; к приключениям.", "%d |4группа осталась:группы осталось:групп осталось;...", "(ближний бой)", "(дальний бой)", "Подробный отчёт о приключениях ваших спутников.", "Приключение исчезнет через:", "Отчёт о приключениях", "Все спутники готовы к приключениям.",
      "Назначить группу", "Назначить пробную группу", "Будет получен, даже если ваши спутники потерпят неудачу.", "Усиливает ближайшего союзника, увеличивая на {1} наносимый и снижая на {2}% получаемый им урон на два хода. Наносит {3} урона себе.", "Проверка восстановления здоровья...", "Очистить все пробные группы", "Нажмите для завершения", "Здоровье спутника изменилось.", "Завершить все", "Текущий прогресс: %s",
      "Проклятие Неопределённости", "Проклятое Руководство Искателя Приключений", "Проклятое Тактическое Руководство", "Ослабляет всех врагов, нанося {1} урона на каждом из следующих {2} ходов. Множественные применения этого эффекта суммируются.", "Ослабляет всех противников, нанося {1} урона мгновенно, а затем столько же в течение трёх последующих ходов. Увеличивает урон по ближайшему противнику на {2} на три хода.", "Поражение", "Обречённый поход", "Длительность:", "Изменить группу", "Каждый ход случайному противнику наносится урон в размере {}% его максимального запаса здоровья.",
      "Неудачное завершение этого задания даст %s каждому спутнику.", "Первое произнесение заклинания в течение хода %d.", "Опыт спутника", "Вариантов просчитано:", "Исцеляет ближайшего союзника на {1}, а также увеличивает входящий по нему урон на {2}% на два хода.", "В пробной группе - %s", "Входящие атаки:", "Наносит {} урона случайному противнику.", "Наносит {} урона всем противникам на расстоянии.", "Наносит {} урона всем противникам в ближнем бою и увеличивает собственный урон на 20% на три хода.",
      "Недостаточно анимы", "Ничего не делает.", "Не все способности были приняты в расчёт.", "Не все последствия были проанализированы.", "Предварительный:", "Количество: %s", "Уменьшает наносимый противниками урон на {}% во время следующего хода.", "Уменьшает наносимый всеми противниками урон на {}% на два хода.", "Снижает урон, получаемый ближайшим союзником, на 5000% на 2 хода.", "Оставшееся здоровье противника: %s",
      "Требуется спутник в группе", "Скоро возвращаются:", "Награды:", "Выберите соратников", "Отправить пробные группы", "Начать приключение", "Скоро начнётся...", "Цели:", "Пробные группы могут быть изменены, пока вы не нажали %s.", "Назначить пробную группу новичков на эту миссию.",
      "Руководство могло устареть.", "Руководство показывает вам возможные варианты исхода событий. В некоторых случаях приключение заканчивается победой, в других - ужасной неудачей.", "Эти спутники влияют на уровень ваших отрядов:", "Пульсация:", "Ходов выжили: %s", "Ходов прошло: %s", "Использование: прервать размышления Руководства.", "Использование: позволить Руководству выбрать отряды и расстановку.", "Использование: Прочитать Руководство, которое определит судьбу вашей группы.", "Победа!",
      "Победа не гарантирована.", "Победит, если начать через: %s", "Уровень ваших отрядов - это медианный уровень ваших спутников (%s), округлённый в меньшую сторону. Он не уменьшается, когда вы набираете дополнительных спутников.", "[Перезарядка: %dХ]",
    }
    or C == "zhCN" and { -- 83/84 (98%)
      "…或者不是。最好读到最后。", "第一章：法师都是近战。", "别被骗了！咕咕不是应急食品。", "一切正如预言里所说那样。", "结果并不如预言的那样。", "扭转乾坤！力挽狂澜！", "惜败。", "正如预言所说那样。", "有什么问题吗？", "走狗屎运的话可能会赢。",
      "%d 完成", "   共%d个随从可用，其中：","   %d个已加入预设。", "   %d个空闲。", "%d 已派遣", "（近战）", "（远程）", "一份由你的随从完成的冒险的详细记录。", "点击：提交你的冒险报告","过期时间：", "冒险报告", "所有的随从都准备好冒险了。",
      "预设", "左键：预设随从", "即使失败也会获得该经验。", "增益最近的队友，两轮内使其造成的全部伤害提高{1}，受到的全部伤害降低{2}%。对自身造成{3}点伤害。", "正在检查健康状况...", "清除所有预设队伍", "提交冒险报告","提交你的冒险任务情况，以使插件数据库更完备。","提交步骤：","1.访问该链接：","2.在discord频道里上传以下文本：","重置冒险报告", "点击以完成", "随从生命值发生了变化。", "全部完成", "当前进度：%s |n(注：当前游戏版本，有效的进度最高为20)",
      "结果不确定", "受诅咒的冒险指南", "随从匹配指南", "使全部敌人受到负面效果，接下来的{2}轮内每次造成{1}点伤害。此效果可以多次叠加。", "对所有敌人施加负面效果，在此轮和接下来的三轮中分别造成{1}伤害。此外，受到来自最近敌人三轮内的伤害提高{2}。", "失败", "经验队(失败！只吃经验)", "持续时间：", "编辑预设队伍", "每过一轮，一个随机敌人会受到{}％最大生命值的攻击。",
      "每个随从可从此失败的任务中获取%s经验。", "在第%d轮时先发", "随从经验", "正在匹配...", "为{1}治疗最近的盟友。使距离最近的盟友受到的伤害增加{2}%，持续两轮。", "预设队伍中：%s", "受到的攻击：", "对一个随机敌人造成{}的伤害。", "对所有远程敌人造成{}伤害。", "在近战中对所有敌人造成{}伤害，并在三轮内增加20%的自身伤害。",
      "心能不足", "精英", "稀有", "没什么效果。", "没有考虑到所有的技能。", "未检验全部结果。", "预估：", "数量：%s", "所有敌人下轮造成的伤害降低{}%。", "所有敌人两轮内造成的伤害减少{}%。", "使最近盟友两轮受到的伤害降低5000%。", "敌人剩余生命值：%s",
      "小队中需要一名随从", "完成时间：", "奖励：", "选择随从", "一键派遣", "右键：直接派遣", "即将开始…", "目标：", "预设未派遣还可修改", "优先派遣可升一级的随从吃经验",
      "插件版本已过期。", "指南展示了一系列可能的结果，既有胜利，也有可怕的失败。", "随从等级会影响你的部队等级。", "持续轮数：", "存活轮数：%s", "需要轮数：%s", "！匹配成功，点击载入。", "点击：自动完成队伍匹配。", "用法：阅读指南，然后决定你的冒险小队的命运。", "胜利",
      "无胜利匹配", "如果开始的话会赢得: %s", "部队等级：%s |n(注：你的部队等级是随从等级的中位数向下取整数值。)", "[冷却时间：%d轮]",
    }
    or C == "zhTW" and { -- 87/90 (96%)
      "…或者不是。最好讀到最后。", "第一章：法師都是近戰。", "別被騙了！咕咕不是應急食品。", "一切正如預言里所說那樣。", "結果并不如預言的那樣。", "扭轉乾坤！力挽狂瀾！", "惜敗。", "正如預言所說那樣。", "有什么問題嗎？", "走狗屎運的話可能會贏。",
      "%d 完成", "   共%d個隨從可用，其中：","   %d個已加入預設。", "   %d個空閑。", "%d 已派遣", "（近戰）", "（遠程）", "一份由你的隨從完成的冒險的詳細記錄。", "點擊：提交你的冒險報告","過期時間：", "冒險報告", "所有的隨從都準備好冒險了。",
      "預設", "左鍵：預設隨從", "即使失敗也會獲得該經驗。", "增益最近的隊友，兩輪內使其造成的全部傷害提高{1}，受到的全部傷害降低{2}%。對自身造成{3}點傷害。", "正在檢查健康狀況...", "清除所有預設隊伍", "提交冒險報告","提交你的冒險任務情況，以使插件數據庫更完備。","提交步驟：","1.訪問該鏈接：","2.在discord頻道里上傳以下文本：","重置冒險報告", "點擊以完成", "隨從生命值發生了變化。", "全部完成", "當前進度：%s |n(注：當前游戲版本，有效的進度最高為20)",
      "結果不確定", "受詛咒的冒險指南", "隨從匹配指南", "使全部敵人受到負面效果，接下來的{2}輪內每次造成{1}點傷害。此效果可以多次疊加。", "對所有敵人施加負面效果，在此輪和接下來的三輪中分別造成{1}傷害。此外，受到來自最近敵人三輪內的傷害提高{2}。", "失敗", "經驗隊(失敗！只吃經驗)", "持續時間：", "編輯預設隊伍", "每過一輪，一個隨機敵人會受到{}％最大生命值的攻擊。",
      "每個隨從可從此失敗的任務中獲取%s經驗。", "在第%d輪時先發", "隨從經驗", "正在匹配...", "為{1}治療最近的盟友。使距離最近的盟友受到的傷害增加{2}%，持續兩輪。", "預設隊伍中：%s", "受到的攻擊：", "對一個隨機敵人造成{}的傷害。", "對所有遠程敵人造成{}傷害。", "在近戰中對所有敵人造成{}傷害，并在三輪內增加20%的自身傷害。",
      "心能不足", "精英", "稀有", "沒什么效果。", "沒有考慮到所有的技能。", "未檢驗全部結果。", "預估：", "數量：%s", "所有敵人下輪造成的傷害降低{}%。", "所有敵人兩輪內造成的傷害減少{}%。", "使最近盟友兩輪受到的傷害降低5000%。", "敵人剩余生命值：%s",
      "小隊中需要一名隨從", "完成時間：", "獎勵：", "選擇隨從", "一鍵派遣", "右鍵：直接派遣", "即將開始…", "目標：", "預設未派遣還可修改", "優先派遣可升一級的隨從吃經驗",
      "插件版本已過期。", "指南展示了一系列可能的結果，既有勝利，也有可怕的失敗。", "隨從等級會影響你的部隊等級。", "持續輪數：", "存活輪數：%s", "需要輪數：%s", "！匹配成功，點擊載入。", "點擊：自動完成隊伍匹配。", "用法：閱讀指南，然后決定你的冒險小隊的命運。", "勝利",
      "無勝利匹配", "如果開始的話會贏得: %s", "部隊等級：%s |n(注：你的部隊等級是隨從等級的中位數向下取整數值。)", "[冷卻時間：%d輪]",
    }
    or C == "ptBR" and { -- 84/84 (100%)
      "\"... ou não. Melhor ler essa coisa por completo.\"", "Capítulo 1: Magos Corpo a Corpo", "\"Não acredite nas suas mentiras! Druidas Equilíbrio não são rações de emergência.\"", "\"Tudo aconteceu como previsto.\"", "\"Nada foi como esperado.\"", "Vitória arrancada das garras da derrota!", "Tão perto mas tão longe.", "\"O resultado foi como previsto.\"", "\"Havia alguma dúvida?\"", "\"Com a sua sorte, só há um jeito de isso acabar.\"",
      "%d |4aventura:aventuras; restando...", "%d |4companheiro está:companheiros estão; em um grupo provisório.\n", "%d |4companheiro está pronto:companheiros estão prontos; para aventuras.", "%d |4grupo:grupos; restando...", "(corpo a corpo)", "(longo alcance)", "Um registro detalhado de uma aventura realizada por seus companheiros.", "Aventura Expira em:", "Relatório da Aventura", "Todos os companheiros estão prontos para aventuras.",
      "Atribuir Grupo", "Atribuir grupo para tentativa", "Concedido mesmo que os aventureiros sejam derrotados.", "Beneficia o aliado mais próximo, aumentando todo dano causado em {1} e reduz todo o dano recebido por {2}% dois turnos. Causa {3} de dano a si mesmo.", "Checando recuperação de vida...", "Limpar todos os grupos provisórios", "Clique para completar", "A vida do companheiro foi alterada.", "Completar Tudo", "Progresso Atual: %s",
      "Maldição da Incerteza", "Guia Amaldiçoado dos Aventureiros", "Guia Tático Amaldiçoado", "Penaliza todos os inimigos, fazendo {1} dano durante os próximos dois turnos. Várias aplicações deste efeito, sobrepõem-se.", "Penaliza todos os inimigos, causando {1} de dano neste turno e durante os próximos três turnos. Adicionalmente, aumenta todo o dano tomado pelo inimigo mais próximo em {2} por três turnos.", "Derrota", "Operação Sentenciada", "Duração:", "Editar grupo", "A cada dois turnos, um inimigo aleatório é atacado com {}% de sua vida máxima.",
      "O fracasso nesta missão concede %s a cada companheiro.", "Primeiro lançamento durante o turno %d.", "EXP do Seguidor", "Futuros considerados:", "Cura o aliado mais próximo por {1}, e aumenta todo o dano tomado pelo aliado em {2}% por dois turnos.", "Em Grupo Provisório - %s", "Ataques recebidos:", "Causa {} de dano a um inimigo aleatório.", "Causa {} de dano a todos os inimigos em alcance.", "Causa {} de dano a todos os inimigos em alcance corpo-a-corpo, e aumenta o próprio dano infligido em 20% por três turnos.",
      "Anima insuficiente", "Não faz nada.", "Nem todas as habilidades foram levadas em consideração.", "Nem todos os resultados foram examinados.", "Preliminar:", "Quantidade: %s", "Reduz em {}% o dano causado por todos os inimigos no próximo turno.", "Reduz o dano causado por todos os inimigos em {}% por dois turnos.", "Reduz o dano recebido pelo aliado mais próximo em 5000% por duas rodadas.", "Vida restante do inimigo: %s",
      "Requer um companheiro no grupo", "Retornando em breve:", "Recompensas:", "Selecione aventureiros", "Enviar Grupos Provisórios", "Comece a aventura", "Começa em breve...", "Alvos:", "Grupos provisórios podem ser alterados até que você clique em %s.", "Indicar provisoriamente esses novatos a esta aventura.",
      "O Guia pode estar desatualizado.", "O guia mostra vários futuros possíveis. Em alguns, a aventura termina em triunfo; em outros, uma derrota particularmente horrível.", "Estes companheiros atualmente afetam o nível das suas tropas:", "Pulso:", "Turnos sobrevividos: %s", "Turnos tomados: %s", "Uso: Interrompe as deliberações do guia.", "Uso: Deixe o livro selecionar tropas e táticas de batalha.", "Use: Leia o guia, determinando o destino do seu grupo de aventureiros.", "Vitória",
      "A vitória não pôde ser garantida.", "Ganharia se começasse em: %s", "O nível das suas tropas é a média do nível dos seus companheiros (%s), arrendodada para baixo. Ele não diminui quando são recrutados companheiros adicionais.", "[Recarga: %dT]",
    } or nil
K = V and {
      "\"... or not. Better read this thing to the end.\"", "\"Chapter 1: Mages Must Melee.\"", "\"Do not believe its lies! Balance druids are not emergency rations.\"", "\"Everything went as foretold.\"", "\"Nothing went as expected.\"", "\"Snatch victory from the jaws of defeat!\"", "\"So close, and yet so far.\"", "\"The outcome was as foretold.\"", "\"Was there ever any doubt?\"", "\"With your luck, there is only one way this ends.\"",
      "%d |4adventure:adventures; remaining...", "%d |4zz","%d |4companion is:companions are; in a tentative party.", "%d |4companion is:companions are; ready for adventures.", "%d |4party:parties; remaining...", "(melee)", "(ranged)", "A detailed record of an adventure completed by your companions.", "Use: Feed the Cursed Adventurer's Guide.", "Adventure Expires In:", "Adventure Report", "All companions are ready for adventures.",
      "Assign Party", "Assign Tentative Party", "Awarded even if the adventurers are defeated.", "Buffs the closest ally, increasing all damage dealt by {1} and reducing all damage taken by {2}% for two turns. Inflicts {3} damage to self.", "Checking health recovery...", "Clear all tentative parties" ,"Wanted: Adventure Reports","The Cursed Adventurer's Guide hungers. Only the tales of your companions' adventures, conveyed in excruciating detail, will satisfy it.","To submit your adventure reports,","1. Visit:","2. Upload the following text in the logs channel:","Reset Adventure Reports", "Click to complete", "Companion health has changed.", "Complete All", "Current Progress: %s",
      "Curse of Uncertainty", "Cursed Adventurer's Guide", "Cursed Tactical Guide", "Debuffs all enemies, dealing {1} damage during each of the next {2} turns. Multiple applications of this effect overlap.", "Debuffs all enemies, dealing {1} damage this turn and during each of the next three turns. Additionally, increases all damage taken by the nearest enemy by {2} for three turns.", "Defeated", "Doomed Run", "Duration:", "Edit party", "Every other turn, a random enemy is attacked for {}% of their maximum health.",
      "Failing this mission grants %s to each companion.", "First cast during turn %d.", "Follower XP", "Futures considered:", "Heals the closest ally for {1}, and increases all damage taken by the ally by {2}% for two turns.", "In Tentative Party - %s", "Incoming attacks:", "Inflicts {} damage to a random enemy.", "Inflicts {} damage to all enemies at range.", "Inflicts {} damage to all enemies in melee, and increases own damage dealt by 20% for three turns.",
      "Insufficient anima", "Elite", "Rare", "It does nothing.", "Not all abilities have been taken into account.", "Not all outcomes have been examined.", "Preliminary:", "Quantity: %s", "Reduces all enemies' damage dealt by {}% during the next turn.", "Reduces all enemies' damage dealt by {}% for two turns.", "Reduces the damage taken by the closest ally by 5000% for two turns.", "Remaining enemy health: %s",
      "Requires a companion in the party", "Returning soon:", "Rewards:", "Select adventurers", "Send Tentative Parties", "Start the adventure", "Starting soon...", "Targets:", "Tentative parties can be changed until you click %s.", "Tentatively assign these rookies to this adventure.",
      "The Guide may be out of date.", "The guide shows you a number of possible futures. In some, the adventure ends in triumph; in others, a particularly horrible failure.", "These companions currently affect your troop level:", "Ticks:", "Turns survived: %s", "Turns taken: %s", "Use: Interrupt the guide's deliberations.", "Use: Let the book select troops and battle tactics.", "Use: Read the guide, determining the fate of your adventuring party.", "Victorious",
      "Victory could not be guaranteed.", "Would win if started in: %s", "Your troop level is the median level of your companions (%s), rounded down. It does not decrease when you recruit additional companions.", "[CD: %dT]",
}

local L = K and {}
for i=1,K and #K or 0 do
	L[K[i]] = V[i]
end

T.LT = L or nil
