
local LSM = LibStub and LibStub('LibSharedMedia-3.0', true)
if(not LSM) then return end

LSM:Register("font", "(EN) 2002", [[Fonts\2002B.TTF]], 255)
LSM:Register("font", "(EN) Skurri", [[Fonts\SKURRI_CYR.TTF]], 255)
LSM:Register("font", "(EN) MoK", [[Fonts\K_Pagetext.TTF]], 255)
LSM:Register("font", "(EN) Morpheus", [[Fonts\MORPHEUS_CYR.TTF]], 255)
LSM:Register("font", "(EN) Adventure", [[Interface\Addons\!!!163UI!!!\Textures\fonts\Adventure.ttf]], 255)

LSM:Register("statusbar", "Aluminium",			[[Interface\Addons\!!!163UI!!!\Textures\statusbar\Aluminium]])
LSM:Register("statusbar", "Armory",				[[Interface\Addons\!!!163UI!!!\Textures\statusbar\Armory]])
LSM:Register("statusbar", "BantoBar",			[[Interface\Addons\!!!163UI!!!\Textures\statusbar\BantoBar]])
--LSM:Register("statusbar", "DarkBottom",         [[Interface\AddOns\!!!163UI!!!\Textures\statusbar\DarkBottom]])
LSM:Register("statusbar", "Empty",              [[Interface\Addons\!!!163UI!!!\Textures\statusbar\Empty]])
LSM:Register("statusbar", "Flat",				[[Interface\Addons\!!!163UI!!!\Textures\statusbar\Flat]])
LSM:Register("statusbar", "Glaze2",			    [[Interface\AddOns\!!!163UI!!!\Textures\statusbar\Glaze2]])
--LSM:Register("statusbar", "Gloss",              [[Interface\AddOns\!!!163UI!!!\Textures\statusbar\Gloss]])
--LSM:Register("statusbar", "Graphite",			[[Interface\AddOns\!!!163UI!!!\Textures\statusbar\Graphite]])
--LSM:Register("statusbar", "Grid",				[[Interface\AddOns\!!!163UI!!!\Textures\statusbar\Grid]])
--LSM:Register("statusbar", "Healbot",			[[Interface\AddOns\!!!163UI!!!\Textures\statusbar\Healbot]])
LSM:Register("statusbar", "LiteStep",           [[Interface\AddOns\!!!163UI!!!\Textures\statusbar\LiteStep]])
--LSM:Register("statusbar", "LiteStepLite",       [[Interface\AddOns\!!!163UI!!!\Textures\statusbar\LiteStepLite]])
LSM:Register("statusbar", "Minimalist",			[[Interface\Addons\!!!163UI!!!\Textures\statusbar\Minimalist]])
LSM:Register("statusbar", "Otravi",				[[Interface\Addons\!!!163UI!!!\Textures\statusbar\Otravi]])
LSM:Register("statusbar", "Outline",			[[Interface\AddOns\!!!163UI!!!\Textures\statusbar\Outline]])
LSM:Register("statusbar", "Perl",				[[Interface\AddOns\!!!163UI!!!\Textures\statusbar\Perl]])
LSM:Register("statusbar", "Round",			    [[Interface\AddOns\!!!163UI!!!\Textures\statusbar\Round]])
LSM:Register("statusbar", "Smooth",			    [[Interface\AddOns\!!!163UI!!!\Textures\statusbar\Smooth]])
LSM:Register("statusbar", "Solid",              [[Interface\Buttons\WHITE8X8]])
--LSM:Register("statusbar", "Tooltip",            [[Interface\Tooltips\UI-Tooltip-Background]])
--LSM:Register("statusbar", "TukTex",			[[Interface\AddOns\!!!163UI!!!\Textures\statusbar\TukTex]])
--LSM:Register("statusbar", "X-Perl",             [[Interface\AddOns\!!!163UI!!!\Textures\statusbar\X-Perl]])
LSM:Register('statusbar', 'Charcoal',			[[Interface\Addons\!!!163UI!!!\Textures\statusbar\Charcoal]])
LSM:Register('statusbar', 'Diagonal',			[[Interface\Addons\!!!163UI!!!\Textures\statusbar\Diagonal]])
LSM:Register('statusbar', 'Smooth v2',			[[Interface\Addons\!!!163UI!!!\Textures\statusbar\Smoothv2]])
LSM:Register('statusbar', 'Smudge',				[[Interface\Addons\!!!163UI!!!\Textures\statusbar\Smudge]])