local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_CovenantSanctum", "zhCN", false, true)

if not L then return end
-- Simplified Chinese localization by nbyang ( https://www.curseforge.com/members/nbyang )
if L then
L["config_easy_waypoints"] = "便捷导航"
L["config_easy_waypoints_desc"] = "使你可以更简单的建立导航路线, 你可以通过右键单击设定导航点或者使用CTRL+右键单击获得更多选项."
L["config_icon_alpha"] = "图标透明度"
L["config_icon_alpha_desc"] = "修改图标透明度"
L["config_icon_scale"] = "图标大小"
L["config_icon_scale_desc"] = "调整图标的大小"
L["config_innkeeper"] = "旅店"
L["config_innkeeper_desc"] = "显示旅店的位置"
L["config_mail"] = "邮箱"
L["config_mail_desc"] = "显示邮箱的位置"
L["config_others"] = "其他"
L["config_others_desc"] = "显示其他的点"
L["config_plugin_desc"] = "在世界地图和小地图中提示圣所的各种NPC"
L["config_plugin_name"] = "圣所"
L["config_portal"] = "传送门"
L["config_portal_desc"] = "显示传送门的位置"
L["config_reforge"] = "物品升级"
L["config_reforge_desc"] = "显示物品升级NPC的位置"
L["config_renown"] = "名望记录者"
L["config_renown_desc"] = "显示名望记录者位置"
L["config_restore_nodes"] = "恢复被隐藏的图标"
L["config_restore_nodes_desc"] = "恢复被你隐藏掉的图标"
L["config_restore_nodes_print"] = "所有隐藏的图标已被恢复"
L["config_stablemaster"] = "兽栏管理员"
L["config_stablemaster_desc"] = "显示兽栏管理员的位置"
L["config_tab_general"] = "通用"
L["config_travelguide_note"] = "|cFFFF0000* 由于 TravelGuide 的存在, 本模块不会启用 |r"
L["config_vendor"] = "商人"
L["config_vendor_desc"] = "显示商人的位置"
L["config_weaponsmith"] = "武器兑换商"
L["config_weaponsmith_desc"] = "显示武器兑换商的位置"
L["config_what_to_display"] = "选择要显示的图标"
L["config_what_to_display_desc"] = "根据你的需要在下面调整所显示的图标"
L["handler_context_menu_add_tomtom"] = "添加到 TomTom"
L["handler_context_menu_addon_name"] = "HandyNotes: 圣所"
L["handler_context_menu_hide_node"] = "隐藏这个图标"
L["handler_tooltip_requires"] = "需要"
L["handler_tooltip_sanctum_feature"] = "圣所升级"
L["handler_tooltip_TNTIER"] = "传送网络第 %s 层"
L["Mailbox"] = "邮箱"
L["Portal to Oribos"] = "奥利波斯传送门"
end