local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_CovenantSanctum", "zhTW", false, true)

if not L then return end
-- Traditional Chinese localization by RainbowUI ( https://www.curseforge.com/members/rainbowui )
if L then
L["config_easy_waypoints"] = "快速導航"
L["config_easy_waypoints_desc"] = "簡化建立路線導航的方法，只要點一下滑鼠右鍵便能設定導航目的地，CTRL + 右鍵點擊會有更多選項。"
L["config_icon_alpha"] = "圖示透明度"
L["config_icon_alpha_desc"] = "圖示的透明度。"
L["config_icon_scale"] = "圖示大小"
L["config_icon_scale_desc"] = "圖示的縮放大小。"
L["config_innkeeper"] = "旅店老闆"
L["config_innkeeper_desc"] = "顯示旅店店老闆的位置。"
L["config_mail"] = "郵箱"
L["config_mail_desc"] = "顯示郵箱的位置。"
L["config_others"] = "其他"
L["config_others_desc"] = "顯示其他所有的地點。"
L["config_plugin_desc"] = "在世界地圖和小地圖中顯示你的誓盟聖所中 NPC 和地點。"
L["config_plugin_name"] = "誓盟聖所"
L["config_portal"] = "傳送門"
L["config_portal_desc"] = "顯示傳送門或傳送點的位置。"
L["config_reforge"] = "護甲強化"
L["config_reforge_desc"] = "顯示護甲強化的位置。"
L["config_renown"] = "名望守衛者"
L["config_renown_desc"] = "顯示名望守衛者的位置。"
L["config_restore_nodes"] = "恢復被隱藏的地點"
L["config_restore_nodes_desc"] = "恢復所有點右鍵選擇隱藏的地點。"
L["config_restore_nodes_print"] = "所有被隱藏的地點都已恢復"
L["config_stablemaster"] = "獸欄管理員"
L["config_stablemaster_desc"] = "顯示獸欄管理員的位置。"
L["config_tab_general"] = "一般"
L["config_travelguide_note"] = "|cFFFF0000*已透過 HandyNotes: TravelGuide 啟動。|r"
L["config_vendor"] = "商人"
L["config_vendor_desc"] = "顯示商人的位置。"
L["config_weaponsmith"] = "武器鍛造師"
L["config_weaponsmith_desc"] = "顯示武器鍛造師的位置。"
L["config_what_to_display"] = "選擇要顯示什麼"
L["config_what_to_display_desc"] = "這些設定控制要顯示哪類的圖示。"
L["handler_context_menu_add_tomtom"] = "加入 TomTom"
L["handler_context_menu_addon_name"] = "地圖標記: 誓盟聖所"
L["handler_context_menu_hide_node"] = "隱藏這個地點"
L["handler_tooltip_requires"] = "需要"
L["handler_tooltip_sanctum_feature"] = "升級聖所"
L["handler_tooltip_TNTIER"] = "傳送網路第 %s 層。"
L["Mailbox"] = "郵箱"
L["Portal to Oribos"] = "奧睿博司傳送門"
end