-- CL.Core
-- Diablohu(diablohudream@gmail.com)
-- yleaf(yaroot@gmail.com)
-- Mini Dragon(projecteurs@gmail.com) <流浪者酒馆-Brilla@金色平原> 20211214

if GetLocale() ~= "zhCN" then return end
if not DBM_COMMON_L then DBM_COMMON_L = {} end

local CL = DBM_COMMON_L

CL.NONE								= "无"
CL.RANDOM							= "随机"
CL.NEXT								= "下一个 %s"
CL.COOLDOWN							= "%s 冷却"
CL.UNKNOWN							= "未知"
CL.LEFT								= "左"
CL.RIGHT							= "右"
CL.BOTH								= "两边"
CL.BEHIND							= "后面"
CL.BACK								= "后"
CL.SIDE								= "旁边"
CL.TOP								= "上"
CL.BOTTOM							= "下"
CL.MIDDLE							= "中"
CL.FRONT							= "前"
CL.EAST								= "东"
CL.WEST								= "西"
CL.NORTH							= "北"
CL.SOUTH							= "南"
CL.INTERMISSION						= "转场"
CL.ORB								= "球"
CL.ORBS								= "球"
CL.RING								= "环"
CL.RINGS							= "环"
CL.CHEST							= "奖励宝箱"
CL.NO_DEBUFF						= "没有 %s"
CL.ALLY								= "队友"
CL.ALLIES							= "人群"
CL.ADD								= "小怪"
CL.ADDS								= "小怪"
CL.BIG_ADD							= "大怪"
CL.BOSS								= "Boss"
CL.EDGE								= "房间边缘"
CL.FAR_AWAY							= "远离"
CL.BREAK_LOS						= "卡视角"
CL.RESTORE_LOS						= "恢复视角"
CL.SAFE								= "安全"
CL.NOTSAFE							= "不安全"
CL.SHIELD							= "护盾"
CL.PILLAR							= "柱子"
CL.SHELTER							= "遮挡"
CL.INCOMING							= "%s 即将到来"
CL.BOSSTOGETHER						= "Boss 靠近"
CL.BOSSAPART						= "Boss 分开"
CL.TANKCOMBO						= "坦克连击"
CL.TANKCOMBOC						= "坦克连击 (%s)"
CL.AOEDAMAGE						= "AOE 伤害"
CL.SEASONAL							= "季节性"
